### ISSUE TITLE
HPX V1.6.0 fails on Fedora release

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5275] opened 2021-04-05 11:46 UTC
@diehlpk reported:

Hi,

HPX 1.6.0 started to fail on Fedora release which is shipped in three weeks,
Could you please have a look?

https://kojipkgs.fedoraproject.org/work/tasks/8255/64998255/build.log
https://pastebin.com/ajjsDKEp

Thanks,
Patrick

**Comment by msimberg** [comment] 2021-04-06 07:47
@hkaiser the fix in https://gist.github.com/hkaiser/554e5866ab5ac0111901cbcdaa19b69c is fair, but so is the warning. I wonder what the semantics of that proxy iterator type should be? If it's up to the caller to keep the `v_` member alive long enough we can add a move assignment operator, which does the same as the copy assignment operator. I'm also guessing that existing assignment operator should actually be sfinae-d out for `vector_value_proxy` right-hand sides?

**Comment by hkaiser** [comment] 2021-04-06 12:15
> @hkaiser the fix in https://gist.github.com/hkaiser/554e5866ab5ac0111901cbcdaa19b69c is fair, but so is the warning. I wonder what the semantics of that proxy iterator type should be? If it's up to the caller to keep the `v_` member alive long enough we can add a move assignment operator, which does the same as the copy assignment operator. I'm also guessing that existing assignment operator should actually be sfinae-d out for `vector_value_proxy` right-hand sides?

Yes to both comments. I can't reproduce the issue locally, though.

**Comment by msimberg** [comment] 2021-04-06 13:18
> > @hkaiser the fix in https://gist.github.com/hkaiser/554e5866ab5ac0111901cbcdaa19b69c is fair, but so is the warning. I wonder what the semantics of that proxy iterator type should be? If it's up to the caller to keep the `v_` member alive long enough we can add a move assignment operator, which does the same as the copy assignment operator. I'm also guessing that existing assignment operator should actually be sfinae-d out for `vector_value_proxy` right-hand sides?
> 
> Yes to both comments. I can't reproduce the issue locally, though.

Neither can I (where locally means gcc trunk on godbolt with a small test example, gcc 9-11 all have similar behaviour)... It's possible that it's a regression/change in GCC 11 (it's still not released).

**Comment by diehlpk** [comment] 2021-05-18 13:27
Since the build is fixed on Fedora, I will close the ticket.

**Closed by diehlpk** 2021-05-18 13:27 UTC
Labels: type: defect
