### ISSUE TITLE
Install failure on OS X -- duplicate rpath entries

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#1299] opened 2014-10-28 02:23 UTC
I am using OS X Yosemite. I currently cannot build HPX from source. This used to work fine on Mavericks.

The build itself goes fine. The install then emits this error message:

```
/opt/local/bin/install_name_tool: object: /Users/eschnett/SIMFACTORY/hpx-master/install/lib/hpx/libparcel_coalescing.0.9.10.dylib malformed object (load command 39 cmdsize is zero)
```

If I use "otool -l" on this library, then I see that it is indeed broken; I see the same error message.

Using "otool -l" on the original library (the one in the build directory), I see that it is healthy. Just before load command 39 (the load commands are numbered) are the definitions for LC_RPATH, i.e. the path names provided via the -rpath command. I see that the path "/Users/eschnett/SIMFACTORY/boost-1_56_0/install/lib" appears twice.

According to my interpretation of the man page of "install_name_tool" (and Google), this should not be the case -- each path should be unique.

It appears that the commands in the file "cmake_install.cmake" should rewrite these LC_RPATH paths, changing the HPX build directory to the HPX install directory. In my build, these commands are in lines 43 to 59 of this file, and read

```
      execute_process(COMMAND "/opt/local/bin/install_name_tool"
        -id "libparcel_coalescing.0.dylib"
        -change "/Users/eschnett/SIMFACTORY/hpx-master/build/lib/libhpx.0.dylib" "libhpx.0.dylib"
        -change "/Users/eschnett/SIMFACTORY/hpx-master/build/lib/libhpx_serialization.0.dylib" "libhpx_serialization.0.dylib"
        "${file}")
      execute_process(COMMAND /opt/local/bin/install_name_tool
        -delete_rpath "/Users/eschnett/SIMFACTORY/hpx-master/build/lib"
        "${file}")
      execute_process(COMMAND /opt/local/bin/install_name_tool
        -delete_rpath "/Users/eschnett/SIMFACTORY/boost-1_56_0/install/lib"
        "${file}")
      execute_process(COMMAND /opt/local/bin/install_name_tool
        -add_rpath "/Users/eschnett/SIMFACTORY/hpx-master/install/lib"
        "${file}")
      execute_process(COMMAND /opt/local/bin/install_name_tool
        -add_rpath "/Users/eschnett/SIMFACTORY/boost-1_56_0/install/lib"
        "${file}")
```

It appears that these calls to "install_name_tool" somehow break the library. I think that this is an error either in install_name_tool, or in another system tool, or in clang 3.5 that I am using to build HPX, or in cmake 3.0.

Would it be possible to manually uniquify the -rpath options that are passed to the linker, so that each path is listed only once? The file CMakeFiles/parcel_coalescing_lib.dir/link.txt contains indeed two identical -rpath options for the offending path. Unfortunately, my cmake-fu (or lack thereof) doesn't allow me to try this myself.

See also https://github.com/pandegroup/openmm/issues/295, which seems to describe exactly my situation.

**Comment by hkaiser** [comment] 2015-02-25 17:57
Is this still an issue after the recent build system changes?

**Comment by eschnett** [comment] 2015-02-26 00:20
Yes, I confirm that the issue is still present.

**Comment by sithhell** [comment] 2015-02-27 13:17
This has been fixed by disabling the full RPATH setting of cmake, which seemed to have cause the problem (see eaf73b9).
Buildbot is able to install all libraries just fine (http://hermione.cct.lsu.edu/builders/hpx_appleclang_5_1_boost_1_56_osx_x86_64_release/builds/242/steps/install/logs/stdio).
Please reopen if it is still not working for you.

**Comment by eschnett** [comment] 2015-02-27 15:09
The build and install steps are now working fine. However, I see this error when I build and run a simple HPX test:
```
mpirun -np 1 ./hello-cc

dyld: Library not loaded: libhpx.0.dylib
  Referenced from: /Users/eschnett/SIMFACTORY/hpx-master/test/test-0/./hello-cc
  Reason: no suitable image found.  Did find:
	/Users/eschnett/SIMFACTORY/hpx-master/install/lib/libhpx.0.dylib: malformed mach-o image: load command #40 length (0) too small in /Users/eschnett/SIMFACTORY/hpx-master/install/lib/libhpx.0.dylib
```
This is essentially the same error message as before.

Also, 99% of the HPX self-tests fail. Here is the beginning of the respective output (run before installing HPX):
```
Running tests...
Test project /Users/eschnett/SIMFACTORY/hpx-master/build
        Start   1: tests.regressions.id_type_ref_counting_1032
  1/223 Test   #1: tests.regressions.id_type_ref_counting_1032 ...............................................***Failed    0.16 sec
        Start   2: tests.regressions.multiple_init
  2/223 Test   #2: tests.regressions.multiple_init ...........................................................***Failed    0.05 sec
        Start   3: tests.regressions.id_type_ref_counting_1032_4
  3/223 Test   #3: tests.regressions.id_type_ref_counting_1032_4 .............................................***Failed    0.05 sec
```

**Comment by sithhell** [comment] 2015-02-27 15:58
I am not entirely sure what's going on there. Looking at buildbot, it seems mostly fine:
http://hermione.cct.lsu.edu/builders/hpx_appleclang_5_1_boost_1_56_osx_x86_64_release/builds/242
Though I buildbot does indeed not tr

Just tried to reproduce the error with the following commands:
```
bash-3.2$ cd /Users/buildbot/slave/hpx_appleclang_5_1_boost_1_56_osx_x86_64_debug/install/
bash-3.2$ cd bin/
bash-3.2$ ./async_io
dyld: Library not loaded: libhpxd.0.dylib
  Referenced from: /Users/buildbot/slave/hpx_appleclang_5_1_boost_1_56_osx_x86_64_debug/install/bin/./async_io
  Reason: image not found
Trace/BPT trap: 5
bash-3.2$ export DYLD_LIBRARY_PATH=/Users/buildbot/slave/hpx_appleclang_5_1_boost_1_56_osx_x86_64_debug/install/lib:$DYLD_LIBRARY_PATH
bash-3.2$ ./async_io
OS-thread: Write this string to std::cout
HPX-thread: The asynchronous IO operation returned: 0
bash-3.2$ 
```

This seems to work. So you can either have the rpath error preventing you to install at all or set the DYLD_LIBRARY_PATH environment variable to contain the correct path. This looks like a cmake bug I have no idea how to work around otherwise. What do you suggest?

**Comment by eschnett** [comment] 2015-02-27 23:33
The error I see indicates that the library was installed in the wrong way, as the library is found but contains an error: `malformed mach-o image`. This indicates that the library was destroyed while installing it, but the installer did not notice. The problem is `install_name_tool`, which cannot handle duplicate rpath entries.

Setting `DYLD_LIBRARY_PATH` would work fine for me -- I'm using it for other libraries -- but as I mentioned, this is not the problem here.

**Closed** 2019-08-03 08:30 UTC
Labels: compiler: clang, platform: Mac OSX, tag: wontfix, type: defect
