### ISSUE TITLE
CMake does not work for HPX 1.7.0 on Piz Daint

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5504] opened 2021-08-11 21:24 UTC
## Expected Behavior

CMake should be able to generate the Makefile. The same setup works for HPX 1.6.0 and HPX 1.5.1 on Piz Daint. However, for HPX 1.7.0 this error occurs.

## Actual Behavior

```
HPX will be installed to /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0


-- Configuring done
CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/lib/pkgconfig/hpx_application_release.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/lib/pkgconfig/hpx_application.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/CMakeFiles/hpx_application_release.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/CMakeFiles/hpx_application.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/lib/pkgconfig/hpx_component_release.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/lib/pkgconfig/hpx_component.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/CMakeFiles/hpx_component_release.pc


CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   /scratch/snx3000/pdiehl/Octo-Mpi/build/hpx_1.7.0/build/CMakeFiles/hpx_component.pc


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    LIBFABRIC_ROOT


CMake Generate step failed.  Build files cannot be regenerated correctly.

```

## Steps to Reproduce the Problem

  1. Get HPX 1.7.0 and try to run CMake on Piz Daint

## Specifications

... Please describe your environment

  - HPX Version: 1.7.0
  - Platform (compiler, OS): Piz Daint

**Comment by msimberg** [comment] 2021-08-12 07:31
@diehlpk are you using the same version of CMake in both cases? And are you using CUDA?

This is caused by generator expressions ending up in our pkgconfig files which we currently can't deal with properly. This will be "fixed" either by us removing pkgconfig support, or by newer CMakes which will let us deal with it properly (the minimum required version doesn't let us do that yet).

Right now you can work around it by setting `HPX_WITH_PKGCONFIG=OFF`.

**Comment by diehlpk** [comment] 2021-08-12 13:51
@msimberg Yes, I am using CUDA and the same CMake version.

**Comment by msimberg** [comment] 2021-08-13 16:01
Closing as wontfix (for now, see https://github.com/STEllAR-GROUP/hpx/issues/5504#issuecomment-897414039).

**Closed by msimberg** 2021-08-13 16:01 UTC
Labels: category: CMake, platform: CUDA
