### ISSUE TITLE
Running with TCP parcelport causes immediate crash or freeze

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1754] opened 2015-09-17 16:44 UTC
When trying to run octotiger with TCP parcelport on 100 SuperMIC nodes I either get an immediate freeze up and no output, or this: https://gist.github.com/dmarce1/6473aad6059387ad5832

**Comment by hkaiser** [comment] 2015-09-17 18:52
Can you show us your PBS script, please?

**Comment by dmarce1** [comment] 2015-09-17 19:00
I ran it interactively using this command: 


pbsdsh -u /work/dmarce1/octotiger/release/env.sh /work/dmarce1/octotiger/release/octotiger --hpx:nodes=`uniq $PBS_NODEFILE` --hpx:endnodes -Ihpx.stacks.use_guard_pages=0 -Ihpx.parcel.mpi.enable=0 -t20



#!/bin/bash


the env.sh file I use is:
----------------------------------------------------------------------------------------------------------------------------
export LD_LIBRARY_PATH="/home/dmarce1/lib:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/mpirt/lib/intel64:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/ipp/../compiler/lib/intel64:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/ipp/lib/intel64:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/ipp/tools/intel64/perfsys:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/compiler/lib/intel64:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/mkl/lib/intel64:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/tbb/lib/intel64/gcc4.4:/usr/local/compilers/Intel/parallel_studio-2015u3/composer_xe_2015.3.187/debugger/libipt/intel64/lib:/usr/local/packages/mvapich2/2.0/INTEL-14.0.2/lib:/usr/local/compilers/gcc/4.9.0/lib/gcc/x86_64-unknown-linux-gnu/4.9.0:/usr/local/compilers/gcc/4.9.0/lib64:/usr/local/compilers/gcc/4.9.0/lib:/usr/local/compilers/Intel/cluster_studio_xe_2013.1.046/composer_xe_2013_sp1.2.144/compiler/lib/intel64:/usr/local/compilers/Intel/cluster_studio_xe_2013.1.046/composer_xe_2013_sp1.2.144/mkl/lib/intel64"

"$@"
-------------------------------------------------------------------------------------------------------------------

**Comment by hkaiser** [comment] 2015-09-24 16:23
How do you build your application? The error seems to be caused by an allocator mismatch (i.e. a memory region is free'd by a different allocator than it was allocated).

**Comment by hkaiser** [comment] 2015-11-19 17:53
@dmarce1 This should work now (after #1872 has been merged). Could you verify, please?

**Comment by quantomb** [comment] 2015-11-20 16:33
FWIT I cannot get my program to run. It immediately crashes with the statement:

hpx::init: exception caught: character conversion failed

the submission script is as before:

pbdsh -u /home/skella1/pargit/parquet/env.sh /home/skella1/pargit/parquet/build/workbench/workbench --hpx:nodes=`cat $PBS_NODEFILE` --hpx:endnodes --nt=256 --iter=5 --hpx:print-bind --hpx:0:print-counter=/threadqueue{locality#*/total}/length -t6

**Comment by hkaiser** [comment] 2015-11-20 16:45
@quantomb This error message is printed if something goes wrong during parsing the command line. Could you please run your application on one node using gdb and stop at the the point where the exception is being thrown (issue a `catch throw` command before running the application) and give me the stack-backtrace (output of the `bt` command)?

**Comment by quantomb** [comment] 2015-11-20 16:57
I believe what you want is here

https://gist.github.com/quantomb/393aebfb07a90ee33d4f#file-tcpback-txt

**Comment by hkaiser** [comment] 2015-11-20 17:07
@quantomb Yes, that the thing I was looking for, thanks. I'd need the same for the debug version, however as the Release version does not give us any clue where the exception is actually thrown.

**Comment by hkaiser** [comment] 2015-11-20 17:09
@quantomb also, the execption seem to happen during the actual command line parsing. Could you please copy/paste your command line again? What does `cat $PBS_NODEFILE` print?

**Comment by quantomb** [comment] 2015-11-20 17:15
The odd part is the stack trace I just sent you was with a simpler test. I started an interactive job and ran this:

gdb ./build/workbench/workbench

There were no commandline arguments given and it still complained. Since I was on an interactive job I did not feed in $PBS_NODEFILE so I don't think parsing that is the problem. I will recompile in debug mode and post what that gives me.

**Comment by quantomb** [comment] 2015-11-20 17:36
As an update I am having trouble compiling in debug mode. I get the following error when trying to compile my program.

CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/workingver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'
CMakeFiles/workbench_exe.dir/main.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/workingver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'

I think I understand that something a function or variable doesn't exist but I am looking to see where or why

**Comment by hkaiser** [comment] 2015-11-20 17:53
You've compiled HPX against one version of Boost (1.58.0) but use a different version for your application.

**Comment by zao** [comment] 2015-11-20 18:15
Do we also parse the set of environment variables? It's possible that one contains data or text with a different encoding which might trip up some general-purpose code that assumes UTF-8 or low ASCII. It's not uncommon for legacy systems to have Latin-1 lying around.

**Comment by quantomb** [comment] 2016-02-09 18:37
@hkaiser I am returning to this problem. I do not get any error when I run on release. When I switch to master I get 
hpx::init: exception caught: character conversion failed

If I enable debug mode, both for hpx and my program, I get cannot even compile as I get the following error (which is the same as previously reported)

CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/curver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'
CMakeFiles/workbench_exe.dir/main.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/curver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'


You reported that this means that I compiled HPX against one version of boost and my program uses a different version which I do not understand as I manually set 
-DBOOST_ROOT=/work/skella1/boost_1_58_0 \
when I compile each.

**Comment by hkaiser** [comment] 2016-02-09 18:48
It's probably cmake again. Please verify that cmake is actually using the directories of dependent libraries you specified (look into `CMakeCache.txt` or use `ccmake`). Alternatively, build using `make VERBOSE=1 ...` to see the issued command lines and look for the Boost include directory and library references there.

Otherwise, please post your build logs and your `CMakeCache.txt` here (i.e. link to a paste site).

**Comment by quantomb** [comment] 2016-02-09 19:17
I get the following on CMakeCache.txt

From HPX:
//No help, variable specified on the command line.
BOOST_ROOT:PATH=/work/skella1/boost_1_58_0
From my program:
//No help, variable specified on the command line.
BOOST_ROOT:UNINITIALIZED=/work/skella1/boost_1_58_0

They seem the same to me

**Comment by hkaiser** [comment] 2016-02-09 20:01
It's difficult to tell from the distance what's going on for you. Can you run make with the `VERBOSE=1` and verify that the boost directory used as include paths match for both, your program and HPX.

**Comment by quantomb** [comment] 2016-02-09 20:08
Here is the output including the error

-- The CXX compiler identification is GNU 4.9.0
-- Check for working CXX compiler: /usr/local/compilers/gcc/4.9.0/bin/c++
-- Check for working CXX compiler: /usr/local/compilers/gcc/4.9.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The C compiler identification is GNU 4.9.0
-- Check for working C compiler: /usr/local/compilers/gcc/4.9.0/bin/gcc
-- Check for working C compiler: /usr/local/compilers/gcc/4.9.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Using jemalloc allocator.
-- Found MKL: /usr/local/compilers/Intel/composer_xe_2013.5.192/mkl/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/skella1/pargit/parquet/build
/home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -H/home/skella1/pargit/parquet/workbench -B/home/skella1/pargit/parquet/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -E cmake_progress_start /home/skella1/pargit/parquet/build/CMakeFiles /home/skella1/pargit/parquet/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/skella1/pargit/parquet/build'
make -f workbench/CMakeFiles/workbench_exe.dir/build.make workbench/CMakeFiles/workbench_exe.dir/depend
make[2]: Entering directory `/home/skella1/pargit/parquet/build'
cd /home/skella1/pargit/parquet/build && /home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -E cmake_depends "Unix Makefiles" /home/skella1/pargit/parquet/workbench /home/skella1/pargit/parquet/workbench/workbench /home/skella1/pargit/parquet/build /home/skella1/pargit/parquet/build/workbench /home/skella1/pargit/parquet/build/workbench/CMakeFiles/workbench_exe.dir/DependInfo.cmake --color=
Dependee "/home/skella1/pargit/parquet/build/workbench/CMakeFiles/workbench_exe.dir/DependInfo.cmake" is newer than depender "/home/skella1/pargit/parquet/build/workbench/CMakeFiles/workbench_exe.dir/depend.internal".
Dependee "/home/skella1/pargit/parquet/build/workbench/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/skella1/pargit/parquet/build/workbench/CMakeFiles/workbench_exe.dir/depend.internal".
Scanning dependencies of target workbench_exe
make[2]: Leaving directory `/home/skella1/pargit/parquet/build'
make -f workbench/CMakeFiles/workbench_exe.dir/build.make workbench/CMakeFiles/workbench_exe.dir/build
make[2]: Entering directory `/home/skella1/pargit/parquet/build'
/home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -E cmake_progress_report /home/skella1/pargit/parquet/build/CMakeFiles 1
[ 50%] Building CXX object workbench/CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o
cd /home/skella1/pargit/parquet/build/workbench && /usr/local/compilers/gcc/4.9.0/bin/c++   -DDEBUG -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME=workbench_exe -DHPX_APPLICATION_STRING=\"workbench_exe\" -DHPX_PREFIX=\"/scratch/skella1/curver/install\" -D_DEBUG -g -I/usr/local/compilers/Intel/composer_xe_2013.5.192/mkl/include -I/home/skella1/pargit/parquet/workbench/workbench -I/work/skella1/curver/install/include -I/work/skella1/curver/install/include/hpx/external -I/work/skella1/boost_1_58_0 -I/work/skella1/include    -std=c++14 -o CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o -c /home/skella1/pargit/parquet/workbench/workbench/workbench/server/matrix.cpp
/home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -E cmake_progress_report /home/skella1/pargit/parquet/build/CMakeFiles 2
[100%] Building CXX object workbench/CMakeFiles/workbench_exe.dir/main.cpp.o
cd /home/skella1/pargit/parquet/build/workbench && /usr/local/compilers/gcc/4.9.0/bin/c++   -DDEBUG -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME=workbench_exe -DHPX_APPLICATION_STRING=\"workbench_exe\" -DHPX_PREFIX=\"/scratch/skella1/curver/install\" -D_DEBUG -g -I/usr/local/compilers/Intel/composer_xe_2013.5.192/mkl/include -I/home/skella1/pargit/parquet/workbench/workbench -I/work/skella1/curver/install/include -I/work/skella1/curver/install/include/hpx/external -I/work/skella1/boost_1_58_0 -I/work/skella1/include    -std=c++14 -o CMakeFiles/workbench_exe.dir/main.cpp.o -c /home/skella1/pargit/parquet/workbench/workbench/main.cpp
Linking CXX executable workbench
cd /home/skella1/pargit/parquet/build/workbench && /home/packages/cmake/2.8.12/INTEL-14.0.2/bin/cmake -E cmake_link_script CMakeFiles/workbench_exe.dir/link.txt --verbose=1
/usr/local/compilers/gcc/4.9.0/bin/c++   -g    CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o CMakeFiles/workbench_exe.dir/main.cpp.o  -o workbench  -L/usr/local/compilers/Intel/composer_xe_2013.5.192/mkl/lib/intel64 -rdynamic /scratch/skella1/curver/install/lib/libhpx_initd.a /scratch/skella1/curver/install/lib/libhpxd.so.0.9.12 /scratch/skella1/curver/install/lib/libhpxd.so.0.9.12 /scratch/skella1/curver/install/lib/libhpx_initd.a -ldl -lrt /work/skella1/boost_1_58_0/stage/lib/libboost_chrono-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_date_time-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_filesystem-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_program_options-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_regex-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_system-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_thread-mt-d.so -lpthread /work/skella1/boost_1_58_0/stage/lib/libboost_context-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_random-mt-d.so /work/skella1/boost_1_58_0/stage/lib/libboost_atomic-mt-d.so /work/skella1/lib/libjemalloc.so /work/skella1/lib/libhwloc.so -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lmpi_cxx -lmpi -lmpi_cxx -lmpi -Wl,-rpath,/scratch/skella1/curver/install/lib:/work/skella1/boost_1_58_0/stage/lib:/work/skella1/lib:/usr/local/compilers/Intel/composer_xe_2013.5.192/mkl/lib/intel64: 
CMakeFiles/workbench_exe.dir/workbench/server/matrix.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/curver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'
CMakeFiles/workbench_exe.dir/main.cpp.o: In function `(anonymous namespace)::check_hpx_version()':
/work/skella1/curver/install/include/hpx/config/version.hpp:95: undefined reference to `hpx::hpx_check_boost_version_105800'
collect2: error: ld returned 1 exit status
make[2]: *** [workbench/workbench] Error 1
make[2]: Leaving directory `/home/skella1/pargit/parquet/build'
make[1]: *** [workbench/CMakeFiles/workbench_exe.dir/all] Error 2
make[1]: Leaving directory `/home/skella1/pargit/parquet/build'
make: *** [all] Error 2

**Comment by quantomb** [comment] 2016-02-09 20:14
sorry I should have reported that looking at the above it does look like it is linking to the correct version of boost everywhere I see it.

**Comment by hkaiser** [comment] 2016-02-09 20:33
ok, so your application is built against the directory `/work/skella1/boost_1_58_0`. Now, please show us the same for when you're building HPX itself. Also, please make sure that the HPX version in `/scratch/skella1/curver/install/lib/` is the one you meant to link with.

**Comment by quantomb** [comment] 2016-02-09 20:43
Yes, that is definitely the directory I want.

As to HPX. I could include all the outuput from the hpx compilation though that would be a lot. Is this sufficient? It is a selection of the text with a relevant warning. It shows the stack trace which shows it is using boost but it is linking to a include directory.

-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   context
--   random
--   atomic

[  3%] Building CXX object src/CMakeFiles/hpx_init.dir/hpx_main.cpp.o
Building CXX object src/CMakeFiles/hpx_init.dir/hpx_user_main.cpp.o
Building CXX object src/CMakeFiles/hpx_init.dir/util/lightweight_test.cpp.o
Building CXX object src/CMakeFiles/hpx_init.dir/main.cpp.o
In file included from /work/skella1/include/boost/unordered/detail/equivalent.hpp:15:0,
                 from /work/skella1/include/boost/unordered/unordered_map.hpp:18,
                 from /work/skella1/include/boost/unordered_map.hpp:17,
                 from /work/skella1/curver/hpx/hpx/runtime/serialization/detail/polymorphic_intrusive_factory.hpp:20,
                 from /work/skella1/curver/hpx/hpx/util/detail/function_registration.hpp:13,
                 from /work/skella1/curver/hpx/hpx/util/detail/basic_function.hpp:15,
                 from /work/skella1/curver/hpx/hpx/util/function.hpp:13,
                 from /work/skella1/curver/hpx/hpx/hpx_fwd.hpp:45,
                 from /work/skella1/curver/hpx/hpx/hpx_init.hpp:13,
                 from /work/skella1/curver/hpx/src/hpx_user_main_argc_argv.cpp:6:
/work/skella1/include/boost/unordered/detail/table.hpp: In member function ‘void boost::unordered::detail::table<Types>::reserve(std::size_t)’:
/work/skella1/include/boost/unordered/detail/table.hpp:865:57: warning: implicit conversion from ‘float’ to ‘double’ to match other operand of binary expression [-Wdouble-promotion]
             std::ceil(static_cast<double>(num_elements) / mlf_)));

**Comment by hkaiser** [comment] 2016-02-09 20:47
> Yes, that is definitely the directory I want.

That's not what I asked, sorry if I was not sufficiently concise. I meant to ask whether the libraries located in that directory have been built against the same Boost libraries as you're building your application against.

The error you're seeing is caused by inconsistent Boost libraries used to compile HPX and your application. 

Could it be that the HPX libraries are stale?

**Comment by quantomb** [comment] 2016-02-09 20:55
I apologize but I am not sure what you mean by stale. Every time I rebuild hpx I clean the build and install directories so I am not building off old versions if that is what you mean. 

I understand the error but I do not know how to look up the boost version hpx is building against. In my program I use the command ldd and check that the dependencies point to the directories of hpx and boost that I expect. Is there a file I could run this or a similar command against to check hpx dependencies. I could even recompile hpx on supermic with verbose=1 but that will have tens of thousands of lines of output due to all the warnings that are generated.

Thank you for your patience with me in this regard

**Comment by hkaiser** [comment] 2016-02-09 20:59
`hello_world --hpx:version`  should give you the version HPX was built against.

**Comment by quantomb** [comment] 2016-02-10 14:10
ummm.... I done messed up something. 

[skella1@smic1 build]$ ./bin/hello_world --hpx:version
pure virtual method called
terminate called without an active exception
Aborted

I ran the program normally and this is what I got:
https://help.github.com/articles/about-gists/

Note it does say that the boost call is coming from /work/skella1/boost_1_58_0/  which is where the parquet program was linking. So going back to the question of building off most recent versions of hpx saying they are building off different versions of boost, I still do not understand.


sorry this took so long to get back to supermic issues

**Comment by zao** [comment] 2016-02-10 14:17
I assume you meant to link this gist?
https://gist.github.com/quantomb/5dc7d373499121df2abc

**Comment by quantomb** [comment] 2016-02-10 14:17
woops wrong link:
https://gist.github.com/quantomb/5dc7d373499121df2abc

**Comment by quantomb** [comment] 2016-02-11 14:45
When I run hello_world with gdb the output is in the above gist. It points to /lib64/libc.so.6

**Comment by hkaiser** [comment] 2016-02-11 17:30
Sure, that's what you have posted already. We need to find out is what string was passed to the function `boost::from_utf8`. It's the content of this string which causes the problems.

**Comment by sithhell** [comment] 2016-06-22 05:40
What's left to do here? Are the issues fixed?

**Comment by hkaiser** [comment] 2016-07-20 17:50
Let's assume this has been resolved. Please reopen if necessary.

**Closed by hkaiser** 2016-07-20 17:50 UTC
Labels: affecting: LSU, category: init, category: parcel transport, type: defect
