### ISSUE TITLE
HPX_ASSERT problem

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#2368] opened 2016-10-24 19:12 UTC
When running this modified intersim benchmark against these modified composable guard files, something strange happens. The HPX_ASSERT(false) on line 113 allows the program to continue running, bypassing the abort() on line 114. This happens for RelWithDebugInfo, but not Debug. The breakme() function is there to give gdb an easy target to attach to.

[HPX_ASSERT.zip](https://github.com/STEllAR-GROUP/hpx/files/548730/HPX_ASSERT.zip)

**Comment by stevenrbrandt** [comment] 2016-10-25 20:25
Except that the assert *does* do something, even though it's supposed to be disabled in that mode. Note above, the HPX_ASSERT(false) causes the code to bypass the abort() on the next line.

**Comment by hkaiser** [comment] 2016-11-08 20:39
@stevenrbrandt I can't reproduce your problem, sorry. Could you give a more precise description of how to reproduce it?

**Comment by hkaiser** [comment] 2017-10-12 18:25
I'll close this as being resolved. Please feel free to reopen if the problem persists.

**Closed by hkaiser** 2017-10-12 18:25 UTC
Labels: category: tests, type: defect
