### ISSUE TITLE
undefined reference to opal_hwloc191_hwloc_.....

### ISSUE THREAD

**Issue by timbiedert** [STEllAR-GROUP/hpx#2410] opened 2016-11-28 14:51 UTC
I'm trying to compile HPX on a new cluster I was just granted access to.

There is some hwloc-related issue:

```
CMakeFiles/hpx.dir/runtime/threads/policies/hwloc_topology.cpp.o: In function `hpx::threads::opal_hwloc191_hwloc_topology::get_thread_affinity_mask_from_lva(unsigned long, hpx::error_code&) const':
hwloc_topology.cpp:(.text+0x1225): undefined reference to `opal_hwloc191_hwloc_bitmap_alloc'
hwloc_topology.cpp:(.text+0x1261): undefined reference to `opal_hwloc191_hwloc_get_area_membind_nodeset'
hwloc_topology.cpp:(.text+0x126f): undefined reference to `opal_hwloc191_hwloc_bitmap_alloc'
hwloc_topology.cpp:(.text+0x1283): undefined reference to `opal_hwloc191_hwloc_get_type_depth'
hwloc_topology.cpp:(.text+0x1297): undefined reference to `opal_hwloc191_hwloc_bitmap_zero'
hwloc_topology.cpp:(.text+0x12bb): undefined reference to `opal_hwloc191_hwloc_bitmap_isset'
hwloc_topology.cpp:(.text+0x12d1): undefined reference to `opal_hwloc191_hwloc_bitmap_or'
hwloc_topology.cpp:(.text+0x12e3): undefined reference to `opal_hwloc191_hwloc_get_obj_by_depth'
hwloc_topology.cpp:(.text+0x12fe): undefined reference to `opal_hwloc191_hwloc_bitmap_free'
hwloc_topology.cpp:(.text+0x132a): undefined reference to `opal_hwloc191_hwloc_get_type_depth'
hwloc_topology.cpp:(.text+0x135a): undefined reference to `opal_hwloc191_hwloc_get_obj_by_depth'
hwloc_topology.cpp:(.text+0x136a): undefined reference to `opal_hwloc191_hwloc_bitmap_isset'
hwloc_topology.cpp:(.text+0x1399): undefined reference to `opal_hwloc191_hwloc_bitmap_free'
hwloc_topology.cpp:(.text+0x13c4): undefined reference to `opal_hwloc191_hwloc_bitmap_iszero'
hwloc_topology.cpp:(.text+0x13d0): undefined reference to `opal_hwloc191_hwloc_bitmap_zero'
hwloc_topology.cpp:(.text+0x13eb): undefined reference to `opal_hwloc191_hwloc_bitmap_free'
hwloc_topology.cpp:(.text+0x13fc): undefined reference to `opal_hwloc191_hwloc_bitmap_fill'
hwloc_topology.cpp:(.text+0x1433): undefined reference to `opal_hwloc191_hwloc_get_type_depth'
hwloc_topology.cpp:(.text+0x1449): undefined reference to `opal_hwloc191_hwloc_get_depth_type'
hwloc_topology.cpp:(.text+0x1455): undefined reference to `opal_hwloc191_hwloc_compare_types'
```
(and lots of similar errors)

What does this mean?   

Here's my Cmake command (using current master branch of hpx):
```
cmake -DCMAKE_INSTALL_PREFIX=$HPX_DIR \
      -DHPX_WITH_COMPILER_WARNINGS=OFF \
      -DHPX_WITH_EXAMPLES=OFF \
      -DHPX_WITH_TESTS=OFF \
      -DHPX_WITH_FULL_RPATH=ON \
      -DHPX_WITH_PARCELPORT_MPI=ON \
      -DHPX_WITH_PARCELPORT_TCP=OFF \
      -DHPX_WITH_HWLOC=ON \
      -DHWLOC_INCLUDE_DIR=/home/tb582202/local/include \
      -DHWLOC_LIBRARY=/home/tb582202/local/lib/libhwloc.so \
      -DHPX_WITH_MALLOC=tcmalloc \
```

I did compile the newest hwloc 1.11.5 myself because on the system only 1.7 was installed; which produced the same error, however.

System:
- CentOS 7.2
- GCC 6.2.0
- CMake 3.6.0
- Boost 1.60̇.0
- hwloc 1.11.5
- OpenMPI 1.10.4

**Comment by hkaiser** [comment] 2016-11-28 16:29
Apparently it's looking for symbols for HWLOC V1.9.1. Could you verify the linker is finding the correct HWLOC binaries?

**Comment by zao** [comment] 2016-11-28 17:53
Surely it's the include search path (order) that's bogus if the objects contain references to an older `hwloc`?

My guess is at something sneaking in `/usr/include` (or similar) before `HWLOC_INCLUDE_DIR`, if at all used.

**Comment by pagrubel** [comment] 2016-11-28 18:18
Try -DHWLOC_ROOT
On Nov 28, 2016, at 10:53 AM, Lars Viklund <notifications@github.com<mailto:notifications@github.com>> wrote:


Surely it's the include search path (order) that's bogus if the objects contain references to an older hwloc?

My guess is at something sneaking in /usr/include (or similar) before HWLOC_INCLUDE_DIR, if at all used.

**Comment by timbiedert** [comment] 2016-11-29 14:07
Setting -DHWLOC_ROOT did not work.

An exemplary make command:
```
[ 83%] Building CXX object src/CMakeFiles/hpx.dir/compute/host/numa_domains.cpp.o
cd /tmp/hpx-build/hpx/build/src && /usr/local_rwth/sw/gcc/6.2.0/bin/g++   -DBOOST_DISABLE_ASSERTS -DHPX_COMPONENT_NAME=hpx -DHPX_COROUTINE_EXPORTS -DHPX_DISABLE_ASSERTS -DHPX_ENABLE_ASSERT_HANDLER -DHPX_EXPORTS -D_GNU_SOURCE -Dhpx_EXPORTS -I/tmp/hpx-build/hpx -I/tmp/hpx-build/hpx/build -isystem /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/include -I/home/tb582202/local/include -I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include -I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/event/libevent2021/libevent -I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/event/libevent2021/libevent/include -I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include -I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi  -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Werror=uninitialized -Wno-unused-local-typedefs -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/hpx.dir/compute/host/numa_domains.cpp.o -c /tmp/hpx-build/hpx/src/compute/host/numa_domains.cpp
```

Note that `-I/home/tb582202/local/include` comes before `-I/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include` (which seems to be added automatically as part of OpenMPI)


And here's the linker command:
```
cd /tmp/hpx-build/hpx/build/src && /rwthfs/rz/SW/UTIL.common/cmake/3.6.0/bin/cmake -E cmake_link_script CMakeFiles/hpx.dir/link.txt --verbose=1
/usr/local_rwth/sw/gcc/6.2.0/bin/g++  -fPIC  -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Werror=uninitialized -Wno-unused-local-typedefs -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden -O3 -DNDEBUG  -Wl,-z,defs -fvisibility=hidden -shared -Wl,-soname,libhpx.so.1 -o ../lib/libhpx.so.1.0.0 CMakeFiles/hpx.dir/error_code.cpp.o CMakeFiles/hpx.dir/exception.cpp.o CMakeFiles/hpx.dir/exception_list.cpp.o CMakeFiles/hpx.dir/hpx_init.cpp.o CMakeFiles/hpx.dir/runtime.cpp.o CMakeFiles/hpx.dir/runtime_impl.cpp.o CMakeFiles/hpx.dir/state.cpp.o CMakeFiles/hpx.dir/throw_exception.cpp.o CMakeFiles/hpx.dir/version.cpp.o CMakeFiles/hpx.dir/pre_main.cpp.o CMakeFiles/hpx.dir/runtime/actions/continuation.cpp.o CMakeFiles/hpx.dir/runtime/actions/detail/action_factory.cpp.o CMakeFiles/hpx.dir/runtime/actions/detail/invocation_count_registry.cpp.o CMakeFiles/hpx.dir/runtime/agas/addressing_service.cpp.o CMakeFiles/hpx.dir/runtime/agas/big_boot_barrier.cpp.o CMakeFiles/hpx.dir/runtime/agas/component_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/detail/bootstrap_component_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/detail/bootstrap_locality_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/detail/hosted_component_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/detail/hosted_locality_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/interface.cpp.o CMakeFiles/hpx.dir/runtime/agas/locality_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/primary_namespace.cpp.o CMakeFiles/hpx.dir/runtime/agas/server/component_namespace_server.cpp.o CMakeFiles/hpx.dir/runtime/agas/server/locality_namespace_server.cpp.o CMakeFiles/hpx.dir/runtime/agas/server/primary_namespace_server.cpp.o CMakeFiles/hpx.dir/runtime/agas/server/route.cpp.o CMakeFiles/hpx.dir/runtime/agas/server/symbol_namespace_server.cpp.o CMakeFiles/hpx.dir/runtime/agas/symbol_namespace.cpp.o CMakeFiles/hpx.dir/runtime/applier/applier.cpp.o CMakeFiles/hpx.dir/runtime/applier/bind_naming_wrappers.cpp.o CMakeFiles/hpx.dir/runtime/components/component_type.cpp.o CMakeFiles/hpx.dir/runtime/components/console_error_sink.cpp.o CMakeFiles/hpx.dir/runtime/components/console_logging.cpp.o CMakeFiles/hpx.dir/runtime/components/memory.cpp.o CMakeFiles/hpx.dir/runtime/components/runtime_support.cpp.o CMakeFiles/hpx.dir/runtime/components/server/console_error_sink_server.cpp.o CMakeFiles/hpx.dir/runtime/components/server/console_error_sink_singleton.cpp.o CMakeFiles/hpx.dir/runtime/components/server/console_logging_server.cpp.o CMakeFiles/hpx.dir/runtime/components/server/destroy_component.cpp.o CMakeFiles/hpx.dir/runtime/components/server/memory_block.cpp.o CMakeFiles/hpx.dir/runtime/components/server/runtime_support_server.cpp.o CMakeFiles/hpx.dir/runtime/components/stubs/memory_block_stubs.cpp.o CMakeFiles/hpx.dir/runtime/components/stubs/memory_stub.cpp.o CMakeFiles/hpx.dir/runtime/components/stubs/runtime_support_stubs.cpp.o CMakeFiles/hpx.dir/runtime/get_locality_name.cpp.o CMakeFiles/hpx.dir/runtime/launch_policy.cpp.o CMakeFiles/hpx.dir/runtime/naming/address.cpp.o CMakeFiles/hpx.dir/runtime/naming/name.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/detail/parcel_await.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/detail/parcel_route_handler.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/detail/per_action_data_counter.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/detail/per_action_data_counter_registry.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/locality.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/parcel.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/parcelhandler.cpp.o CMakeFiles/hpx.dir/runtime/parcelset/parcelport.cpp.o CMakeFiles/hpx.dir/runtime/serialization/detail/polymorphic_id_factory.cpp.o CMakeFiles/hpx.dir/runtime/serialization/detail/polymorphic_intrusive_factory.cpp.o CMakeFiles/hpx.dir/runtime/serialization/detail/polymorphic_nonintrusive_factory.cpp.o CMakeFiles/hpx.dir/runtime/serialization/output_archive.cpp.o CMakeFiles/hpx.dir/runtime/set_parcel_write_handler.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/detail/context_base.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/detail/context_generic_context.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/detail/coroutine_impl.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/detail/coroutine_self.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/detail/tss.cpp.o CMakeFiles/hpx.dir/runtime/threads/coroutines/swapcontext.cpp.o CMakeFiles/hpx.dir/runtime/threads/detail/thread_num_tss.cpp.o CMakeFiles/hpx.dir/runtime/threads/detail/thread_pool.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/current_executor.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/default_executor.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/service_executor.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/this_thread_executors.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/thread_pool_attached_executors.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/thread_pool_executors.cpp.o CMakeFiles/hpx.dir/runtime/threads/executors/thread_pool_os_executors.cpp.o CMakeFiles/hpx.dir/runtime/threads/policies/affinity_data.cpp.o CMakeFiles/hpx.dir/runtime/threads/policies/hwloc_topology.cpp.o CMakeFiles/hpx.dir/runtime/threads/policies/parse_affinity_options.cpp.o CMakeFiles/hpx.dir/runtime/threads/resource_manager.cpp.o CMakeFiles/hpx.dir/runtime/threads/scheduler_specific_ptr.cpp.o CMakeFiles/hpx.dir/runtime/threads/thread.cpp.o CMakeFiles/hpx.dir/runtime/threads/thread_data.cpp.o CMakeFiles/hpx.dir/runtime/threads/thread_executor.cpp.o CMakeFiles/hpx.dir/runtime/threads/thread_helpers.cpp.o CMakeFiles/hpx.dir/runtime/threads/threadmanager.cpp.o CMakeFiles/hpx.dir/runtime/threads/threadmanager_base.cpp.o CMakeFiles/hpx.dir/runtime/threads/topology.cpp.o CMakeFiles/hpx.dir/runtime/trigger_lco.cpp.o CMakeFiles/hpx.dir/performance_counters/counter_creators.cpp.o CMakeFiles/hpx.dir/performance_counters/counters.cpp.o CMakeFiles/hpx.dir/performance_counters/manage_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/manage_counter_type.cpp.o CMakeFiles/hpx.dir/performance_counters/performance_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/registry.cpp.o CMakeFiles/hpx.dir/performance_counters/server/action_invocation_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/arithmetics_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/component_instance_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/elapsed_time_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/per_action_data_counters.cpp.o CMakeFiles/hpx.dir/performance_counters/server/raw_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/raw_values_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/server/statistics_counter.cpp.o CMakeFiles/hpx.dir/performance_counters/stubs/performance_counter_stub.cpp.o CMakeFiles/hpx.dir/util/activate_counters.cpp.o CMakeFiles/hpx.dir/util/asio_util.cpp.o CMakeFiles/hpx.dir/util/backtrace/backtrace.cpp.o CMakeFiles/hpx.dir/util/batch_environment.cpp.o CMakeFiles/hpx.dir/util/batch_environments/alps_environment.cpp.o CMakeFiles/hpx.dir/util/batch_environments/pbs_environment.cpp.o CMakeFiles/hpx.dir/util/batch_environments/slurm_environment.cpp.o CMakeFiles/hpx.dir/util/command_line_handling.cpp.o CMakeFiles/hpx.dir/util/debug/thread_stacktrace.cpp.o CMakeFiles/hpx.dir/util/find_prefix.cpp.o CMakeFiles/hpx.dir/util/generate_unique_ids.cpp.o CMakeFiles/hpx.dir/util/ini.cpp.o CMakeFiles/hpx.dir/util/init_ini_data.cpp.o CMakeFiles/hpx.dir/util/integer/int128.cpp.o CMakeFiles/hpx.dir/util/integer/uint128.cpp.o CMakeFiles/hpx.dir/util/interval_timer.cpp.o CMakeFiles/hpx.dir/util/io_service_pool.cpp.o CMakeFiles/hpx.dir/util/itt_notify.cpp.o CMakeFiles/hpx.dir/util/logging.cpp.o CMakeFiles/hpx.dir/util/manage_config.cpp.o CMakeFiles/hpx.dir/util/map_hostnames.cpp.o CMakeFiles/hpx.dir/util/parse_command_line.cpp.o CMakeFiles/hpx.dir/util/pool_timer.cpp.o CMakeFiles/hpx.dir/util/query_counters.cpp.o CMakeFiles/hpx.dir/util/register_locks.cpp.o CMakeFiles/hpx.dir/util/register_locks_globally.cpp.o CMakeFiles/hpx.dir/util/runtime_configuration.cpp.o CMakeFiles/hpx.dir/util/security/root_certificate_authority.cpp.o CMakeFiles/hpx.dir/util/security/subordinate_certificate_authority.cpp.o CMakeFiles/hpx.dir/util/sed_transform.cpp.o CMakeFiles/hpx.dir/util/serialize_exception.cpp.o CMakeFiles/hpx.dir/util/set_thread_name.cpp.o CMakeFiles/hpx.dir/util/static_reinit.cpp.o CMakeFiles/hpx.dir/util/thread_aware_timer.cpp.o CMakeFiles/hpx.dir/util/thread_description.cpp.o CMakeFiles/hpx.dir/util/thread_mapper.cpp.o CMakeFiles/hpx.dir/lcos/barrier.cpp.o CMakeFiles/hpx.dir/lcos/base_lco.cpp.o CMakeFiles/hpx.dir/lcos/base_lco_with_value.cpp.o CMakeFiles/hpx.dir/lcos/base_lco_with_value_1.cpp.o CMakeFiles/hpx.dir/lcos/base_lco_with_value_2.cpp.o CMakeFiles/hpx.dir/lcos/base_lco_with_value_3.cpp.o CMakeFiles/hpx.dir/lcos/detail/barrier_node.cpp.o CMakeFiles/hpx.dir/lcos/detail/future_data.cpp.o CMakeFiles/hpx.dir/lcos/latch.cpp.o CMakeFiles/hpx.dir/lcos/local/composable_guard.cpp.o CMakeFiles/hpx.dir/lcos/local/detail/condition_variable.cpp.o CMakeFiles/hpx.dir/lcos/local/local_barrier.cpp.o CMakeFiles/hpx.dir/lcos/local/mutex.cpp.o CMakeFiles/hpx.dir/lcos/promise.cpp.o CMakeFiles/hpx.dir/compute/cuda/cuda_target.cpp.o CMakeFiles/hpx.dir/compute/cuda/get_cuda_targets.cpp.o CMakeFiles/hpx.dir/compute/host/get_host_targets.cpp.o CMakeFiles/hpx.dir/compute/host/host_target.cpp.o CMakeFiles/hpx.dir/compute/host/numa_domains.cpp.o CMakeFiles/hpx.dir/__/plugins/parcelport/mpi/mpi_environment.cpp.o CMakeFiles/hpx.dir/__/plugins/parcelport/mpi/parcelport_mpi.cpp.o  -L/tmp/hpx-build/hpx/build/lib  -L/usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib -ldl -lrt /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_chrono.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_date_time.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_filesystem.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_program_options.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_regex.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_system.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_thread.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_atomic.so -lpthread /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_context.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_random.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_system.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_atomic.so /home/tb582202/local/lib/libtcmalloc_minimal.so /home/tb582202/local/lib/libhwloc.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi_cxx.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi_cxx.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_thread.so -lpthread /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_context.so /usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib/libboost_random.so /home/tb582202/local/lib/libtcmalloc_minimal.so /home/tb582202/local/lib/libhwloc.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi_cxx.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi_cxx.so /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libmpi.so -Wl,-rpath,/tmp/hpx-build/hpx/build/lib:/usr/local_rwth/sw/boost/1_60_0/gcc-openmpi/lib:/home/tb582202/local/lib:/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib: 
````
Only my manual `/home/tb582202/local/lib/libhwloc.so` is present.

Unfortunately, there is no compiled hwloc191 library within the OpenMPI version used.

**Comment by hkaiser** [comment] 2016-11-29 14:21
As you said, you are trying to compile and link against HWLOC 1.11.1 but the compiler command line refers to 

    /opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include 

If there is no HWLOC 1.9.1 binary available for the linker to find then this explains the missing symbols you reported. 

The only option I see is to make the missing HWLOC 1.9.1 binary available to the linker.

**Comment by timbiedert** [comment] 2016-11-29 14:24
I'm rather surprised it does not find the HWLOC 1.11.1 headers I installed to `/home/tb582202/local/include`,  but prefers the 1.9.1 headers (of which the include path is specified AFTER).

**Comment by hkaiser** [comment] 2016-11-29 14:28
@timbiedert I think the missing symbols come from references inside your openmpi implementation. HPX does not modify the exported HWLOC names (does not prepend `opal_hwloc191_` to the symbols).

**Comment by timbiedert** [comment] 2016-11-29 15:10
Solved it using this setup:
```
cmake -DCMAKE_INSTALL_PREFIX=$HPX_DIR \
      -DHPX_WITH_COMPILER_WARNINGS=OFF \
      -DHPX_WITH_EXAMPLES=OFF \
      -DHPX_WITH_TESTS=OFF \
      -DHPX_WITH_FULL_RPATH=ON \
      -DHPX_WITH_PARCELPORT_MPI=ON \
      -DHPX_WITH_PARCELPORT_TCP=OFF \
      -DHPX_WITH_HWLOC=ON \
      -DHWLOC_LIBRARY=/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/lib/libopen-pal.so \
      -DHPX_WITH_MALLOC=tcmalloc \
      ..
```

Using `nm -D` I found the missing `opal_hwloc191_hwloc_*` symbols in libopen-pal.so.

I'm still confused why the compiler actually chose the opal version, since my manual version was first in the include paths.

Without hwloc it also would have compiled. However, I was wondering, what would be the performance impact?

Thank you!

**Comment by hkaiser** [comment] 2016-11-29 16:07
Without HWLOC HPX is not able to define affinities for the kernel threads which may impact your performance significantly.

I'll go ahead and close this now. Feel free to reopen if necessary.

**Closed by hkaiser** 2016-11-29 16:07 UTC
Labels: category: CMake, type: defect

**Comment by mcopik** [comment] 2017-02-17 23:40
@timbiedert I've been able to repeat your issue. The problem is even more serious because examples can not be built. I've identified the root of the problem and [according to OpenMPI developers](https://github.com/open-mpi/hwloc/issues/229) the presence of `/opt/MPI/openmpi-1.10.4/linux/gcc_6.2.0/include/openmpi/opal/mca/hwloc/hwloc191/hwloc/include` in OpenMPI compilation flags indicates that it has not been installed properly, maybe due to a mistake or maybe it is a bug in OpenMPI. Devs asked to me contact cluster maintainers and ask them how they have built and installed OpenMPI.

Which cluster are you using? I have the same problem at RWTH cluster and I asked the local IT guys to provide the configure command they have used to build OpenMPI. If you have been using another HPC cluster then you can help us and send the same question to your IT department.

**Comment by timbiedert** [comment] 2017-02-18 12:14
@mcopik Thanks for your reply. I was also working on the RWTH cluster :-)
