### ISSUE TITLE
It seems that the tcp parcelport is running, and the MPI parcelport is ignored

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5701] opened 2021-12-09 22:28 UTC
## Expected Behavior

MPI parcelport should run

## Actual Behavior

tcp parcleport is running. At least the error message shows that the tcp parcelport is active

```
{os-thread}: locality#27/parcel-thread-tcp#0
{thread-description}: <unknown>
{state}: invalid (value out of bounds)
{auxinfo}: 
{file}: /pscratch/sd/d/diehlpk/OctoTigerBuildChain/src/hpx/libs/core/thread_pools/include/hpx/thread_pools/scheduled_thread_pool_impl.hpp
{line}: 605
{function}: thread_pool<Scheduler>::create_thread
{what}: invalid state: thread pool is not running: HPX(invalid_status)
```
Maybe that is some false positive, but it is rather confusing. 

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Compile with parcel port mpi = ON and run Octo-Tiger.

## Specifications

... Please describe your environment

  - HPX Version: 1.7.1
  - Platform (compiler, OS): gcc 9.30, cray-mpich 8, CUDA 11.4

**Comment by hkaiser** [comment] 2021-12-09 23:04
This is a duplicate of #5700, closing

**Closed by hkaiser** 2021-12-09 23:04 UTC
Labels: tag: duplicate
