### ISSUE TITLE
hpxcxx's shebang doesn't specify the python version

### ISSUE THREAD

**Issue by JPenuchot** [STEllAR-GROUP/hpx#3743] opened 2019-03-13 19:30 UTC
Calling `hpxcxx` on my configuration (Arch Linux, up-to-date as of the day I'm posting this) doesn't work unless I manually replace the shebang to target `python2` instead of the default `python` executable, which can be Python 3 in some cases (like mine, which is what Arch defaults to). The script isn't compatible with Python 3 so that results into the following error :

```
  File "/usr/local/bin/hpxcxx", line 142
    print pkg+'='+pkgconf
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(pkg+'='+pkgconf)?
```

This is what I replaced the current shebang with to make it work :

```bash
#! /usr/bin/env python2
```

The latter works on my config, but I would suggest to test it on other distros obviously to avoid breaking existing configurations.

**Comment by hkaiser** [comment] 2019-03-14 01:38
Is this a duplicate of #3718?

**Comment by JPenuchot** [comment] 2019-03-14 03:23
Oh yes it is !

**Closed** 2019-03-14 12:58 UTC
Labels: category: tools, tag: duplicate, type: defect, type: feature request
