### ISSUE TITLE
Build error for hpx w/ Apex on Summit

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/hpx#4679] opened 2020-05-28 01:45 UTC
## Expected Behavior
Build passes

## Actual Behavior

```
[ 43%] Building CXX object libs/performance_counters/CMakeFiles/hpx_performance_counters.dir/src/config_entries.cpp.o
In file included from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/../../hpx/runtime/components/make_client.hpp:10,
                 from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/../../hpx/runtime/basename_registration_fwd.hpp:15,
                 from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/../../hpx/runtime_fwd.hpp:28,
                 from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/async/include/hpx/async/applier/apply_helper.hpp:15,
                 from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/async/include/hpx/async/applier/apply.hpp:12,
                 from /gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/src/counters.cpp:10:
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/futures/include/hpx/futures/future.hpp: In instantiation of 'static decltype(auto) hpx::lcos::detail::future_then_dispatch<Future, FD, Enable>::call(Future&&, T0&&, F&&) [with T0 = const hpx::detail::sync_policy&; F = hpx::util::detail::bound_front<hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>), hpx::util::pack_c<long unsigned int, 0>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >; Future = hpx::lcos::future<hpx::naming::id_type>; FD = hpx::detail::sync_policy; Enable = void]':
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/futures/include/hpx/futures/future.hpp:649:74:   required by substitution of 'template<class F, class T0> static decltype (hpx::lcos::detail::future_base<hpx::lcos::future<hpx::naming::id_type>, hpx::naming::id_type>::future_then_dispatch<typename std::decay<_Arg>::type>::call(std::move(fut), forward<T0>(t0), forward<F>(f))) hpx::lcos::detail::future_base<hpx::lcos::future<hpx::naming::id_type>, hpx::naming::id_type>::then<F, T0>(hpx::lcos::future<hpx::naming::id_type>&&, T0&&, F&&, hpx::error_code&) [with F = hpx::util::detail::bound_front<hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>), hpx::util::pack_c<long unsigned int, 0>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >; T0 = const hpx::detail::sync_policy&]'
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/futures/include/hpx/futures/future.hpp:971:35:   required from 'decltype(auto) hpx::lcos::future<R>::then(T0&&, F&&, hpx::error_code&) [with T0 = const hpx::detail::sync_policy&; F = hpx::util::detail::bound_front<hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>), hpx::util::pack_c<long unsigned int, 0>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >; R = hpx::naming::id_type]'
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/src/counters.cpp:1160:74:   required from here
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/futures/include/hpx/futures/future.hpp:426:42: error: static assertion failed: Cannot use the                     dummy implementation of future_then_dispatch, please use                     one of the template specialization.
             static_assert(sizeof(Future) == 0, "Cannot use the \
                           ~~~~~~~~~~~~~~~^~~~
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/src/counters.cpp: In function 'hpx::lcos::future<hpx::naming::id_type> hpx::performance_counters::get_counter_async(const hpx::performance_counters::counter_info&, hpx::error_code&)':
/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_mpi_async/hpx/libs/performance_counters/src/counters.cpp:1158:30: error: could not convert 'f.hpx::lcos::future<hpx::naming::id_type>::then<const hpx::detail::sync_policy&, hpx::util::detail::bound_front<hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>), hpx::util::pack_c<long unsigned int, 0>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(hpx::launch::sync, hpx::util::bind_front(F&&, Ts&& ...) [with F = hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>); Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; typename hpx::util::make_index_pack<sizeof... (Ts)>::type = hpx::util::pack_c<long unsigned int, 0>; typename std::decay<_Tp>::type = hpx::naming::id_type (*)(const std::__cxx11::basic_string<char>&, hpx::lcos::future<hpx::naming::id_type>)](complemented_info.hpx::performance_counters::counter_info::fullname_), hpx::throws)' from 'void' to 'hpx::lcos::future<hpx::naming::id_type>'
                 return f.then(hpx::launch::sync,
                        ~~~~~~^~~~~~~~~~~~~~~~~~~
                     hpx::util::bind_front(
                     ~~~~~~~~~~~~~~~~~~~~~~
                         &register_with_agas, complemented_info.fullname_));
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [libs/performance_counters/CMakeFiles/hpx_performance_counters.dir/src/counters.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libs/performance_counters/CMakeFiles/hpx_performance_counters.dir/all] Error 2
make: *** [all] Error 2

```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

## Specifications

... Please describe your environment

  - HPX Version: latest master w/ commit: 7a07598fbfcb4a871d16d568e31dbd211dc74d4f
  - Platform (compiler, OS): Power machine, gcc 8.1.1
  - CMake: -DHPX_WITH_APEX=TRUE -DHPX_WITH_APEX_TAG=v2.1.9

**Comment by msimberg** [comment] 2020-05-28 07:48
I think the fix is the same as for #4675. I'll have a PR up soon for you to try.

**Comment by msimberg** [comment] 2020-06-02 08:03
@weilewei #4681 should have fixed this issue. Would you mind checking and closing if the problem is solved?

**Comment by weilewei** [comment] 2020-06-02 20:29
Actually, I got similar error on my desktop with latest hpx master as of today: https://gist.github.com/weilewei/a81e2761351bdae7317ac12ec3a5906c let me build it on Summit now.

**Comment by weilewei** [comment] 2020-06-02 20:46
I can confirm that similar issues happened on Summit with latest hpx master.

**Comment by msimberg** [comment] 2020-06-03 07:38
Thanks @weilewei for checking. I'll try to fix this for you.

**Closed** 2020-06-08 09:14 UTC
Labels: category: APEX, category: executors, type: defect
