### ISSUE TITLE
MPI Backend Trouble 

### ISSUE THREAD

**Issue by KilianWerner** [STEllAR-GROUP/hpx#4297] opened 2020-01-08 15:30 UTC
## Expected Behavior

Given a system with a single clean OpenMPI installation an mpi hello world program finds a given Comm_size and Comm_rank. (for example 0/2 and 1/2 for mpirun -np 2)

We now compile HPX with MPI_Parcelport=ON with this same OpenMPI installation.
Then an HPX application run with mpirun -np 2 should find those same ranks and sizes as hpx::get_locality_id() and hpx::find_all_localities().size().

## Actual Behavior

All hpx::find_all_localities() method calls return vectors with size 1, no communication between localities is possile.

## Steps to Reproduce the Problem
A docker container containing a minimal HPX hello world setup is available at
docker://kilianwerner/hpxminimal

The used docker folder including all source and configuration is available at
https://github.com/KilianWerner/HPXMinimalDocker

Running on any host with singularity and openmpi version 4.0.1 the following commands 

sudo singularity build min.sif docker://kilianwerner/hpxminimal
mpirun -np 2 singularity exec min.sif /opt/mpitest

result in output:
Hello, I am rank 1/2Hello, I am rank 0/2

However
mpirun -np 2 singularity exec min.sif /home/myUser/MinimalExample/build/hpxmin

results in output:

Localities: 1Threads: 4Localities: 1Threads: 4

## Specifications
  - HPX Version: 1.3.0
  - Platform (compiler, OS): ubuntu:disco
  - OpenMPI Version: 4.0.1

## Comments:
Our work group often stumbles into the problem that hpx::find_all_localities().size() = 1 regardless of the mpi backend situation. Most of the times this is "solved" by changing to older versions of hpx, openmpi, use other mpi implementations (like intel mpi) and just generally swap things around until hpx localities find each other. 

As we are now trying to get a robust common solution working in a docker container, we face the problem again and need hpx to behave consistent with raw mpi applications in a robust manner.

**Comment by hkaiser** [comment] 2020-01-08 15:39
@KilianWerner could you please try the same when using https://github.com/STEllAR-GROUP/hpx/tree/stable (i.e. last known good master)? We're about to release V1.4 and it would be nice to know if this was fixed in the mean time.

**Comment by biddisco** [comment] 2020-01-08 15:50
I wonder if this might be due to the use of OpenMPI. I believe we all use MPICH or cray MPI etc and nobody tests OpenMPI. Our MPI environment check might not be looking for the right env vars or something of that kind.

Do any of the core developers use OpenMPI and can they run a simple check?
I will build openmpi and test myself if nobody else volunteers.

**Comment by KilianWerner** [comment] 2020-01-08 15:55
Replacing git clone https://github.com/STEllAR-GROUP/hpx.git --branch master --single-branch
with git clone https://github.com/STEllAR-GROUP/hpx.git --branch stable --single-branch

results in the following build error for now:
'filesystem' is not a namespace-name  (see file attached)

[error.txt](https://github.com/STEllAR-GROUP/hpx/files/4036094/error.txt)

**Comment by biddisco** [comment] 2020-01-08 15:59
That's a C++17 thing. It will go away if you use c++14. I've had the same error on several builds but I didn't check to see what was wrong. I was mixing an app using c++17 with an hpx build using c++14 - if hpx itself is causing trouble, we should investigate.

**Comment by KilianWerner** [comment] 2020-01-08 16:09
Thank you. The docker container has been updated to pull --branch stable and consitently use c++ 17 (the hpx application was compiled with c++ 14). 

This however results in the hpx hello world application giving a bad alloc:
mpirun -np 2 singularity exec min.sif /home/myUser/MinimalExample/build/hpxmin
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node KW-PC exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by biddisco** [comment] 2020-01-08 16:18
```
mkdir hpx-test
cd hpx-test/
cmake -DMPI_CXX_COMPILER=$HOME/apps/openmpi/4.0.2/bin/mpicxx \
 -DHPX_WITH_PARCELPORT_MPI=ON \
 -DHPX_WITH_MALLOC=SYSTEM \
 -DHWLOC_ROOT=$HOME/apps/hwloc/2.1.0/ \
 ~/src/hpx-scratch/
make -j8 hello_world_distributed
```
Results
```
~/apps/openmpi/4.0.2/bin/mpiexec -n 2 bin/hello_world_distributed 
hello world from OS-thread 1 on locality 1
hello world from OS-thread 2 on locality 1
hello world from OS-thread 0 on locality 0
hello world from OS-thread 0 on locality 1
hello world from OS-thread 3 on locality 0
hello world from OS-thread 1 on locality 0
hello world from OS-thread 2 on locality 0
hello world from OS-thread 3 on locality 1
```

**Comment by msimberg** [comment] 2020-01-08 16:25
These may be unrelated, but is there a good reason for you to set `HPX_IGNORE_COMPILER_COMPATIBILITY` to `ON`? `mpicxx` should identify itself as the actual host compiler. I'd also try setting the build type expclitly for both the example project and HPX to `Debug` to potentially get more useful errors messages (that `bad_alloc` looks like it's happening before the runtime has been started). Last, does the same happen if you only run on one node? Or without `mpirun`?

**Comment by KilianWerner** [comment] 2020-01-08 16:33
@biddisco I got into a shell in the provided docker container and tried your style of compilation:

sudo docker run -it kilianwerner/hpxminimal /bin/bash
myUser@80670e84fd40:~/hpx-test$ cmake -DMPI_CXX_COMPILER=/usr/bin/mpicxx -DHPX_WITH_PARCELPORT_MPI=ON /hpx/hpx/


Then:
mpiexec -n 2 bin/hello_world_distributed

Still results in bad alloc.

**Comment by KilianWerner** [comment] 2020-01-08 16:35
@msimberg HPX_IGNORE_COMPILER_COMPATIBILITY has been removed and build types have been changed to Debug in the git repository, the new container is currently building... You can play around with the container in a shell if you have installed docker with 'sudo docker run -it kilianwerner/hpxminimal /bin/bash'

**Comment by KilianWerner** [comment] 2020-01-08 16:44
@msimberg Only running on one node and without mpirun also resulted in Localities: 1Threads: 4... which if of course correct in that setting. (since the use of stable and c++17 this also results in bad alloc though)

**Comment by biddisco** [comment] 2020-01-08 16:45
I'm afraid that I know nothing about docker or containers, so I don't think I can help any further.

**Comment by KilianWerner** [comment] 2020-01-08 16:47
docker is a kind of virtualization technique for reproducability, basically after installing docker the command sudo docker run -it kilianwerner/hpxminimal /bin/bash will put you on a virtual ubuntu (like ssh) containing my minimal example

**Comment by KilianWerner** [comment] 2020-01-08 17:16
A similar error is reproducable on your docker container: https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/contributing/docker_image.html

On this docker container I compile openmpi 4.0.1 like above.

Then I compile hpx like this:

mkdir hpx
cd hpx
git clone https://github.com/STEllAR-GROUP/hpx.git --branch stable --single-branch
mkdir build-hpx && cd build-hpx
cmake ../hpx -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCELPORT_TCP=OFF -DCMAKE_BUILD_TYPE=DEBUG
make -j 8
make install

Converting to .sif and running mpirun -np 2 singularity exec hpx_official_docker.sif /hpx/build-hpx/bin/hello_world_distributed.

Results in the appended error.
[error2.txt](https://github.com/STEllAR-GROUP/hpx/files/4036452/error2.txt)

**Comment by msimberg** [comment] 2020-01-13 08:22
I'm also a bit at a loss. I've never used singularity so can't help you there. But it would be good to establish if this is a problem with HPX, OpenMPI, or singularity. Do you get the same (or similar) errors if you use mpich? Could you provide a list of the MPI environment variables in the container? We have a list of MPI environment variables that we check here: https://github.com/STEllAR-GROUP/hpx/blob/35b2d3b66abaff81e39405eb1c2d923e911392ef/CMakeLists.txt#L817-L819.

**Comment by hkaiser** [comment] 2020-01-13 11:18
Could you collect the execution environment for both instances of the HPX application launched, please? That will allow to reproduce the situation outside of a concrete singularity setting.

**Comment by KilianWerner** [comment] 2020-01-13 13:01
MPICH is sadly not available at our cluster. However the problem (isolated localities even though MPI works correctly) occured without the use of singularity a few times before in our workgroup. 

One suspicion is that OS updates on the cluster provocated the behaviour, since we observed the bug appearing and disappearing without changes in our building process in weeks around patch days. Even so, the problem still has to lie with hpx and can only be provoked by the environment, as MPI World sizes and ranks were correct and MPI communication possible at all times.

execution environment see attached
[environment.txt](https://github.com/STEllAR-GROUP/hpx/files/4053618/environment.txt)

**Comment by hkaiser** [comment] 2020-01-13 13:40
Just an observation: while the `PMIX_RANK` is properly set in both localities, the `SLURM_xxx` environment variable look odd for locality 1. 

```
Locality 0:
SLURM_LOCALID=0
SLURM_NNODES=2
SLURM_NODEID=0
SLURM_NODELIST=node[215,237]
SLURM_NPROCS=2
SLURM_NTASKS=2
SLURM_NTASKS_PER_NODE=1
SLURM_PROCID=0
```
but
```
Locality 1:
SLURM_LOCALID=0
SLURM_NNODES=1
SLURM_NODEID=0
SLURM_NODELIST=node[215,237]
SLURM_NPROCS=1
SLURM_NTASKS=1
SLURM_NTASKS_PER_NODE=1
SLURM_PROCID=0
SLURM_STEP_LAUNCHER_PORT=41466
SLURM_STEP_NODELIST=node237
SLURM_STEP_NUM_NODES=1
SLURM_STEP_NUM_TASKS=1
SLURM_STEP_TASKS_PER_NODE=1
```
While some of the SLURM settings on Locality 1 indicate that there are 2 nodes involved in the job, other settings indicate that it's only one node. HPX looks primarily at the `SLURM_STEP_NUM_TASKS` and `SLURM_NODEID` settings (see https://github.com/STEllAR-GROUP/hpx/blob/master/libs/batch_environments/src/slurm_environment.cpp). We apparently have to refine the analysis of the environment variables to accommodate for the described SLURM quirk.

**Comment by KilianWerner** [comment] 2020-01-14 12:52
I can confirm that this slurm behaviour is reproducable on the used cluster.

The setup that is currently working on the cluster (hpx 1.0.0, openmpi 3.1.4) outputs a warning that is probably related to this issue, however performs correctly anyway:

hpx::init: command line warning: --hpx:localities used when running with SLURM, requesting a different number of localities (2) than have been assigned by SLURM (1), the application might not run properly.

Note that the command line argument --hpx:localities is not used and the application executes with hpx::find_all_localities().size() = 2.

 To me this, looks like the illogical slurm environment variables are successfully ignored in that setting. Is there a way to configure HPX's treatment of environment variables and enforce this ignore-slurm behavior? For example OMPI_COMM_WORLD_SIZE and OMPI_COMM_WORLD_RANK are correctly set.

**Comment by hkaiser** [comment] 2020-01-14 13:14
Thanks. I think that we will need your help in fixing this. The file I linked above does the environment analysis in case the application was started through SLURM. Would you be willing to try modifying that file such that it uses SLURM environment variables in a way that works around problem? For instance you could look at the `SLURM_NODELIST` to determine that there are two nodes involved and then use `SLURM_STEP_NODELIST` to find the node-id of that instance in the node list. There might be other ways however...

**Comment by sithhell** [comment] 2020-01-14 20:09
This is not a issue with slurm per se. The environment variables are a
result in how openmpi launches it's jobs.
The workaround to make it work is to tell hpx to ignore the batch
environment. That way, you might need to set the number of threads and
thread bindings appropriately if your using multiple localities per node.
One possible fix would be to not extract the localities information but
only from MPI and leave the thread binding configuration to the slurm
environment.

**Comment by sithhell** [comment] 2020-01-14 20:19
Thomas Heller <thom.heller@gmail.com> schrieb am Di., 14. Jan. 2020, 21:09:

> This is not a issue with slurm per se. The environment variables are a
> result in how openmpi launches it's jobs.
> The workaround to make it work is to tell hpx to ignore the batch
> environment.
>

Using this option:
https://stellar-group.github.io/hpx/docs/sphinx/tags/1.2.0/html/manual/launching_and_configuring_hpx_applications.html#cmdoption-hpx-ignore-batch-env

That way, you might need to set the number of threads and thread bindings
> appropriately if your using multiple localities per node.
> One possible fix would be to not extract the localities information but
> only from MPI and leave the thread binding configuration to the slurm
> environment.
>

**Comment by msimberg** [comment] 2020-01-15 08:18
To confuse things more, note that we also have the `--hpx:use-process-mask` option which implies `-hpx:ignore-batch-env`, and which uses the process mask set by slurm/mpi. This is useful in setups with multiple ranks on a single node. I think ignoring the batch environment means that the number of nodes isn't detected though.

**Comment by KilianWerner** [comment] 2020-01-15 13:50
Both --hpx:use-process-mask and --hpx:ignore-batch-env result in isolated localities too.

I am working on a slurm_environment.cpp adaption. However I don't understand why this information is retrieved in such a complicated matter. If MPI is the backend for HPX why not just call MPI standard methods for rank, world size and node names? This way HPX will work if (whatever) MPI works and slurm can be as quirky as it wants to be.

**Comment by KilianWerner** [comment] 2020-01-15 14:33
I did the appended quick&dirty mod of the slurm_environment.cpp of hpx version 1.3.0

Instead of SLURM_STEP_NODELIST now SLURM_JOB_NODELIST is used, other SLURM stuff is replaced by OMPI_COMM stuff. While this solution now depends on OpenMPI and a matching of one task per node it resolves the isolated localities, which proves we are looking at the right problem. 

[slurm_environment.cpp.txt](https://github.com/STEllAR-GROUP/hpx/files/4065330/slurm_environment.cpp.txt)

**Comment by sithhell** [comment] 2020-01-16 08:27
A diff would have been nicer ;)

In any case. Changing from `SLURM_STEP_NODELIST` to `SLURM_JOB_NODELIST` is not the correct fix. We need to rely on the actual slurm job step. This is important if you run multiple jobs within one allocation, that is change the number of nodes, run on different nodes, etc.. As mentioned, this unfortunately conflicts with the way how OpenMPI launches processes when configured with SLURM support, as you can observe, the second process is run as a new step.

Now, the fact that you are still seeing the bad behavior when passing `--hpx:ignore-batch-env` is because you are using 1.3.0. IIRC, this issue was fixed by #4035 (fixes #4032) and is the underlying root cause of this issue. The new 1.4.0 release should work then.

So the proper fix would be, to ignore the number of processes set by the batch environment iff mpi was enabled and use those instead.

Another possible workaround would be (at least for the case when you run one locality per node):
`mpirun ./application --hpx:ignore-batch-env --hpx:localities=$SLURM_NNODES`

Upgrading to 1.4.0 should fix the issue without needing the above workaround.

**Comment by KilianWerner** [comment] 2020-01-16 12:33
Yes, a hard coded slurm_environment.cpp cannot fit all slurm settings (at least if the quirky openmpi+slurm setting on our cluster counts). Maybe it would help to be able to specify via command line which environment variables to look at. 

The workaround mpirun ./application --hpx:ignore-batch-env --hpx:localities=2 does solve the issue for me for now.

Sadly I was not yet able to build hpx 1.4.0. Examples fail with

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Segmentation fault (core dumped)

So I cannot confirm the issue is fixed without workaround in 1.4.0

**Comment by msimberg** [comment] 2020-01-23 08:28
@KilianWerner could you try to get a backtrace with `gdb`? `catch throw` should make it stop at the exception.

**Comment by KilianWerner** [comment] 2020-01-23 09:43
@msimberg Thanks for helping with this issue too. See gdb results attached.
[gdb.txt](https://github.com/STEllAR-GROUP/hpx/files/4102324/gdb.txt)
![gdb](https://user-images.githubusercontent.com/59651227/72973207-24032f80-3dcd-11ea-9919-1f6023a47b7c.png)

**Comment by hkaiser** [comment] 2020-01-23 22:15
> Yes, a hard coded slurm_environment.cpp cannot fit all slurm settings (at least if the quirky openmpi+slurm setting on our cluster counts). Maybe it would help to be able to specify via command line which environment variables to look at.
> The workaround mpirun ./application --hpx:ignore-batch-env --hpx:localities=2 does solve the issue for me for now.
> Sadly I was not yet able to build hpx 1.4.0. Examples fail with
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Segmentation fault (core dumped)
> 
> So I cannot confirm the issue is fixed without workaround in 1.4.0

This looks like an ABI problem (i.e. either different versions of HPX being mixed or different compiler flags (standard c++ versions) used for HPX and the application). I would suggest making sure that all traces of the V1.3.0 installation of HPX are purged before building V1.4.0. CMake does not do a good job when it comes to making sure older versions are uninstalled/deleted.

**Comment by KilianWerner** [comment] 2020-02-26 10:41
@hkaiser The bad_alloc still occurs in 1.4.1. It also occurs in a docker container (no previous hpx installations) and when running the built in examples (no possible differences in building hpx and the application).

**Comment by hkaiser** [comment] 2020-02-26 14:05
@KilianWerner as @msimberg explained above, the `bad_alloc` is most likely a problem caused by some ABI incompatibilities. In any case, would you have a stack-backtrace for this?

**Comment by KilianWerner** [comment] 2020-02-26 14:45
I am sorry if this should be obvious. How would I go about solving ABI incompatibilities? The above gdb output is my attempt to provide a backtrace from running the hello_world_distributed example after installing hpx 1.4 on a clean ubuntu:disco (in docker). 

> @msimberg Thanks for helping with this issue too. See gdb results attached.
> [gdb.txt](https://github.com/STEllAR-GROUP/hpx/files/4102324/gdb.txt)
> ![gdb](https://user-images.githubusercontent.com/59651227/72973207-24032f80-3dcd-11ea-9919-1f6023a47b7c.png)

**Comment by biddisco** [comment] 2020-02-26 20:06
Looking at the stacktrace, my suspicions would be that boost and hpx were compiled with c++14 and c++17 flags one way around or the other, but not both the same. I suppose you've already checked that.

**Comment by hkaiser** [comment] 2020-02-26 22:35
This could also be  caused by a mix of Release and Debug binaries used for Boost, HPX, and/or the application itself. Please don't mix and match binaries built using different optimization settings.

**Comment by KilianWerner** [comment] 2020-02-27 14:07
Boost is compiled like so:

export CXXFLAGS="-std=c++17 -O3 -DNDEBUG -fopenmp"
cd boost_1_72_0
./bootstrap.sh
./b2 -j8 toolset=gcc cxxflags="-std=c++17 -O3 -DNDEBUG" install

HPX like so:

cmake ../hpx -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCELPORT_TCP=OFF -DCMAKE_CXX_FLAGS="-std=c++17 -O3 -DNDEBUG"
make install

Again, everything is within a clean docker container and the application used is the hello_world_distributed example. So I'm not sure what could cause the mix up.

However compiling HPX with 
-DHPX_WITH_CXX17_FILESYSTEM=OFF -DHPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=ON
resolves the issue for now.

With this I could confirm, that the original MPI Backend error does not occur with hpx 1.4.1. although the following error is still printed (note that the application is not called with any command line arguments): 

hpx::init: command line warning: --hpx:localities used when running with SLURM, requesting a different number of localities (2) than have been assigned by SLURM (1), the application might not run properly.

**Comment by msimberg** [comment] 2020-07-17 08:36
@KilianWerner sorry this fell off the radar for us. It sounds like the problem is "solved". As for the last warning, how did you launch that application? With `hpxrun`, `mpirun`, or `srun`?

**Comment by Cind12** [comment] 2020-07-17 21:59
The problem is solved for now, however it is a reappearing issue, dependent on the occasional openmpi/linux updates on our cluster and hpx releases. Also the warning remains without hindering execution. The problem occurs both with mpirun and srun. I have not yet given hpxrun a try.

**Comment by KilianWerner** [comment] 2020-07-17 22:02
The problem is solved for now, however it is a reappearing issue, dependent on the occasional openmpi/linux updates on our cluster and hpx releases. Also the warning remains without hindering execution. The problem occurs both with mpirun and srun. I have not yet given hpxrun a try. (Please excuse the previous posting from a wrong account.)

**Closed** 2021-06-02 17:50 UTC
Labels: category: parcel transport, tag: wontfix, type: defect
