### ISSUE TITLE
CMAKE Configuration Test Failures for clang 3.5 on debian

### ISSUE THREAD

**Issue by vamatya** [STEllAR-GROUP/hpx#1566] opened 2015-05-29 09:39 UTC
Configuration test failures shown for c++11 feature tests, shown here, https://gist.github.com/vamatya/e73c9454944b0f97bc33, however the tests seem actually not performed : https://gist.github.com/vamatya/ed6a75bef5d96ee0ec7b. 

hpx_version: commit 41e1e53658e0b6c463a38e020e7e7f149fe7f00f ; May 25
platform: debian, 
compiler: clang 3.5

**Comment by sithhell** [comment] 2015-05-29 11:26
I was not able to reproduce this with latest master and a debian clang 3.5 installation using jemalloc, hwloc and boost provided by debian's package manager.

**Comment by hkaiser** [comment] 2015-05-29 12:09
The second file you linked does not contain the error log for the problem.

**Comment by vamatya** [comment] 2015-05-29 20:24
That's all I get in the log. Installing fortran, removed earlier error. I'm using tcmalloc, hwloc, boost all built/installed from source. Cmake options: https://gist.github.com/vamatya/75a53e9e811bf39bf69c.

**Comment by sithhell** [comment] 2015-05-29 20:37
On Friday, May 29, 2015 13:24:22 Vinay Amatya wrote:
> That's all I get in the log. Installing fortran, removed earlier error. I'm
> using tcmalloc, hwloc, boost all built/installed from source. Cmake
> options: https://gist.github.com/vamatya/75a53e9e811bf39bf69c.

As mentioned multiple times on IRC already: A missing Fortran compiler is 
*not* a hard error and has no effect on how the core libraries are built.

My guess is that some of your dependencies aren't installed correctly or some 
libraries fail to link with that compiler. Did you try if everything works for 
you with the system provided libraries?

**Comment by hkaiser** [comment] 2015-05-29 21:43
Can you give us a dump of your environment, please?

**Comment by sithhell** [comment] 2015-05-29 21:52
Please also apply that patch: https://gist.github.com/sithhell/30c6f9c05d4fa3c2032f/raw/d55e1a1e62013626b67493bb61abd19c7ee2202f/test.patch

and post the output with it applied!

**Comment by hkaiser** [comment] 2015-05-30 00:01
@sithhell Should we apply this patch in general?

**Comment by vamatya** [comment] 2015-05-30 11:32
printenv: https://gist.github.com/vamatya/c1d49ae88ce1a48e2bc4
cmake_out after applying patch : https://gist.github.com/vamatya/597291880985c7212b35

Indiviually compiling all c++11_test files with clang/clang++ went through except, cxx11_std_is_final.cpp

**Comment by sithhell** [comment] 2015-05-30 11:43
Am 30.05.2015 1:32 nachm. schrieb "Vinay Amatya" <notifications@github.com>:
>
> printenv: https://gist.github.com/vamatya/c1d49ae88ce1a48e2bc4
> cmake_out after applying patch :
https://gist.github.com/vamatya/597291880985c7212b35

There you go. The boost libraries can not be linked (undefined reference to
some std library). How did you build those? Did you link the boost libs
with libc++? Could you rebuild them with clang in C++14 mode?

>
> Indiviually compiling all c++11_test files with clang/clang++ went
through except, cxx11_std_is_final.cpp

Sure, because when you build them just like that, you probably don't link
against the boost libraries.
This is a bug in our cmake scripts (that is, the compiler feature tests
shouldn't link against boost). However, you would have run into the same
error when linking libhpx.

**Comment by hkaiser** [comment] 2015-05-30 12:20
What's the next steps?

**Comment by hkaiser** [comment] 2015-05-30 12:34
Even if linking against Boost is not necessary, it should work after all. Any idea why clang reports missing symbols from libc++?

**Comment by sithhell** [comment] 2015-05-30 12:34
Am 30.05.2015 2:20 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> What's the next steps?

Get a working set of boost libraries. The ones provided by Debian should
work.

**Comment by sithhell** [comment] 2015-05-30 12:46
Am 30.05.2015 2:34 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> Even if linking against Boost is not necessary, it should work after all.
Any idea why clang reports missing symbols from libc++?

My guess is that he built boost with libc++ but didn't pass the necessary
flag to cmake.

**Comment by vamatya** [comment] 2015-05-31 05:06
@sithhell: Build boost options used: https://gist.github.com/vamatya/829b92f05b9febe54820
How do you build them in C++14 mode? cxxflags="-std=c++14 .... "? Tried that, still didn't work. 
What cmake flag should be passed?  -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++"? 
Using boost provided by Debian works.

**Comment by sithhell** [comment] 2015-05-31 18:01
Am 31.05.2015 7:06 vorm. schrieb "Vinay Amatya" <notifications@github.com>:
>
> @sithhell: Build boost options used:
https://gist.github.com/vamatya/829b92f05b9febe54820
> How do you build them in C++14 mode? cxxflags="-std=c++14 .... "? Tried
that, still didn't work.
> What cmake flag should be passed? -DCMAKE_CXX_FLAGS="-std=c++11
-stdlib=libc++"?

If you've built boost with libc++, you have to build hpx with it as well,
so yes, adding -stdlib=libc++ to the cmake flags is what you should do.

**Comment by hkaiser** [comment] 2015-05-31 18:03
I think we can close this issue now

**Comment by biddisco** [comment] 2015-08-10 07:25
I ran into a problem with this as well. I specified the wrong hwloc installation in my cmake command line and as a result, the config tests did not link and all the CXX11_FEATURE_XXX tests failed, causing cmake config to abort early and I wsted some time trying to work out what was wrong. This is a genuine bug as the config tests should not link against these other libraries - if the main build fails later, you will see an error message (in this case a link error) and the problem will be obvious, but because the config tests hide the compilation output, you do not see the problem immediately.

The fix would/should be to only use the minimal set of flags/libs etc when testing for features.

**Comment by hkaiser** [comment] 2015-08-10 12:12
> The fix would/should be to only use the minimal set of flags/libs etc when testing for features.

Not sure how much effort this requires. For now, we could print the compilation output for the feature tests (when they fail) with HPX_CMAKE_LOG_LEVEL=Debug or so.

**Comment by sithhell** [comment] 2015-08-10 12:15
On 08/10/2015 02:12 PM, Hartmut Kaiser wrote:
>> The fix would/should be to only use the minimal set of flags/libs etc when testing for features.
> 
> Not sure how much effort this requires. For now, we could print the compilation output for the feature tests (when they fail) with HPX_CMAKE_LOG_LEVEL=Debug or so.

Shouldn't be that much ... would just require to do the compiler checks
before we search for libraries.

**Comment by hkaiser** [comment] 2015-08-11 01:49
@biddisco please check #1712 and verify that it fixes your issue

**Closed** 2015-08-11 09:52 UTC
Labels: affecting: CSCS, category: CMake
