### ISSUE TITLE
Performance regression in thread annotations

### ISSUE THREAD

**Issue by severinstrobl** [STEllAR-GROUP/hpx#5397] opened 2021-06-16 21:17 UTC
Some change introduced between 84cf823 and the current master seems to result in a serious performance regression when using the parallel algorithms, e.g., `hpx::transform_reduce`, with an annotated lambda, where the performance deteriorates by a factor of 5 in my application. It seems also other loop constructs are affected, although not quite as drastically.

@khuck: Any idea if there was a change in APEX that could manifest in such a dramatic way?

## Specifications
  - HPX Version:1.7.0-rc1/master
  - APEX Version: 2.4.1
  - Platform (compiler, OS): GCC 10.2.0, Linux

**Comment by khuck** [comment] 2021-06-16 22:41
@severinstrobl can you share a simple example that reproduces it?  I'll see what I can find on my end.  Obviously something changed, but I don't know where...

**Comment by severinstrobl** [comment] 2021-06-17 06:39
Sure, I'll try to put something together either tomorrow or on the weekend.

**Comment by severinstrobl** [comment] 2021-06-17 10:30
In fact, the old example I used to play around with when looking into task annotations also exhibits the problem, so [here is my testcase](https://gist.github.com/severinstrobl/001637c417caf341faccb76350e678b9).

On my test system I get the following results for the time spent in the annotated function:

HPX version | APEX version | runtime [s]
-- | -- | --
84cf823 | 2.3 | 778.515
f3c41fa | 2.4 | 2.18e+04

Just to be sure I also tested the recent version of HPX with APEX disabled and the runtime is about the same as for the older version with APEX, so it is not a general regression in `hpx::transform`.

p.s.: Is there a way to find out the exact version of APEX used? There is `GIT_COMMIT_HASH` in `apex_config.h` but this is the HPX commit.

**Comment by khuck** [comment] 2021-06-17 16:30
@severinstrobl how did you "disable" APEX?  You mean you configured HPX without APEX?

You can disable APEX at runtime by setting the environment variable APEX_DISABLE=1, which will make every APEX API call return immediately.  If that time is the same as the run with APEX fully enabled, then I think the regression is in HPX.  When HPX is configured with APEX, several other features are forced on in HPX for example:

```cmake
# If APEX is defined, the action timers need thread debug info.
if(HPX_WITH_APEX)
  hpx_add_config_define(HPX_HAVE_THREAD_DESCRIPTION)
  if(HPX_WITH_THREAD_DESCRIPTION_FULL)
    hpx_add_config_define(HPX_HAVE_THREAD_DESCRIPTION_FULL)
  endif()
endif()
```

**Comment by khuck** [comment] 2021-06-17 16:31
The exact version is the commit with that version tag.

**Comment by khuck** [comment] 2021-06-17 17:17
@severinstrobl @hkaiser I have confirmed this is NOT related to changes in the APEX library, but in HPX.  here is how I reproduced that:

I built HPX two different ways, one with APEX enabled and one without.  The plain HPX build is in the `$HOME/src/hpx/build` directory, the HPX+APEX build is in the `$HOME/src/hpx/build_apex` directory.  Then I built the example from Severin, both without and with APEX:

```bash
export PKG_CONFIG_PATH=$HOME/src/hpx/build/lib/pkgconfig
cflags=`pkg-config --cflags hpx_application`
libs=`pkg-config --libs hpx_application`

g++ ${cflags} test.cpp -o without ${libs} -Wl,-rpath,${HOME}/src/hpx/build/lib -Wl,-rpath,/home/khuck/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-9.3.0/gperftools-2.8.1-4tdycospw2h737mhsbaqxwmo6wua26br/lib

export PKG_CONFIG_PATH=$HOME/src/hpx/build_apex/lib/pkgconfig
cflags=`pkg-config --cflags hpx_application`
libs=`pkg-config --libs hpx_application`

g++ ${cflags} test.cpp -o with ${libs} -Wl,-rpath,${HOME}/src/hpx/build_apex/lib -Wl,-rpath,/home/khuck/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-9.3.0/gperftools-2.8.1-4tdycospw2h737mhsbaqxwmo6wua26br/lib
```

and I could reproduce the overhead (I shortened the iterations to 2, and it took from 11.9 seconds to 25.1 on my 4-core laptop).  HOWEVER, I noticed that APEX doesn't even get linked in to the executable with these settings.  I re-linked, adding the APEX library:
```
libapex=${HOME}/src/hpx/build_apex/apex/src/apex
g++ ${cflags} test.cpp -o with ${libs} -L${libapex} -lhpx_apex -Wl,-rpath,${HOME}/src/hpx/build_apex/lib -Wl,-rpath,${libapex} -Wl,-rpath,/home/khuck/spack/opt/spack/linux-ubuntu20.04-sandybridge/gcc-9.3.0/gperftools-2.8.1-4tdycospw2h737mhsbaqxwmo6wua26br/lib
```
and the overhead got a little worse (up to 30 seconds).  Which is VERY strange, because during that time, there are less than 250 timed HPX tasks:
```
Timer                                                : #calls  |    mean  |   total  |  % total  
------------------------------------------------------------------------------------------------
                                           APEX MAIN :        1     30.328     30.328    100.000
            broadcast_call_shutdown_functions_action :        1      0.000      0.000      0.000
hpx::parallel::execution::detail::hierarchical_bu... :       96      0.284     27.251     22.463
                              load_components_action :        1      0.003      0.003      0.002
                                        multiply-add :      136      0.673     91.465     75.395
                                            pre_main :        2      0.000      0.000      0.000
                   primary_namespace_colocate_action :        1      0.000      0.000      0.000
                                          run_helper :        1      0.017      0.017      0.014
                                 shutdown_all_action :        1      0.333      0.333      0.274
                                           APEX Idle :                          2.245      1.850
------------------------------------------------------------------------------------------------
                                        Total timers : 239
```
After which I ran with APEX_DISABLE=1 and the time went back down to 20 seconds.  These aren't super accurate measurements because I am running in a virtual machine on my laptop, but I am pretty sure the (main) problem isn't in APEX...

**Comment by khuck** [comment] 2021-06-17 18:04
In fact, here is some gproftools profiler output of the reproducer benchmark with APEX enabled, and you can see that a lot of time is spent in annotate_function and children (53%): http://www.nic.uoregon.edu/~khuck/with2.pdf, versus the run without (where annotate_function disappears completely - is it compiled away?): http://www.nic.uoregon.edu/~khuck/without.pdf

**Comment by severinstrobl** [comment] 2021-06-17 18:28
@khuck  Thanks for looking into that and the extra information! I did in fact also use two builds, one with APEX enabled and one without.

As the impact on performance is so high, I'd be surprised if it was a change in APEX. My suspicion is that due to some change around `annotated_function` the functor maybe gets copied instead of being passed by reference or something similar.

And yes, with APEX disabled `annotate_function` is just an empty function that gets optimized away.

**Comment by severinstrobl** [comment] 2021-06-17 19:00
@hkaiser Based on some (manual) bisecting and looking at the history, I am somewhat confident that the culprit was introduced with #5347, possibly e509f93?

**Comment by hkaiser** [comment] 2021-06-17 19:18
> @hkaiser Based on some (manual) bisecting and looking at the history, I am somewhat confident that the culprit was introduced with #5347, possibly [e509f93](https://github.com/STEllAR-GROUP/hpx/commit/e509f93739c87ccb5c0031e4987bf2eb3efc63fb)?

Thanks for diagnosing things. I'll try to have a look over the weekend.

**Comment by hkaiser** [comment] 2021-06-18 19:57
@severinstrobl:  I can confirm, that adding this line causes the regression: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/threading_base/include/hpx/threading_base/annotated_function.hpp#L143. @msimberg you were right when you raised an eyebrow at this during review.

I see several possible solutions here:

- The main culprit for the slowdown is the lock in `thread_data::set_description` (https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/threading_base/include/hpx/threading_base/thread_data.hpp#L282). All of the uses of `set_thread_description` in our code base are invoked on the thread itself. We could get rid of the lock assuming that no outside thread would ever access it.
- We could not store the thread description twice (in APEX and the `thread_data`) if APEX is enabled. @khuck is there an API to retrieve the description for a given thread? This would alleviate the problem at least in case APEX is enabled.
- We could simply revert the change I referred to above, but this would re-introduce the issues we have seen in the past that `annotated_function` not always properly sets the description.
- For parallel algorithms: 'lift' the annotated part of the (algorithm loop) function into the partitioner to avoid setting the annotation for each iteration, but just once per chunk. 

None of the listed solutions is perfect.

For now, I'll go with lifting any annotated function from inside an algorithm loop body such that it will annotate the chunk execution instead.

Thanks again @severinstrobl and @khuck for helping to diagnose this issue.

**Comment by msimberg** [comment] 2021-06-18 20:17
@hkaiser nice diagnosis!

Regarding the fourth option: what about making use of the new ability to set the annotation on the policy rather than the callable? If I understand you correctly you're talking about taking the annotation from the callable and adding/moving it to the chunks instead, but I suppose setting the annotation on the policy would have the same effect, without internal changes?

That still leaves a potential performance hit if one isn't aware of this behaviour and one annotates the callable, but I personally find the policy the more "correct" place to put the annotation for parallel algorithms. And it still leaves the possibility to separately annotate the callable as well, if one would want that (perhaps processing each element takes long enough that it's interesting to annotate each call). This is even more true in cases where there is an additional projection and it's not clear which annotation should be used.

I can't judge if removing the lock is completely safe to remove, but it sounds like that would be a good option.

@severinstrobl would you mind trying this:

```
    hpx::transform(hpx::execution::experimental::with_annotation(policy, "multiply-add"),
              std::begin(b), std::end(b),
              std::begin(c), std::begin(a),
              [](const value_type b, const value_type c) {
                return b + scalar * c;
              });
```
?

**Comment by hkaiser** [comment] 2021-06-18 21:06
@msimberg this is a nice idea, however it will not work for arbitrary executors. At least the example provided relies on the `hpx::compute::host::block_executor` that does not support annotations.

**Closed** 2021-06-22 12:56 UTC
Labels: category: APEX, type: defect
