### ISSUE TITLE
run_guarded using bound function ignores reference

### ISSUE THREAD

**Issue by Syntaf** [STEllAR-GROUP/hpx#1864] opened 2015-11-13 23:34 UTC
It seems binding a variable to a function, then calling run_guarded on that binding won't honor a reference. Take a minimal example

``` cpp
#include <hpx/lcos/local/composable_guard.hpp>
#include <hpx/util/bind.hpp>
#include <hpx/hpx_init.hpp>
#include <iostream>

void incr(int &il1) {
    // increment variable by 1, implicitly lock guard
    il1 = il1 + 1;
    // implicitly unlock guard
}

hpx::lcos::local::guard l1;

int hpx_main(boost::program_options::variables_map&)
{
    int i1 = 0;

    // run incr with i1 passed as a reference
    run_guarded(l1, hpx::util::bind(incr, boost::ref(i1)));

    std::cout << i1 << std::endl;

    return hpx::finalize();
}

int main(int argc, char* argv[]) 
{
    boost::program_options::options_description
        desc_commandline("Usage: " HPX_APPLICATION_STRING " [options]");

    return hpx::init(desc_commandline, argc, argv);
}
```

If you were to compile and run this

```
> ./a.out
0
```

It seem's `i1` is not updated, although i've bound a reference of it to incr and invoked it via run_guarded. Is this a bug or am I mistaken?

**Comment by Syntaf** [comment] 2015-11-13 23:54
IRC Logs:
```
<K-ballo> Syntaf: does it ever hit incr?
<Syntaf> K-ballo: inc is called, if I placed a print statement within it, it would print 
<K-ballo> the guard executes afterwars
<K-ballo> *afterwards
<K-ballo> weird, I too would have expected it to synchronize
<K-ballo> not bind's fault then
<Syntaf> so run_guarded has fire and forget semantics?
<hkaiser> Syntaf: it seems to execute things during destruction
```

**Comment by stevenrbrandt** [comment] 2015-11-14 02:09
I think the problem is that at the time you print out i1, it hasn't yet incremented. If you put a print statement inside the guarded function, I think you'll see that it does run. To answer the question about fire and forget, the answer is a qualified yes. While the guard doesn't return a future, attaching another function will happen after the first, the equivalent of a then(). The intent was that you program it in "futurized" style. If a guard did return a future and had a get(), then it would lose the property of being inherently deadlock free.

**Comment by hkaiser** [comment] 2015-11-14 16:06
@stevenrbrandt Is there a way to allow synchronization with the last function running within the guard? Could we add something like

    void incr(int &il1) {
        il1 = il1 + 1;
    }

    hpx::lcos::local::guard l1;
    int l1 = 0;
    run_guarded(l1, hpx::util::bind(incr, boost::ref(i1)));

    // ...

    hpx::future<void> f = l1.get_future();

    // ...

    f.get(); // wait for all guarded functions to execute

**Comment by stevenrbrandt** [comment] 2015-11-15 11:34
Let me give a more thorough explanation of what a guard is supposed to be.
Maybe that will help us clarify what we should do about this ticket.

In the old days we wrote programs with long-lived threads and when we wanted to
have only one of them access a certain region of code, we blocked them using
mutexes. The problem, of course, if thread_a wants to acquire first mutex_1
then mutex_2, and thread_b wants to acquire first mutex_2 then mutex_1, a
deadlock occurs. The wisdom was that you should get your mutexes in canonical
order. Unfortunately, that wasn't possible if you wanted your programs to be
composable. There was no way out of that hell.

However, now that we have short-lived user level threads we can think of how to
solve the problem in a new way. What if adding mutexes to a running thread is
the real problem? What if we solve it by making the thread itself the critical
section? This is the idea of the guard. The guard is like a mutex, but you need
to acquire your guard or guards before your thread enters the run queue--and
you release them automatically when the thread exits.

If you need several guards at once, the system can sort them in some canonical
order and acquire them one by one before making the thread that wants to use
them ready-to-run. Voila, composability and no deadlocks. In fact, nothing even
blocks.

Another problem with mutexes is that if you suspend the thread holding it, new
threads can potentially be blocked. Guards don't have this problem. Because
each thread that wants to use a guard doesn't get to enter the run queue until
its guards are ready, no thread is ever blocked by another holding a guard. So
guards solve this problem too.

Consider this problem (switching to pseudo-code):

```
guard g1;

run_guarded(g1,thread_a(){
  f = run_guarded(g1,thread_b(){...});
  f.get(); // deadlock
});
```

Potentially, this could be solved if I made guards re-entrant. However, that
still doesn't quite work.

```
guard g1, g2;

run_guarded(g1,thread_a(){
  f = run_guarded({g1,g2},thread_b() {...});
  f.get(); 
});
run_guarded(g2,thread_c() {
  f = run_guarded({g1,g2},thead_d() {...});
}
```

Now we're back to where we started. Effectively, thread_a() first holds guard
g1, then tries to add g2 while it's running. Thread c does the same thing in
reverse, and we have deadlock. The whole idea of guards was to prevent this.

I think "futurization" is the new paradigm. Why call get() when we have then()?
Maybe we should think of guards as a way to futurize code that needs mutexes.

Why not take the original code, and write it like this?

```

int hpx_main(boost::program_options::variables_map&)
{
    int i1 = 0;

    // run incr with i1 passed as a reference
    run_guarded(l1, hpx::util::bind(incr, boost::ref(i1)));

    run_guarded(l1,[&i1](){ std::cout << i1 << std::endl; });

    return hpx::finalize();
}
```

**Comment by hkaiser** [comment] 2015-11-15 15:22
Thanks for the explanation, Steve!

> ```
> guard g1;
>
> run_guarded(g1,thread_a(){
>   f = run_guarded(g1,thread_b(){...});
>   f.get(); // deadlock
> });
> ```

It might be possible to detect this and throw if a future is requested from an 'inner' guard.

> I think "futurization" is the new paradigm. Why call get() when we have then()?

I fully agree, however eventually you always need to synchronize with all of your asynchronous code - be it at the end of the computation or the end of an iteration.

**Comment by stevenrbrandt** [comment] 2015-11-15 17:24
Hartmut, it is possible to synchronize with all the async code. One of the properties of the guard is that it is guaranteed to execute the methods attached to it in the order in which they were received. Thus, in the example below, f2 always executes after f1.
```
run_guarded(g1,f1)
run_guarded(g2,f2)
```
Additionally, I rely on the fact that HPX doesn't terminate until all running threads terminate. That covers end of program synchronization.

However, yes, what you say about detecting and throwing these errors make sense. That breaks composability, but it's less offensive because it tells you immediately where and when you made the mistake.

**Comment by hkaiser** [comment] 2015-11-15 18:17
What about:

    guard g;
    vector<double> v = { ... };
    parallel::for_each(par, v.begin(), v.end(),
        [&g](double d)
        {
            run_guarded(g, [d]() { ... });
        });

    // you'd want this:
    g.get_future().get();

**Comment by stevenrbrandt** [comment] 2015-11-15 19:23
Did you intend to use the same guard for each method in the loop? Because the guard is going to effectively sequentialize your loop. Anyhow, we should probably discuss this more when I get back.

**Comment by hkaiser** [comment] 2015-11-15 19:33
Yah, the example is not very convincing... What I meant to show is that we might want to be able to synchronize with all functions run using the guard at any point, not only at the end of the execution.

**Comment by hkaiser** [comment] 2017-03-03 13:19
@stevenrbrandt, @Syntaf: Is this still an issue? Can we close this?

**Comment by stevenrbrandt** [comment] 2017-03-03 14:17
We've talked about the possibility of having guards return a future. For various reasons, this is tricky to do inside the guard code itself. One has to put a promise inside the guard data structures and pass it around, which means one has to be very careful about whether hpx::init has been called, as well as complicating some otherwise simple garbage collection issues. I've done the following, however,
{{{
hpx::future<void> run_guarded_future(guard_set& gs,std::function<hpx::future<void>()> fun) {
  std::shared_ptr<hpx::promise<void>> prom{new hpx::promise<void>()};
  run_guarded(gs,[fun,prom](){
    hpx::future<void> f = fun();
    f.then([prom](auto a){ prom->set_value(); }); 
  }); 
  return prom->get_future();
}
}}}
This should have the capability you want. The difficulty (apart from the wrongness of calling get() and not then()) with using it is that it has noticeably lower performance (at least for the Intersim benchmark).  Maybe we should talk more about what you want to do about this.

**Comment by hkaiser** [comment] 2017-03-21 18:10
@stevenrbrandt This code example will fail as `promiose` is move-only. Hpwever, if you considered using C++14 you could write:
```
hpx::future<void> run_guarded_future(guard_set& gs,std::function<hpx::future<void>()> fun) {
  std::shared_ptr<hpx::promise<void>> prom{new hpx::promise<void>()};
  hpx::future<void> f = prom.get_future();
  run_guarded(gs,[fun,prom=std::move(prom)]() mutable {
    hpx::future<void> f = fun();
    f.then([prom=std::move(prom)](auto a){ prom->set_value(); }); 
  }); 
  return f;
}
```
But your code was C++14 before so this shouldn't be an issue...

I'll go ahead and close this now. Please feel free to re-open, if necessary.

**Closed by hkaiser** 2017-03-21 18:10 UTC
Labels: category: LCOs, type: defect
