### ISSUE TITLE
HPX does not configure

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#3889] opened 2019-06-06 16:01 UTC
## Expected Behavior

Configuring HPX as follows should work. It works for HPX 1.2.1, but not the latest master.

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS='-g' \
  -DHPX_WITH_EXAMPLES=OFF \
  -DHPX_WITH_TESTS=OFF \
  -DHPX_WITH_MALLOC=system \
  -DHPX_WITH_NETWORKING=OFF \
  -DHPX_WITH_ITTNOTIFY=OFF \
  -DHPX_WITH_THREAD_COMPATIBILITY=ON \
  -DHPX_WITH_APEX=OFF \
  -DHPX_WITH_DOCUMENTATION=OFF \
  -DHPX_PREFIX=/usr \
  -DHPX_WITH_MORE_THAN_64_THREADS=ON \
  -DHPX_WITH_MAX_CPU_COUNT=80 \
  -DCMAKE_INSTALL_PREFIX=/usr \
   /usr/install/hpx

## Actual Behavior

... Please describe the behavior you actually observed.

From the error log
Building C object CMakeFiles/cmTC_8c521.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_8c521.dir/CheckSymbolExists.c.o   -c /usr/install/hpx/builddir/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_8c521
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8c521.dir/link.txt --verbose=1
/usr/bin/cc     -Wl,-z,defs -fvisibility=hidden  -rdynamic CMakeFiles/cmTC_8c521.dir/CheckSymbolExists.c.o  -o cmTC_8c521
CMakeFiles/cmTC_8c521.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8c521.dir/build.make:97: recipe for target 'cmTC_8c521' failed
make[1]: *** [cmTC_8c521] Error 1
make[1]: Leaving directory '/usr/install/hpx/builddir/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8c521/fast' failed
make: *** [cmTC_8c521/fast] Error 2

File /usr/install/hpx/builddir/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
```
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. The above cmake invocation should cause the problem.

## Specifications

... Please describe your environment

  - HPX Version: Latest master
  - Platform (compiler, OS):
  1. OS was debian 9.5
  2. C++ was GNU 6.3
  3. Boost was 1.62.0
  4. Cmake: 3.8

**Comment by stevenrbrandt** [comment] 2019-06-06 16:05
If I add
{{{
  -DCMAKE_EXE_LINKER_FLAGS=-lpthread \
  -DCMAKE_MODULE_LINKER_FLAGS=-lpthread \
}}}
I get past the previous error, but I encounter this one:
{{{
CMake Error at cmake/HPX_AddPseudoDependencies.cmake:28 (add_dependencies):
  Cannot add target-level dependencies to non-existent target
  "tests.examples".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
Call Stack (most recent call first):
  libs/cache/examples/CMakeLists.txt:8 (add_hpx_pseudo_dependencies)
}}}

**Comment by hkaiser** [comment] 2019-06-06 16:42
@stevenrbrandt the second error is a duplicate of #3879. Please leave tests enabled while configuring HPX, that should get you over the problem for now. Alternatively you should be able to disable examples (`-DHPX_WITH_EXAMPLES=OFF`).

**Comment by msimberg** [comment] 2019-06-11 13:58
I'm not able to reproduce this (different versions for me though). Could you:
1. Post the non-verbose log? Is it the `HPX_WITH_CXX11_THREAD` check that fails?
2. Try with `HPX_WITH_THREAD_COMPATIBILITY=OFF`? Is this essential for you (I'd like to get rid of it)?
3. If the above fails, run a `git bisect` to find the commit that broke this?

**Comment by hkaiser** [comment] 2019-06-25 13:37
@stevenrbrandt any news on this?

**Comment by msimberg** [comment] 2020-04-27 14:55
Closing this due to inactivity. @stevenrbrandt please reopen if this is still a problem.

**Closed by msimberg** 2020-04-27 14:55 UTC
Labels: category: CMake, type: defect
