### ISSUE TITLE
Linking issue with libhpx_initd.a

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#4537] opened 2020-04-17 09:23 UTC
I stumbled on an issue with HPX on master (c140bf0ebafe8c1caadc0c122fea8e583988ab2f). We have a small static library (`DLAF_gtest_hpx_main`) providing `main()` to our unit tests (GoogleTest) :

```
GTEST_API_ int test_main(int, char**) {
  std::printf("Running main() from gtest_hpx_main.cpp\n");
  auto ret = RUN_ALL_TESTS();
  hpx::finalize();
  return ret;
}

GTEST_API_ int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);

  return hpx::init(test_main, argc, argv);
}
```

Linking the library (`DLAF_gtest_hpx_main`) to our tests results in a linker error
```
ld: <install_tree>/lib/libhpx_initd.a(hpx_wrap.cpp.o): in function `hpx_start::hpx_entry(int, char**)':
<build_tree>/init/src/hpx_wrap.cpp:73: undefined reference to `main'
ld: <install_tree>/lib/libhpx_initd.a(hpx_wrap.cpp.o): in function `__wrap_main':
<build_tree>/init/src/hpx_wrap.cpp:137: undefined reference to `main'
```

The issue is resolved if `DLAF_gtest_hpx_main` is linked after `libhpx_initd.a` (thanks Mikael!). 

Our link line for reference:
```
#!/bin/bash

/usr/bin/g++-8  -g \
  -Wl,-rpath -Wl,/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/mpich-3.3.2-7mdalbfq7raethryd4niu6auxdhroyvw/lib \
  -Wl,-no-as-needed CMakeFiles/test_lapack_tile.dir/test_lapack_tile.cpp.o  -o test_lapack_tile   \
  -L/opt/cuda/lib64  \
  -L/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/intel-mkl-2020.0.166-pinkbbeche3f7eupbcugs7zoqlgp2asn/mkl/lib/intel64_lin  \
  -Wl,-rpath,/opt/cuda/targets/x86_64-linux/lib/stubs:/opt/cuda/lib64:/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/intel-mkl-2020.0.166-pinkbbeche3f7eupbcugs7zoqlgp2asn/mkl/lib/intel64_lin:/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/blaspp-develop-htfdrvnpg54pjqh5uqqg4swamiewswvu/lib:/opt/cuda/targets/x86_64-linux/lib:/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/mpich-3.3.2-7mdalbfq7raethryd4niu6auxdhroyvw/lib:/home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/hpx-master-otndlec6iycvjrvmcztldh4kbyjsld42/lib \
  ../../src/libDLAF.a \
  ../libDLAF_test.a \
  ../src/libDLAF_gtest_hpx_main.a \
  -lmkl_intel_lp64 -lmkl_sequential -lmkl_core \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/lapackpp-develop-e5l4clzhnoqu5tmrpydlu65owgzy53jo/lib/liblapackpp.a \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/blaspp-develop-htfdrvnpg54pjqh5uqqg4swamiewswvu/lib/libblaspp.so \
  /usr/lib/gcc/x86_64-pc-linux-gnu/8.4.0/libgomp.so /usr/lib/libpthread.so -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -DFORTRAN_ADD_ -DADD_ \
  /opt/cuda/targets/x86_64-linux/lib/stubs/libcublas.so /opt/cuda/targets/x86_64-linux/lib/libcudart.so \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/mpich-3.3.2-7mdalbfq7raethryd4niu6auxdhroyvw/lib/libmpicxx.so \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/mpich-3.3.2-7mdalbfq7raethryd4niu6auxdhroyvw/lib/libmpi.so \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/hpx-master-otndlec6iycvjrvmcztldh4kbyjsld42/lib/libhpx_initd.a \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/hpx-master-otndlec6iycvjrvmcztldh4kbyjsld42/lib/libhpxd.so.1.5.0 \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/hpx-master-otndlec6iycvjrvmcztldh4kbyjsld42/lib/libhpx_apex.so.1.5.0 \
  /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/gcc-8.4.0/hpx-master-otndlec6iycvjrvmcztldh4kbyjsld42/lib/libhpx_initd.a \
  /usr/lib/libboost_program_options.so /usr/lib/libboost_filesystem.so /usr/lib/libtcmalloc_minimal.so /usr/lib/libhwloc.so \
  -latomic -ldl -lrt -Wl,-wrap=main ../../lib/libgtestd.a -lpthread

```

Note: `libhpx_initd.a` occurs twice.

(The link line is a little messy, one of our dependencies is propagating some definitions on the link line... please ignore)

**Comment by msimberg** [comment] 2020-04-17 09:27
Likely caused by #4462. I'll look into this. `libhpx_wrap.a` must've appeared earlier in the link line than `libhpx_init.a`.

**Comment by msimberg** [comment] 2020-04-23 15:25
Note: I'm referring to `hpx_init` and `hpx_wrap` as they were before the merge.

This is mainly a result of `hpx_wrap/hpx_init` now being linked automatically together with `hpx`. @teonnik was using the CMake variable `HPX_LIBRARIES` which in the latest release did not link to `hpx_wrap`. That had to be done separate with `HPX_LINK_LIBRARIES`. It also meant that it was possible to not link against `hpx_wrap`. The reason linking to `hpx_wrap` automatically works is that `main` is usually built together with the executable in an object file which the linker accepts. In reality there is a funny dependency from `hpx_wrap` to the object file but the linker allows this. If `main` is in a static library it does not allow it. It's possible to manually get things linking by placing the libraries in the right order: `hpx_wrap -> user_static_lib_with_main -> hpx_init` (or after the merge declaring that `hpx_init` and `user_static_lib_with_main` have circular dependencies with `--start-group` and `--end-group`). As far as I can tell there's no way for us to enforce that only using the `HPX::hpx` target.

That gives us two options:
1. Document that if someone wants to put main outside of the main executable it has to be in an object file.
2. Add a target `HPX::hpx_no_hpx_wrap` which would be identical to `HPX::hpx` but does not link to `hpx_wrap`.

I would not like to make `HPX::hpx` not link to `hpx_wrap` since that's far more common than having `main` in a static library. I think I'd prefer the second option, but it would require a bit of refactoring of our targets internally.

**Comment by hkaiser** [comment] 2020-04-23 15:46
> I would not like to make HPX::hpx not link to hpx_wrap since that's far more common than having main in a static library. I think I'd prefer the second option, but it would require a bit of refactoring of our targets internally.

👍

**Comment by msimberg** [comment] 2020-05-04 08:14
@teonnik by the way, one way to get around this in the meantime is setting `HPX_WITH_DYNAMIC_HPX_MAIN=OFF`. This disables all the linker magic for wrapping the main function. #4564 will give you a way to avoid it even if HPX was compiled with it on though.

**Comment by aurianer** [comment] 2020-05-07 10:49
Closing this since #4564 has been merged

**Closed by aurianer** 2020-05-07 10:49 UTC
Labels: category: init, type: defect
