### ISSUE TITLE
Building and using HPX statically: undefined references from runtime_support_server.cpp

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/hpx#2696] opened 2017-06-14 15:15 UTC
Hi, is there anything I have to turn on other than `-DHPX_WITH_STATIC_LINKING=ON` to get a static version of hpx?

I get a lot of undefined references when trying to build octotiger statically. Specifically. hpx::util::plugin::dll::LoadLibrary(hpx::error_code&, bool) seems to use dlopen, which requires a dynamically linked libc, if I interpret the warning correctly. This also triggers undefined references, as the application now wants a dlopen symbol.

I'm filing this as a (possible) hpx issue as the undefined references are triggered by the hpx plugin system. Is this an HPX issue?

For the full error see: [gist with error](https://gist.github.com/DavidPfander-UniStuttgart/531a55f78e102bc00fdde6ba53f2e290)

**Comment by sithhell** [comment] 2017-06-23 07:24
`-DHPX_WITH_STATIC_LINKING=On` should be sufficient. Could you provide a way to reproduce that bug?

**Comment by DavidPfander-UniStuttgart** [comment] 2017-06-23 11:46
Can't even compile a static build of only hpx on my ubuntu xenial machine:
```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DHPX_WITH_EXAMPLES=OFF -DBOOST_ROOT=/home/pfandedd/boost_1_62_0_install -DHPX_WITH_MALLOC=jemalloc -DCMAKE_BUILD_TYPE=release -DHPX_WITH_STATIC_LINKING=On ../ > output_cmake.log 2>&1
make -j1 VERBOSE=1 > output_make.log 2>&1
```
[output_cmake.txt](https://github.com/STEllAR-GROUP/hpx/files/1097662/output_cmake.txt)
[output_make.txt](https://github.com/STEllAR-GROUP/hpx/files/1097663/output_make.txt)

**Comment by sithhell** [comment] 2017-06-23 20:03
Are all of your dependencies (boost, jemalloc and hwloc) compiled as static
libraries?

Am 23.06.2017 1:46 nachm. schrieb "David Pfander" <notifications@github.com

**Comment by DavidPfander-UniStuttgart** [comment] 2017-06-25 10:17
Shouldn't the build system complain if I haven't?

If you look at the logs attached in my last post, you can see that I'm only linking against static libraries.

**Comment by hkaiser** [comment] 2017-06-25 15:10
> Shouldn't the build system complain if I haven't?

Isn't the build system 'complaining' to you?

**Comment by DavidPfander-UniStuttgart** [comment] 2017-06-25 15:11
Guys, why am I even posting logs if you don't look at them...

No, the build system doesn't complain, because static libs are there. Still, linking fails.

**Comment by sithhell** [comment] 2017-06-25 16:06
Am 25.06.2017 5:11 nachm. schrieb "David Pfander" <notifications@github.com
>:

Guys, why am I even posting logs if you don't look at them...


Did I also miss the cmake invocation?

No, the build system doesn't complain, because static libs are there.
Still, linking fails.

**Comment by sithhell** [comment] 2017-06-25 16:18
Looks like I missed the cmake invocation indeed. Obviously, there are missing link time dependencies. It looks like they mostly come out of libdl, and from libraries we don't have any control over. Certainly needs some investigation.

**Comment by sithhell** [comment] 2017-06-25 16:29
Which cmake version are you using? I vaguely remember there was a problem with the static builds. The version I used on Cori was 3.3.2, that's the one I know works.

**Comment by DavidPfander-UniStuttgart** [comment] 2017-06-30 13:58
I'm using cmake 3.5.1. This is not on cori/tavi, but on my ubuntu desktop machine (16.04).
Still getting the same undefined reference as mentioned in the logs.

**Comment by sithhell** [comment] 2017-06-30 14:05
Right. I think that version is buggy. Could you please try the static build with either 3.8 or 3.3.2?

**Comment by hkaiser** [comment] 2017-07-03 14:54
Can we close this now? This seems to be a cmake problem, not one on our end.

**Comment by DavidPfander-UniStuttgart** [comment] 2017-07-03 16:20
Feel free to close, I'm able to use dynamic builds again on all platform. But I can't rule out the problems described in the original post still exist as I don't know which cmake version I was using.

**Closed** 2017-07-03 20:32 UTC
Labels: category: core, type: defect
