### ISSUE TITLE
Component type-related failures

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4348] opened 2020-01-28 15:07 UTC
There seem to be two variations of this failure that I've seen on pycicle. Collecting them here for easier finding:

- `traits::component_type_is_compatible< typename action_type::component_type>::call(addr)`
    - [tests.unit.agas.local_embedded_ref_to_local_object ](https://cdash.cscs.ch/testDetails.php?test=16789894&build=91735)
    - [tests.unit.parallel_block.task_block_par](https://cdash.cscs.ch/testDetails.php?test=16984829&build=92369)
    - [tests.regressions.lcos.future_hang_on_wait_with_callback_629](https://cdash.cscs.ch/testDetails.php?test=16984813&build=92369)
- `!addr || components::get_base_type(addr.type_) == components::component_base_lco_with_value`
    - [tests.examples.1d_stencil.1d_stencil_7](https://cdash.cscs.ch/testDetails.php?test=16943993&build=92233)
    - [tests.examples.1d_stencil.1d_stencil_6](https://cdash.cscs.ch/testDetails.php?test=17180669&build=92947)

The two assertions might be unrelated of course...

**Comment by hkaiser** [comment] 2020-01-28 15:44
Those errors are definitely related. I think they are caused by something going out of scope prematurely.

**Closed** 2020-08-25 22:31 UTC
Labels: category: components, tag: wontfix, type: defect
