### ISSUE TITLE
HPX can't be used with IO pool turned off

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4818] opened 2020-07-10 07:13 UTC
As reported here: https://github.com/STEllAR-GROUP/hpx/pull/4815#issuecomment-656060214.

**Comment by aurianer** [comment] 2020-07-14 17:32
@biddisco I tried to reproduce your error but I failed, would you have a reproducible example?
At what point I got [this error](https://gist.github.com/aurianer/01e670b34b47c21925349e2b834e13e9) but it was because I was still linking the iostream component to my example ^^'

**Comment by hkaiser** [comment] 2020-07-15 14:38
Should we change the iostreams implementation to silently fall back to execute the output operation on the current HPX thread (instead of dispatching it to the IO-pool) in this case?

**Comment by msimberg** [comment] 2020-07-16 13:44
I think an error is appropriate. After all if a user tries to use HPX iostreams they do so with the expectation that it will be processed on another thread.

Just linking to `libhpx_iostreams` should not lead to anything being written to the IO pool without the user asking for it though and that should probably be fixed.

**Comment by hkaiser** [comment] 2020-07-19 17:38
> Just linking to libhpx_iostreams should not lead to anything being written to the IO pool without the user asking for it though and that should probably be fixed.

I agree. However, do we have a reproducible case where this happens?

**Comment by msimberg** [comment] 2020-07-20 09:31
I actually don't think so. I just realized that the iostreams component is disabled when `HPX_WITH_DISTRIBUTED_RUNTIME=OFF` (as it should be). @aurianer is it possible that you had an old `libhpx_iostreams.so` lying around which got linked in your case? From a clean build directory with the distributed runtime and io pool off it's not even possible to link to the iostreams component by mistake. @biddisco please comment if this is actually a reproducible issue for you or if we should close this for now.

**Comment by biddisco** [comment] 2020-07-23 19:43
I compiled with IO_POOL and TIMER_POOL off today and things were working, so it looks like this problem has gone away or it was some corrupted binary of mine. I will close it for now and reopen if it comes back.

**Closed by biddisco** 2020-07-23 19:43 UTC
Labels: type: defect
