### ISSUE TITLE
Compute breaks HPX tests

### ISSUE THREAD

**Issue by mcopik** [STEllAR-GROUP/hpx#2217] opened 2016-06-14 21:10 UTC
Compiler: g++ 4.9
Boost: 1.54
CUDA: 7.5

Branch created from the most recent master, builds fine with all tests passing when configured with:

`-DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9  -DHPX_WITH_EXAMPLES=Off -DHPX_WITH_MALLOC=system`

Adding:

`-DHPX_WITH_CUDA=On`

breaks most of the (if not all) tests depending on compute. A sample error has been attached. 
[fail_out.txt](https://github.com/STEllAR-GROUP/hpx/files/314954/fail_out.txt)

On which platforms compute has been tested before merging with master? I've never had any problems with building and running HPX with those tools. I'd like to cooperate with hpx::compute,. but I can't make any changes, except adding new code, if I can't verify that my updates don't break anything. 

@hkaiser @sithhell

**Comment by sithhell** [comment] 2016-06-15 05:33
I can't reproduce that problem. I am using gcc 4.9.3, cuda 7.5 and boost 1.60. Could you please purge your build directory and try again?

**Comment by mcopik** [comment] 2016-06-15 06:24
Actually, it happened twice - once through CLion and once for a clean manual build. I'll try to remove everything and build again.

**Comment by mcopik** [comment] 2016-06-15 06:56
The very same error, now just happening for transform instead of for_each.

However! The failing command is:
`
/usr/local/cuda/bin/nvcc /home/mcopik/projects/hpx_compute/hpx_compute_refactor/tests/unit/computeapi/cuda/transform_compute.cu -dc -o /home/mcopik/projects/hpx_compute/build_refactor/tests/unit/computeapi/cuda/CMakeFiles/transform_compute_test_exe.dir//./transform_compute_test_exe_generated_transform_compute.cu.o -ccbin /usr/bin/g++ -m64 -D_GNU_SOURCE -Xcompiler ,\"-D_DEBUG\",\"-DDEBUG\",\"-DHPX_DISABLE_ASSERTS\",\"-DBOOST_DISABLE_ASSERTS\",\"-std=c++11\",\"-Wall\",\"-Wextra\",\"-Wno-unused-local-typedefs\",\"-Wno-strict-aliasing\",\"-Wno-sign-promo\",\"-Wno-attributes\",\"-Wno-cast-align\",\"-Wno-unused-parameter\",\"-Wformat=2\",\"-Wno-format-nonliteral\",\"-Winit-self\",\"-Wdouble-promotion\",\"-Wcast-qual\",\"-Wcast-align\",\"-Werror=trampolines\",\"-Werror=parentheses\",\"-Werror=reorder\",\"-Werror=return-type\",\"-Werror=sequence-point\",\"-Werror=format\",\"-Werror=missing-braces\",\"-Werror=sign-compare\",\"-fdiagnostics-show-option\",\"-Werror=vla\",\"-Werror=return-type\",\"-Wno-unused-but-set-parameter\",\"-Wno-unused-but-set-variable\",\"-Werror=uninitialized\",\"-Wno-unused-local-typedefs\",\"-Wno-sync-nand\",\"-Wno-delete-non-virtual-dtor\",\"-fvisibility=hidden\",\"-O3\",\"-DNDEBUG\" -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_30,code=compute_30 -gencode=arch=compute_35,code=compute_35 --expt-relaxed-constexpr --expt-extended-lambda -lcudadevrt -rdc=true -DNVCC -I/usr/local/cuda/include -I/home/mcopik/projects/hpx_compute/hpx_compute_refactor -I/home/mcopik/projects/hpx_compute/build_refactor -I/usr/include -I/home/mcopik/projects/hpx_compute/hpx_compute_refactor/tests -I/usr/local/cuda/include
`

I noticed that `-std=c++11` is passed through -Xcompiler (I guess it's for host compiler options?). Adding `-std=c++11` to nvcc options partially solves the issue - it compiles, I get a ridicilous amount of warnings, most of them in form of:
`
warning: calling a __host__ function [...] from a __host__ __device__ function [...] is not allowed
`
and
`
cc1: warning: command line option ‘-Wno-sign-promo’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
`

Should this flag appear twice, for host and device compiler? You should be able to check easily how it appears in your build command.

My cmake version is 2.8.12.2.

**Comment by sithhell** [comment] 2016-06-15 09:04
> I noticed that -std=c++11 is passed through -Xcompiler (I guess it's for host compiler options?). Adding -std=c++11 to nvcc options partially solves the issue - it compiles, but I get a ridiculous amount of warnings, most of them in form of:
 warning: calling a __host__ function [...] from a __host__ __device__ function [...] is not allowed

We can't do a lot about those warnings at the moment. Yes, they are ridiculous, that's nvcc for you ...

Regarding the flag, I have no idea what's going wrong there. Everything (expect the build unit tests) work for me using the above mentioned toolchain and cmake 3.5.2

**Comment by mcopik** [comment] 2016-06-15 17:49
What do you mean "expect the build unit tests"? I tried different version for cmake, compilation starts working from 3.3 but on 3.5.2 I still can't built few unit tests.

**Comment by hkaiser** [comment] 2016-06-15 20:08
So it's a cmake problem, as expected. Ok, that's worth documenting - CUDA will work starting cmake V3.3 only.

> I still can't built few unit tests.

Which ones?

**Comment by mcopik** [comment] 2016-06-15 20:39
Stream fails at:
`/usr/local/cuda/bin/nvcc /home/mcopik/projects/hpx_compute/hpx_compute_refactor/tests/performance/local/stream.cpp -x=cu -dc -o /home/mcopik/projects/hpx_compute/build_refactor/tests/performance/local/CMakeFiles/stream_exe.dir//./stream_exe_generated_stream.cpp.o -ccbin /usr/bin/gcc-4.9 -m64 --std c++11 -D_GNU_SOURCE -Xcompiler ,\"-D_DEBUG\",\"-DDEBUG\",\"-DHPX_DISABLE_ASSERTS\",\"-DBOOST_DISABLE_ASSERTS\",\"-Wall\",\"-Wextra\",\"-Wno-unused-local-typedefs\",\"-Wno-strict-aliasing\",\"-Wno-sign-promo\",\"-Wno-attributes\",\"-Wno-cast-align\",\"-Wno-unused-parameter\",\"-Wformat=2\",\"-Wno-format-nonliteral\",\"-Winit-self\",\"-Wdouble-promotion\",\"-Wcast-qual\",\"-Wcast-align\",\"-Werror=trampolines\",\"-Werror=parentheses\",\"-Werror=reorder\",\"-Werror=return-type\",\"-Werror=sequence-point\",\"-Werror=format\",\"-Werror=missing-braces\",\"-Werror=sign-compare\",\"-fdiagnostics-show-option\",\"-Werror=vla\",\"-Werror=return-type\",\"-Wno-unused-but-set-parameter\",\"-Wno-unused-but-set-variable\",\"-Werror=uninitialized\",\"-Wno-unused-local-typedefs\",\"-Wno-sync-nand\",\"-Wno-delete-non-virtual-dtor\",\"-fvisibility=hidden\",\"-O3\",\"-DNDEBUG\" -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_30,code=compute_30 -gencode=arch=compute_35,code=compute_35 --expt-relaxed-constexpr --expt-extended-lambda -lcudadevrt -rdc=true -DNVCC -I/usr/local/cuda/include -I/home/mcopik/projects/hpx_compute/hpx_compute_refactor -I/home/mcopik/projects/hpx_compute/build_refactor -I/usr/include -I/home/mcopik/projects/hpx_compute/hpx_compute_refactor/tests -I/usr/local/cuda/include
`

with:
`
/home/mcopik/projects/hpx_compute/hpx_compute_refactor/hpx/compute/host/block_allocator.hpp(151): error: identifier "Initialization guard variable for " is undefined in device code
`
`
/home/mcopik/projects/hpx_compute/hpx_compute_refactor/hpx/compute/host/block_allocator.hpp(151): error: identifier "_ZZN3hpx8parallel2v125parallel_execution_policy10parametersEvE6params" is undefined
`

**Comment by hkaiser** [comment] 2017-03-21 18:00
@mcopik: This should have been fixed on master now. Could you verify this, please?

**Comment by mcopik** [comment] 2017-03-23 10:08
@hkaiser I don't have an access to the machine with the exact same configuration (it was an LSU workstation) but I tried to build master on my workstation with CUDA 8.0. Unfortunately, it fails to build some of CUDA examples and produces a gazillion warnings about calling host functions.

It fails to build partitioned_vector. The error for first case:

```
/usr/include/c++/5/bits/stl_pair.h(128) (col. 17): error: calling a __host__ function("boost::intrusive_ptr< ::hpx::threads::thread_data> ::intrusive_ptr") from a __device__ function("std::pair< ::hpx::threads::thread_state_enum,  ::boost::intrusive_ptr< ::hpx::threads::thread_data> > ::pair") is not allowed
``

I don't think it produced any trace of template instantations.

**Comment by hkaiser** [comment] 2017-03-23 10:11
@atrantan You said everything now worked for you using NVCC? Can you comment, please?

**Comment by mcopik** [comment] 2017-03-23 10:14
It might be an NVCC bug though. I get hundreds of "calling host function" warnings and only one is an error.

The failing command is:
```
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ /home/mcopik/Projekty/stellar/hpx/examples/compute/cuda/partitioned_vector.cu -o /home/mcopik/Projekty/stellar/build/examples/compute/cuda/CMakeFiles/partitioned_vector_exe.dir//partitioned_vector_exe_generated_partitioned_vector.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 --std c++11 -D_GNU_SOURCE -Xcompiler ,\"-D_DEBUG\",\"-DDEBUG\",\"-DHPX_DISABLE_ASSERTS\",\"-DBOOST_DISABLE_ASSERTS\",\"-Wall\",\"-Wextra\",\"-Wno-unused-local-typedefs\",\"-Wno-strict-aliasing\",\"-Wno-sign-promo\",\"-Wno-attributes\",\"-Wno-cast-align\",\"-Wno-unused-parameter\",\"-Wformat=2\",\"-Wno-format-nonliteral\",\"-Winit-self\",\"-Wdouble-promotion\",\"-Wcast-qual\",\"-Wcast-align\",\"-Werror=trampolines\",\"-Werror=parentheses\",\"-Werror=reorder\",\"-Werror=return-type\",\"-Werror=sequence-point\",\"-Werror=uninitialized\",\"-Werror=format\",\"-Werror=missing-braces\",\"-Werror=sign-compare\",\"-fdiagnostics-show-option\",\"-Werror=vla\",\"-Werror=return-type\",\"-Wno-unused-but-set-parameter\",\"-Wno-unused-but-set-variable\",\"-Werror=uninitialized\",\"-Wno-unused-local-typedefs\",\"-Wno-sync-nand\",\"-Wno-delete-non-virtual-dtor\",\"-fvisibility=hidden\",\"-O3\",\"-DNDEBUG\" -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_30,code=compute_30 -gencode=arch=compute_35,code=compute_35 --expt-relaxed-constexpr --expt-extended-lambda --default-stream per-thread -lcudadevrt -rdc=true -DNVCC -I/usr/local/cuda/include -I/home/mcopik/Projekty/stellar/hpx -I/home/mcopik/Projekty/stellar/build -I/usr/include -I/home/mcopik/Projekty/stellar/hpx/examples -I/usr/local/cuda/include
```

But I I remove the -Wall and -Wextra options, then not only warnings are gone but the error as well. I can't verify if it helps because even though the object file is generated and present, CMake is still trying to repeat the failing build command.

**Comment by mcopik** [comment] 2017-03-23 10:18
@atrantan 

```
/usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

**Comment by atrantan** [comment] 2017-03-23 10:52
@mcopik, Warnings do not surprise me and we have to deal we that since we are using `_host_ _device_` prefix in overused fonctions like `invoke()`. partitioned_vector example fails with nvcc. To get rid off those disagreements, I suggest U to compile with cuda clang. The recent clang release (4.0) should be fine

**Comment by mcopik** [comment] 2017-03-23 11:00
@atrantan @hkaiser I see... But it does mean that this issue is still unresolved until NVCC is fixed? Or maybe we should put somewhere in docs that cuda clang is preferred and builds using nvcc are broken at that moment?

**Comment by atrantan** [comment] 2017-03-23 12:10
What we should do is to monentarily remove partition vector from being compiled if nvcc is used. And to notify in the docs that warnings may happen if nvcc is used

**Comment by hkaiser** [comment] 2017-03-23 12:12
> What we should do is to monentarily remove partition vector from being compiled if nvcc is used. And to notify in the docs that warnings may happen if nvcc is used

@atrantan Could you prepare a PR for this, pls?

**Comment by atrantan** [comment] 2017-03-23 15:21
Sure but I need a full section related to _hpx compute_ to exist first. @heller is maybe the best person to do it. For this moment I am able to do a PR that remove `partitioned_vector` from the build tree when nvcc is detected as the default cuda compiler

**Comment by hkaiser** [comment] 2017-03-23 18:35
@atrantan Thanks!

**Closed** 2019-08-03 08:31 UTC
Labels: category: compute, tag: wontfix, type: defect
