### ISSUE TITLE
action_invoke_no_more_than is obsolete

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3043] opened 2017-12-04 14:33 UTC
This was added to fix a certain problem that CSCS had some years ago, it has been superceded by sliding semaphore which is a better way of throttling tasks/actions.

It also fails tests regularly and impededs progress.

**Comment by hkaiser** [comment] 2017-12-04 16:20
The feature implemented by `action_invoke_no_more_than` completely relies on registering special callback-functions with our action invocation mechanism. Removing this example does not solve any issues as it is currently broken not because of the functionality it demonstrates. The root cause for this example to be broken lies in some optimizations applied recently (see #3017).

**Comment by sithhell** [comment] 2017-12-05 19:06
The test has been fixed with #3044. I don't think we should remove it.

**Comment by biddisco** [comment] 2017-12-06 07:11
I did not want to remove the test - I wanted to remove the entire invoke_no_more_than feature. It was added for a specific problem, did not really help and has never been used since. Maintaining it just requires effort and I though it would be beneficial to prune it away.

**Comment by sithhell** [comment] 2017-12-06 07:27
My mistake. I'm impartial here. What do others think?

**Comment by hkaiser** [comment] 2017-12-06 13:41
Let's turn it into an example demonstrating what can be done using the action hooks.

**Comment by shailesh210** [comment] 2018-03-30 04:02
Hello,
If no one is working on this issue, can I take this up? Also, a bit more explanation would be helpful.
Thanks in advance!

**Comment by hkaiser** [comment] 2018-03-30 14:43
@shailesh210 please feel free to take this on. In essence, the functionality that is currently built into the core libraries (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/actions/action_invoke_no_more_than.hpp) should be removed from the core library and re-introduced as a freestanding example.

**Closed** 2018-06-20 14:59 UTC
Labels: affecting: CSCS, category: actions, difficulty: easy, type: defect
