### ISSUE TITLE
Examples do not run on Mac OSX using the M1 chip

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5340] opened 2021-05-17 21:19 UTC
## Expected Behavior

Examples should run. 

## Actual Behavior

Examples crash with 

```
diehlpk@Patricks-MacBook-Air build % ./bin/fibonacci

{config}:
Core library:
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=system
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_PREFIX (configured)=
  HPX_PREFIX=

  HPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=OFF
  HPX_ITERATOR_SUPPORT_WITH_BOOST_ITERATOR_TRAVERSAL_TAG_COMPATIBILITY=OFF
  HPX_PROGRAM_OPTIONS_WITH_BOOST_PROGRAM_OPTIONS_COMPATIBILITY=OFF
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ASYNC_MPI=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_COROUTINE_COUNTERS=OFF
  HPX_WITH_DISTRIBUTED_RUNTIME=ON
  HPX_WITH_DYNAMIC_HPX_MAIN=ON
  HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_INIT_START_OVERLOADS_COMPATIBILITY=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARALLEL_TESTS_BIND_NONE=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=OFF
  HPX_WITH_PARCELPORT_TCP=ON
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_REGISTER_THREAD_OVERLOADS_COMPATIBILITY=ON
  HPX_WITH_SANITIZERS=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_TESTS_DEBUG_LOG=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=OFF
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

Module coroutines:
  HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=OFF

Module datastructures:
  HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON

Module serialization:
  HPX_SERIALIZATION_WITH_BOOST_TYPES=ON

Module topology:
  HPX_TOPOLOGY_WITH_ADDITIONAL_HWLOC_TESTING=OFF

{version}: V1.7.0-trunk (AGAS: V3.0), Git: bb52868611
{boost}: V1.75.0
{build-type}: release
{date}: May 17 2021 15:56:17
{platform}: Mac OS
{compiler}: Clang version 12.0.5 (clang-1205.0.22.9)
{stdlib}: libc++ version 12000
{os-thread}: worker-thread#7
{what}: mmap() failed to allocate thread stack: HPX(unhandled_exception)

```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Compile HPX master using #5339 
  1. Run any example

## Specifications

... Please describe your environment

  - HPX Version: Master with #5339 
  - Platform (compiler, OS): Big Sur, M1 chip

**Comment by diehlpk** [comment] 2022-03-11 03:21
I just tested with boost 1.78 and hpx master and still not working.

**Comment by gonidelis** [comment] 2022-03-12 17:58
@hkaiser Is there any way I could reproduce that either on ROSTAM or at CCT somehow? Otherwise I could link it to [this GSoC project](https://github.com/STEllAR-GROUP/hpx/issues/5340).

**Comment by hkaiser** [comment] 2022-03-12 18:47
> @hkaiser Is there any way I could reproduce that either on ROSTAM or at CCT somehow? Otherwise I could link it to [this GSoC project](https://github.com/STEllAR-GROUP/hpx/issues/5340).

Unfortunately, we don't have access to an environment that would allow to reproduce the issue.

**Comment by masterleinad** [comment] 2023-08-21 21:35
Looks like this was fixed in https://github.com/STEllAR-GROUP/hpx/pull/5928.

**Closed** 2023-08-21 22:19 UTC
Labels: platform: Mac OSX, compiler: clang, platform: ARM
