### ISSUE TITLE
Peformance degrading over time

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1924] opened 2015-12-21 18:22 UTC
I am not sure how to re-open an issue, but I am still having a problem with 

https://github.com/STEllAR-GROUP/hpx/issues/1753

 Here is a plot:

http://s17.postimg.org/6h8qkbvn3/performance.png

This is with 64 nodes on SuperMIC

This is with a version of octotiger that doesn't rely on serialization of std::array, dmarce1/octotiger@7214efe

**Comment by zao** [comment] 2015-12-21 20:57
I reopened the previous issue, turns out that if you're not a collaborator and the issue is closed by a collaborator, you cannot reopen it yourself.

**Comment by hkaiser** [comment] 2015-12-22 18:21
Closing this as a duplicate of #1753

**Closed by hkaiser** 2015-12-22 18:21 UTC
Labels: affecting: LSU, tag: duplicate, type: defect
