### ISSUE TITLE
Compilation Error when HPX_MPI_WITH_FUTURES=ON

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#4539] opened 2020-04-18 07:29 UTC
## Expected Behavior

Compilation succeeds.

## Actual Behavior

Compilation fails with:

```
/home/teonnik/code/hpx/src/hpx_init.cpp:391:23: error: no member named 'mpi_environment' in namespace 'hpx::util'
                util::mpi_environment::init(&argc, &argv, cms);
                ~~~~~~^
/home/teonnik/code/hpx/src/hpx_init.cpp:393:52: error: no member named 'mpi_environment' in namespace 'hpx::util'
                    static_cast<std::size_t>(util::mpi_environment::size());
```

## Steps to Reproduce the Problem

Some of the flags are probably irrelevant:

```
cmake -D CMAKE_BUILD_TYPE=Debug \
       -D BUILD_SHARED_LIBS=ON \
       -D CMAKE_INSTALL_PREFIX=<install_dir> \
       -D HPX_WITH_CXX14=ON \
       -D HPX_WITH_CUDA=ON \
       -D HPX_WITH_MALLOC=tcmalloc \
       -D TCMALLOC_ROOT=<tcmalloc_dir> \
       -D HWLOC_ROOT=<hwloc_dir> \
       -D BOOST_ROOT=<boost_dir> \
       -D MPI_ROOT=<mpi_dir> \
       -D HPX_MPI_WITH_FUTURES=ON \
       -D HPX_WITH_MAX_CPU_COUNT=128 \
       -D HPX_WITH_NETWORKING=OFF \
       -D HPX_WITH_EXAMPLES=OFF \
       -D HPX_WITH_TESTS=OFF \
       -D HPX_WITH_APEX=ON \
       -D APEX_WITH_OTF2=ON \
       -D OTF2_ROOT=<otf_dir> \
       <src_dir>
```

## Specifications

  - HPX Version: master branch, commit f829319ed1ce76e433fb6c6c5242df762566106d
  - compiler: clang 9.0.1
  - cmake: 3.17.1
  - mpich: 3.3.2
  - hwloc: 2.2.0
  - boost: 1.72.0
  - gperftools: 2.7-1
  - otf2: 2.2
  - OS: Arch Linux
  - Kernel: x86_64 Linux 5.6.4-arch1-1
  - CPU: Intel Core i7-5600U @ 4x 3.2GHz
  - GPU: Intel Corporation HD Graphics 5500

**Comment by hkaiser** [comment] 2020-04-18 14:25
FWIW, the problem is only reproducible if `-DHPX_WITH_NETWORKING=OFF`.

**Comment by hkaiser** [comment] 2020-04-18 16:08
@teonnik please see #4540 for a possible fix

**Comment by teonnik** [comment] 2020-04-19 12:56
I just tested #4540 and can confirm that it resolves the problem, compilation completes successfully.

**Comment by hkaiser** [comment] 2020-04-19 15:01
@teonnik We will need to apply some changes to our testing infrastructure before this can be merged. This might take a day or two. Anyways - thanks for verifying!

**Closed** 2020-04-28 19:26 UTC
Labels: category: modules, type: defect
