### ISSUE TITLE
"Re-using the main() function as the main HPX entry point" doesn't work

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4223] opened 2019-11-18 13:09 UTC
## Expected Behavior

It is expected to work (as per [documentation](https://stellar-group.github.io/hpx/docs/sphinx/latest/html/manual/starting_the_hpx_runtime.html#re-use-the-main-function-as-the-main-hpx-entry-point))

## Actual Behavior

```
Runtime is not available, reporting error locally. 
...


assertion 'get_runtime_ptr() != nullptr' failed: HPX(assertion_failure)
```

## Steps to Reproduce the Problem

Build the attached example source. 

The macro `NOT_WORKING_VARIANT` controls which source code variant to use:
- with `-DNOT_WORKING_VARIANT` the non-working variant of the code is used, with `main` as HPX entry point
- without the macro, the working one is used, with manually defined `hpx_main` entry point.

## Specifications

- HPX Version: 1.3.0
- Mac OS X 10.14.6
- Apple LLVM version 10.0.1 (clang-1001.0.46.4) Target: x86_64-apple-darwin18.7.0

[main.txt](https://github.com/STEllAR-GROUP/hpx/files/3858719/main.txt)

**Comment by msimberg** [comment] 2019-11-18 13:13
@albestro how are you building the test executable?

**Comment by albestro** [comment] 2019-11-18 13:14
With a basic CMakeLists.txt in a bigger project, with something like

```
find_package(HPX)
...
add_executable(hpx_not_working main.cpp)
target_include_directories(hpx_not_working PRIVATE ${HPX_INCLUDE_DIRS})
target_link_libraries(hpx_not_working PRIVATE ${HPX_LIBRARIES})
```

**Comment by albestro** [comment] 2019-11-18 13:17
Here the full HPX stacktrace

```
Runtime is not available, reporting error locally.
{stack-trace}: 5 frames:
0x1050bead1     : hpx::util::stack_trace::trace(void**, unsigned long) + 0x21 in /Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/lib/libhpxd.1.dylib
0x104412894     : hpx::util::backtrace::backtrace(unsigned long) + 0x94 in /Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/lib/libhpxd.1.dylib
0x1044127cd     : hpx::util::backtrace::backtrace(unsigned long) + 0x1d in /Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/lib/libhpxd.1.dylib
0x10440a55b     : hpx::util::trace_on_new_stack(unsigned long) + 0x2b in /Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/lib/libhpxd.1.dylib
0x104401a5c     : hpx::detail::backtrace(unsigned long) + 0x1c in /Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/lib/libhpxd.1.dylib
{env}: 72 entries:
  Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.7i8PDMNxuH/Render
  BASH_ENV=/usr/local/Cellar/lmod/8.2.3/init/bash
  CMAKE_PREFIX_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq
  COLORFGBG=15;0
  COLORTERM=truecolor
  CPATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl/include:/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/include
  CUSTOM_LIBS=/usr/local/custom_libs
  DISPLAY=/private/tmp/com.apple.launchd.uDffDx2yw0/org.macosforge.xquartz:0
  DK_NODE=/Users/ialberto/spack/share/spack/dotkit/darwin-mojave-x86_64
  DYLD_FALLBACK_LIBRARY_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib
  DYLD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/compiler/lib:/opt/intel/compilers_and_libraries_2019.1.144/mac/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2019.1.144/mac/tbb/lib:/opt/intel/compilers_and_libraries_2019.1.144/mac/compiler/lib:/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl/lib:/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib
  HOME=/Users/ialberto
  INTEL_LICENSE_FILE=/opt/intel/compilers_and_libraries_2019.1.144/mac/licenses:/opt/intel/licenses:/Users/ialberto/intel/licenses:/Users/Shared/Library/Application Support/Intel/Licenses
  ITERM_PROFILE=Default
  ITERM_SESSION_ID=w2t0p0:199CB2C0-918B-45D1-89C4-121996540924
  LC_CTYPE=UTF-8
  LC_TERMINAL=iTerm2
  LC_TERMINAL_VERSION=3.3.7
  LESS=-R
  LIBRARY_PATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/tbb/lib:/opt/intel/compilers_and_libraries_2019.1.144/mac/compiler/lib:/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl/lib:/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib
  LMOD_CMD=/usr/local/Cellar/lmod/8.2.3/libexec/lmod
  LMOD_DIR=/usr/local/Cellar/lmod/8.2.3/libexec
  LMOD_PKG=/usr/local/Cellar/lmod/8.2.3
  LMOD_ROOT=/usr/local/Cellar/lmod/8.2.3/..
  LMOD_SETTARG_FULL_SUPPORT=no
  LMOD_VERSION=8.2.3
  LMOD_sys=Darwin
  LOADEDMODULES=mpich-3.3.1-clang-10.0.1-apple-obcjhvh
  LOGNAME=ialberto
  LSCOLORS=Gxfxcxdxbxegedabagacad
  MANPATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/share/man:/usr/local/Cellar/lmod/8.2.3/share/man::
  MKLROOT=/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl
  MODULEPATH=/Users/ialberto/spack/share/spack/modules/darwin-mojave-x86_64:/usr/local/Cellar/lmod/8.2.3/modulefiles/Darwin:/usr/local/Cellar/lmod/8.2.3/modulefiles/Core
  MODULEPATH_ROOT=/usr/local/Cellar/lmod/8.2.3/modulefiles
  MODULESHOME=/usr/local/Cellar/lmod/8.2.3
  NLSPATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/compiler/lib/locale/en_US/%N:/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl/lib/locale/%l_%t/%N
  OLDPWD=/Users/ialberto/workspace/repos/hpx_linalg/build/test
  PAGER=less
  PATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/bin/intel64:/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/bin:/Users/ialberto/spack/bin:/Users/ialberto/workspace/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ialberto/workspace/checker-279/bin
  PKG_CONFIG_PATH=/opt/intel/compilers_and_libraries_2019.1.144/mac/mkl/bin/pkgconfig:/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib/pkgconfig
  PWD=/Users/ialberto/workspace/repos/hpx_linalg/build/test
  SHELL=/usr/local/bin/zsh
  SHLVL=1
  SPACK_ROOT=/Users/ialberto/spack
  SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZD1roKlX2N/Listeners
  TERM=xterm-256color
  TERM_PROGRAM=iTerm.app
  TERM_PROGRAM_VERSION=3.3.7
  TERM_SESSION_ID=w2t0p0:199CB2C0-918B-45D1-89C4-121996540924
  TMPDIR=/var/folders/c9/v21gts9n7rs9cycnxcdzr__80000gn/T/
  USER=ialberto
  XPC_FLAGS=0x0
  XPC_SERVICE_NAME=0
  ZSH=/Users/ialberto/.oh-my-zsh
  _=/Users/ialberto/workspace/repos/hpx_linalg/build/test/./hpx_not_working
  _LMFILES_=/Users/ialberto/spack/share/spack/modules/darwin-mojave-x86_64/mpich-3.3.1-clang-10.0.1-apple-obcjhvh
  _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPWZhbHNlLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXt9LG1UPXtbIm1waWNoLTMuMy4xLWNsYW5nLTEwLjAuMS1hcHBsZS1vYmNqaHZoIl09e1siZm4iXT0iL1VzZXJzL2lhbGJlcnRvL3NwYWNrL3NoYXJlL3NwYWNrL21vZHVsZXMvZGFyd2luLW1vamF2ZS14ODZfNjQvbXBpY2gtMy4zLjEtY2xhbmctMTAuMC4xLWFwcGxlLW9iY2podmgiLFsiZnVsbE5hbWUiXT0ibXBpY2gtMy4zLjEtY2xhbmctMTAuMC4xLWFwcGxlLW9iY2podmgiLFsibG9hZE9yZGVyIl09MSxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJd
  _ModuleTable002_=PSJtcGljaC0zLjMuMS1jbGFuZy0xMC4wLjEtYXBwbGUtb2Jjamh2aCIsfSx9LG1wYXRoQT17Ii9Vc2Vycy9pYWxiZXJ0by9zcGFjay9zaGFyZS9zcGFjay9tb2R1bGVzL2Rhcndpbi1tb2phdmUteDg2XzY0IiwiL3Vzci9sb2NhbC9DZWxsYXIvbG1vZC84LjIuMy9tb2R1bGVmaWxlcy9EYXJ3aW4iLCIvdXNyL2xvY2FsL0NlbGxhci9sbW9kLzguMi4zL21vZHVsZWZpbGVzL0NvcmUiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL1VzZXJzL2lhbGJlcnRvL3NwYWNrL3NoYXJlL3NwYWNrL21vZHVsZXMvZGFyd2luLW1vamF2ZS14ODZfNjQ6L3Vzci9sb2NhbC9DZWxsYXIvbG1vZC84LjIuMy9tb2R1bGVmaWxlcy9EYXJ3aW46L3Vzci9sb2NhbC9DZWxsYXIvbG1vZC84LjIuMy9tb2R1
  _ModuleTable003_=bGVmaWxlcy9Db3JlIix9
  _ModuleTable_Sz_=3
  __CF_USER_TEXT_ENCODING=0x0:0:0
  __LMOD_REF_COUNT_CMAKE_PREFIX_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq:1
  __LMOD_REF_COUNT_CPATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/include:1
  __LMOD_REF_COUNT_DYLD_FALLBACK_LIBRARY_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib:1
  __LMOD_REF_COUNT_DYLD_LIBRARY_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib:1
  __LMOD_REF_COUNT_LIBRARY_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib:1
  __LMOD_REF_COUNT_LOADEDMODULES=mpich-3.3.1-clang-10.0.1-apple-obcjhvh:1
  __LMOD_REF_COUNT_MANPATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/share/man:1;/usr/local/Cellar/lmod/8.2.3/share/man:1
  __LMOD_REF_COUNT_MODULEPATH=/Users/ialberto/spack/share/spack/modules/darwin-mojave-x86_64:2;/usr/local/Cellar/lmod/8.2.3/modulefiles/Darwin:1;/usr/local/Cellar/lmod/8.2.3/modulefiles/Core:1
  __LMOD_REF_COUNT_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/bin:1;/Users/ialberto/spack/bin:1;/Users/ialberto/workspace/scripts:1;/usr/local/bin:1;/usr/bin:1;/bin:1;/usr/sbin:1;/sbin:1;/opt/X11/bin:1;/Library/Frameworks/Mono.framework/Versions/Current/Commands:1;/Users/ialberto/workspace/checker-279/bin:1
  __LMOD_REF_COUNT_PKG_CONFIG_PATH=/Users/ialberto/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/mpich-3.3.1-obcjhvhbzojx2y7joisnskq7vjeinaiq/lib/pkgconfig:1
  __LMOD_REF_COUNT__LMFILES_=/Users/ialberto/spack/share/spack/modules/darwin-mojave-x86_64/mpich-3.3.1-clang-10.0.1-apple-obcjhvh:1
{locality-id}: 4294967295
{process-id}: 73355
{function}: hpx::runtime &hpx::get_runtime()
{file}: /Users/ialberto/workspace/libraries/hpx-1.3.0/src/runtime.cpp
{line}: 851
{os-thread}: <unkown>
{thread-description}: <unknown>
{state}: not running
{auxinfo}:
{config}:
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_CXX14_RETURN_TYPE_DEDUCTION=TRUE
  HPX_WITH_DEPRECATION_WARNINGS=ON
  HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_HPXMP=OFF
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_MORE_THAN_64_THREADS=OFF
  HPX_WITH_NETWORKING=OFF
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=OFF
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=OFF
  HPX_WITH_PARCELPORT_TCP=OFF
  HPX_WITH_PARCELPORT_VERBS=OFF
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SANITIZERS=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_SWAP_CONTEXT_EMULATION=OFF
  HPX_WITH_TESTS_DEBUG_LOG=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=OFF
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=system
  HPX_PREFIX (configured)=unknown
  HPX_PREFIX=unknown
{version}: V1.3.0 (AGAS: V3.0), Git: a943fd2c5d
{boost}: V1.70.0
{build-type}: debug
{date}: Oct 31 2019 16:07:09
{platform}: Mac OS
{compiler}: Clang version 10.0.1 (clang-1001.0.46.4)
{stdlib}: libc++ version 7000
{what}: assertion 'get_runtime_ptr() != nullptr' failed: HPX(assertion_failure)
[1]    73355 abort      ./hpx_not_working
```

**Comment by albestro** [comment] 2019-11-18 13:19
And here an extract of what I get from the preprocessor

```cpp
# 758 "/Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/include/hpx/hpx_init.hpp" 2
# 12 "/Users/ialberto/workspace/libraries/all/hpx-1.3.0+debug/include/hpx/hpx_main.hpp" 2







namespace hpx_start
{



                      extern bool include_libhpx_wrap;
                      bool include_libhpx_wrap = true;
}
# 18 "/Users/ialberto/workspace/repos/hpx_linalg/test/hpx_not_working/main.cpp" 2

int main(int argc, char* argv[])
{
  do_something_in_hpx();
  return 0;
}
```

**Comment by albestro** [comment] 2019-11-18 13:24
I gave a quick look and I arrived at https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/hpx_main.hpp so maybe it’s a build problem on my side about `HPX_HAVE_STATIC_LINKING`

I’ve just switched to the other method, but I think it can be helpful for others that may incur in the same problem.

**Comment by hkaiser** [comment] 2019-11-18 14:51
@albestro so this is caused by `-DHPX_WITH_STATIC_LINKING=On`? Interesting! @NK-Nikunj: are you aware of this.

**Comment by albestro** [comment] 2019-11-18 15:04
@msimberg and I chatted offline about this and we did a few tests. I give a quick report here.

In HPX 1.3.0 the required `-Wl,-e,_initialize_main` seems to be used just by `hpx_setup_target` and for pkg-config related stuff.

For this reason, if you use `add_hpx_executable`, that internally uses `hpx_setup_target`, everything works correctly.

The problem arise if you try setting up CMake by not using the helper functions, like I did, since the required flag seems to not be set neither by `HPX_LIBRARIES` nor `HPX_LINK_LIBRARIES`.

**Comment by albestro** [comment] 2019-11-18 15:07
Additional note: I tested it on newest master (fd67ac0f86cb6a8b6c7692fed3e7498db28a1ba8) and everything works correctly both using `add_hpx_executable` or using `target_link_libraries(... ${HPX_LIBRARIES} ${HPX_LINK_LIBRARIES})`.

**Comment by msimberg** [comment] 2019-11-18 15:19
Just for the record, I think `HPX_WITH_STATIC_LINKING` was a red herring (especially because last time I tried it was more broken than this: #3970).

**Comment by NK-Nikunj** [comment] 2019-11-18 15:24
This looks interesting. I remember building with `HPX_WITH_STATIC_LINKING=On` and it worked just fine with it as well.

**Comment by NK-Nikunj** [comment] 2019-11-18 15:28
It seems like it has something to do with recent CMake changes. I'm pretty sure my method works for statics as well.

**Comment by msimberg** [comment] 2019-11-18 15:31
@NK-Nikunj don't worry :) static linking is broken in different ways but I think it's unrelated to this. I'm closing this now since it works on latest master. If someone really badly needs a patch release to fix this on macOS, let us know.

**Closed by msimberg** 2019-11-18 15:31 UTC

**Comment by biddisco** [comment] 2019-11-25 19:37
@NK-Nikunj 
Any idea why I'm getting this error
```
ninja explain: test/unit/parallel/stdthread/stdthread_test is dirty
[1/1] : && /usr/bin/g++  -fPIC -march=native -mtune=native -ffast-math -std=c++17 -g  -rdynamic  -Wl,-e,_initialize_main test/unit/parallel/stdthread/CMakeFiles/stdthread_test.dir/stdthread_test.cpp.o  -o test/unit/parallel/stdthread/stdthread_test  -Wl,-rpath,/home/biddisco/apps/mpich/3.3.1/lib:/home/biddisco/build/dca/libs/googletest-1.8.0:/home/biddisco/build/hpx-debug/lib:/home/biddisco/apps/jemalloc/5.2.1/lib:/home/biddisco/apps/hwloc/2.1.0/lib:/home/biddisco/apps/cxx17/boost/1.69.0/lib /home/biddisco/apps/mpich/3.3.1/lib/libmpicxx.so /home/biddisco/apps/mpich/3.3.1/lib/libmpi.so libs/googletest-1.8.0/libgtest_main.so src/parallel/hpx/libparallel_hpx.a libs/googletest-1.8.0/libgtest.so -lpthread /home/biddisco/apps/mpich/3.3.1/lib/libmpicxx.so /home/biddisco/apps/mpich/3.3.1/lib/libmpi.so /home/biddisco/build/hpx-debug/lib/libhpx_wrapd.a /home/biddisco/build/hpx-debug/lib/libhpx_initd.a /home/biddisco/build/hpx-debug/lib/libhpxd.so.1.4.0 -latomic -ldl -lrt /usr/lib/x86_64-linux-gnu/libpthread.so /home/biddisco/apps/jemalloc/5.2.1/lib/libjemalloc.so /home/biddisco/apps/hwloc/2.1.0/lib/libhwloc.so /home/biddisco/apps/cxx17/boost/1.69.0/lib/libboost_program_options.so && :
/usr/bin/ld: warning: cannot find entry symbol _initialize_main; defaulting to 000000000003d100
```

**Comment by NK-Nikunj** [comment] 2019-11-25 23:21
@biddisco 
Interesting! It is linking with `hpx_wrapd.a` and yet complaining that it can't find the symbol.

**Comment by NK-Nikunj** [comment] 2019-11-25 23:26
Let me have a look at it tomorrow. Maybe I'm getting something wrong somewhere.

**Comment by biddisco** [comment] 2019-11-26 03:18
I solved my problem so please ignore this question

**Comment by biddisco** [comment] 2019-11-26 03:18
it turned out to be the order of linking that was causing trouble. All fixed now.

**Comment by NK-Nikunj** [comment] 2019-11-26 15:08
Aah, I see! Glad it worked out.
