### ISSUE TITLE
Clangd (Language Server) throws error for __integer_pack at pack.hpp

### ISSUE THREAD

**Issue by andreichalapco** [STEllAR-GROUP/hpx#6412] opened 2024-01-11 21:08 UTC
I've built the hpx from source (using master from Jun 2023) using a gcc 13.1.1 compiler. My Ide for development is sometimes clion and also nvim that both use clangd language server. 

When going trough examples from the hpx I instantly get errors from the language server: Use  of undeclared identifier __integer_pack in `pack.hpp:49`. I know this is a placeholder for the gcc compiler but when running this with clangd it is pretty nerving sometimes...

Should `pack.hpp` use something in the direction of this:

```cpp
#if __has_builtin(__make_integer_seq)
      template<typename, size_t... _Indices>
	using _IdxTuple = _Index_tuple<_Indices...>;

      // Clang defines __make_integer_seq for this purpose.
      using __type = __make_integer_seq<_IdxTuple, size_t, _Num>;
#else
      // For GCC and other compilers, use __integer_pack instead.
      using __type = _Index_tuple<__integer_pack(_Num)...>;
#endif
```
(this is basically taken from [this](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/utility.h#L153))

In order to reproduce this just run:

```
clangd --check=main.cpp
``` 

Where main.cpp include 

```cpp
#include <hpx/hpx_main.hpp>
#include <hpx/iostream.hpp>

int main()
{
    // Say hello to the world!
    hpx::cout << "Hello World!\n" << std::flush;
    return 0;
}
```

One other option I tried was using clangd with --query-driver to query the gcc driver for the necessary system headers but this didn't fix the problem. 

Is there any solution to make the language server work with the source code of hpx ... ?

I'm not sure if clangd language server is a high priority now ... but I thought I mention this. If needed I could try to make a pull request.

**Comment by andreichalapco** [comment] 2024-01-11 23:22
On further checking the cmake building process I discovered this:

```cmake
  # Check the availability of certain C++ builtins
  hpx_check_for_builtin_integer_pack(DEFINITIONS HPX_HAVE_BUILTIN_INTEGER_PACK)

  hpx_check_for_builtin_make_integer_seq(
    DEFINITIONS HPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ
  )
```

So basically if building the source with clang ... I can avoid the macro HPX_HAVE_BUILTIN_INTEGER_PACK ... and have HPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ.

I still believe this is not something good ... because there are for sure many people that want to compile everything with gcc but still use the clangd language server ... (so basically use clion)

**Comment by hkaiser** [comment] 2024-01-11 23:23
I'm not sure if anybody I know uses clangd for their work, so I wouldn't know whom to ask. This is probably caused by HPX being configured by one compiler (gcc) and being used with another one (clangd). The decision of what is supported is being made at configuration time, so that later on clangd sees things to be used that it doesn't support.

I'd very much appreciate it if you had the time and interest to come up with a possible fix (PR) for this.

**Comment by John98Zakaria** [comment] 2024-05-01 06:04
I had reported that issue to jetbrains years ago.
https://youtrack.jetbrains.com/issue/CPP-29030/False-positive-systax-error-highlighting-for-hpx

**Comment by hkaiser** [comment] 2024-05-02 12:32
Let's not close this issue. We've had similar reports in other contexts. I believe this can be fixed.

**Comment by andreichalapco** [comment] 2024-05-02 12:42
Yeah! I think you're right! As a feedback after using hpx there a lot of problems with the clangd lanaguge server, which is a real pity, because I think it is nowadays the most used one (it' s also open source). It would be nice if some efforts would be directed in this direction.

**Closed** 2024-05-03 15:01 UTC
Labels: type: compatibility issue
