### ISSUE TITLE
partitioned_vector_spmd_foreach seg faults

### ISSUE THREAD

**Issue by dcbdan** [STEllAR-GROUP/hpx#2193] opened 2016-05-31 22:00 UTC
The problem occurs when setting the data to the view, inside the generate function call.

```
[dbourge@node52 hpx_build]$ srun -p haswell -N 2 ./bin/partitioned_vector_spmd_foreach 
using seed: 1464731610
using seed: 1464731610
{stack-trace}: 8 frames:
0x7fd07bf0fb14  : hpx::termination_handler(int) + 0x124 in /home/dbourge/hpx/hpx_build/lib/libhpx.so.0
0x7fd07a2f6710  : ??? + 0x7fd07a2f6710 in /lib64/libpthread.so.0
0x4141dc        : ??? + 0x4141dc in /home/dbourge/hpx/hpx_build/./bin/partitioned_vector_spmd_foreach
0x7fd07bf6efb2  : hpx::runtime_impl<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::run_helper(hpx::util::function<int (), false>, int&) + 0x4a2 in /home/dbourge/hpx/hpx_build/lib/libhpx.so.0
0x7fd07bf3b7aa  : ??? + 0x7fd07bf3b7aa in /home/dbourge/hpx/hpx_build/lib/libhpx.so.0
0x7fd07c159292  : hpx::threads::coroutines::detail::coroutine_impl::operator()() + 0xc2 in /home/dbourge/hpx/hpx_build/lib/libhpx.so.0
0x7fd07bf38ff9  : ??? + 0x7fd07bf38ff9 in /home/dbourge/hpx/hpx_build/lib/libhpx.so.0
{what}: Segmentation fault
{config}:
  HPX_HAVE_NATIVE_TLS=ON
  HPX_HAVE_STACKTRACES=ON
  HPX_HAVE_COMPRESSION_BZIP2=OFF
  HPX_HAVE_COMPRESSION_SNAPPY=OFF
  HPX_HAVE_COMPRESSION_ZLIB=OFF
  HPX_HAVE_PARCEL_COALESCING=ON
  HPX_HAVE_PARCELPORT_TCP=ON
  HPX_HAVE_PARCELPORT_MPI=OFF
  HPX_HAVE_PARCELPORT_IPC=OFF
  HPX_HAVE_PARCELPORT_IBVERBS=OFF
  HPX_HAVE_VERIFY_LOCKS=OFF
  HPX_HAVE_HWLOC=ON
  HPX_HAVE_ITTNOTIFY=OFF
  HPX_HAVE_RUN_MAIN_EVERYWHERE=OFF
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=talloc
  HPX_PREFIX (configured)=/home/dbourge/inst_hpx
  HPX_PREFIX=/home/dbourge/hpx/hpx_build
{version}: V0.9.12-trunk (AGAS: V3.0), Git: 597cab849c
{boost}: V1.61.0
{build-type}: release
{date}: May 31 2016 12:14:31
{platform}: linux
{compiler}: GNU C++ version 4.9.2
{stdlib}: GNU libstdc++ version 20141030
srun: error: node53: task 1: Aborted
srun: First task exited 30s ago
srun: task 0: running
srun: task 1: exited abnormally
srun: Terminating job step 1028848.7
srun: Job step aborted: Waiting up to 2 seconds for job step to finish.
slurmd[node52]: *** STEP 1028848.7 KILLED AT 2016-05-31T15:54:00 WITH SIGNAL 9 ***
slurmd[node52]: *** STEP 1028848.7 KILLED AT 2016-05-31T15:54:00 WITH SIGNAL 9 ***
[dbourge@node52 hpx_build]$
```

**Comment by hkaiser** [comment] 2016-06-01 00:09
I'm not able to reproduce this issue. Could you please give us more details? How did you build HPX, what system, compiler did you use, how did you run the example, etc.

**Comment by hkaiser** [comment] 2016-06-01 00:37
@dcbdan I take that comment back: please verify whether the problems is fixed on the branch fixing_2193.

**Comment by dcbdan** [comment] 2016-06-01 13:37
Thanks! The example works on fixing_2193.

**Closed** 2016-06-02 23:54 UTC
Labels: category: examples, type: defect
