### ISSUE TITLE
Compile error in addressing_service.cpp

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2697] opened 2017-06-14 16:35 UTC
I am getting a compile error with master (SuperMIC, GCC 7.1) when CXX14 is OFF. Should HPX compile with C++11 ?

https://gist.github.com/dmarce1/f8c9911ca379af2ba09a6bdb91b485aa

**Comment by hkaiser** [comment] 2017-06-14 17:09
This is a boost problem which I don't know how to solve at this point. Everything should work with gcc 6.x or older versions of Boost.

**Comment by hkaiser** [comment] 2017-06-14 17:15
@dmarce1 From what I can see, this error started to occur once we added support for C++17 to our build system. Could you try to explicitly force it to use C++11 or C++14, please (add `-DHPX_WITH_CXX11=On` or `-DHPX_WITH_CXX14=On` to the cmake command line)?

**Comment by hkaiser** [comment] 2017-07-03 14:52
I'm going to close this issue as it is caused by Boost and we have found a workaround. Please feel free to reopen, if needed.

**Closed by hkaiser** 2017-07-03 14:52 UTC
Labels: compiler: gcc, type: defect
