### ISSUE TITLE
Serializing multiple arguments when applying distributed action results in segfault

### ISSUE THREAD

**Issue by esseivaju** [STEllAR-GROUP/hpx#5998] opened 2022-08-31 00:43 UTC
## Expected Behavior

Call a remote action regardless of the number of parameters as long as they are all serializable. 

## Actual Behavior

A very specific combination of parameters seems to systematically result in a segfault in a distributed environment.

## Steps to Reproduce the Problem

I have a [reproducible example](https://github.com/esseivaju/HPXDistributed/blob/action_2args_error/src/demo.cpp). Configuring it with ```cmake . -DSINGLE_ARG=OFF -DDEFAULT_CONSTRUCTIBLE=OFF -DVECTOR_2ND_ARG=ON``` will result in a segfault when executed (tested on Cori haswell  and Perlmutter CPU). Any other options combination will work.  

## Specifications

  - HPX Version: 1.8.1 (compiled with ```-DHPX_WITH_PARCELPORT_TCP=OFF -DHPX_WITH_PARCELPORT_MPI=ON```)
  - Platform (compiler, OS): 
    - Cori, gcc 11.2.0, cray-mpich 7.7.19 
    - Perlmutter, gcc 11.2.0, cray-mpich 8.1.17

**Comment by hkaiser** [comment] 2022-09-04 19:31
FWIW, I have the problem reproduced. It is not caused by the action being called with two arguments, but by the fact that one of the arguments is non-default constructible. The bug manifests itself in cases where one (some) of the arguments are non-default constructible, while the others are default constructible. I hope to have a fix for this available soon.

**Closed** 2022-09-06 14:08 UTC
Labels: type: defect, category: components
