### ISSUE TITLE
HPX-1.6.0 fails to build on Windows 10

### ISSUE THREAD

**Issue by philipyi** [STEllAR-GROUP/hpx#5270] opened 2021-03-31 16:10 UTC
## Expected Behavior
Successful build using Visual Studio 2019

## Actual Behavior
Build failed with the following errors:

Error	C2182	'abstract declarator': illegal use of type 'void'	1d_stencil_channel (Examples\1D Stencil\1d_stencil_channel\1d_stencil_channel)	C:\Users\phili\Documents\cpp\hpx-1.6.0\libs\core\functional\include\hpx\functional\traits\is_invocable.hpp

Note: error points to line 81 of is_invocable.hpp

## Steps to Reproduce the Problem

Follow all steps in the HPX manual regarding:
How to build HPX under Windows 10 x64 with Visual Studio 2015

## Specifications

  - HPX Version: 1.6.0
  - Platform (compiler, OS): Visual Studio 2019, Windows 10.
  - Setting compiler to use C++14 as well as C++17 makes no difference.

**Comment by hkaiser** [comment] 2021-04-03 19:11
Could you give us the arguments you used when invoking cmake, please?

**Comment by hkaiser** [comment] 2021-04-03 19:14
FWIW, I can build that example just fine using VS 2019 Preview (Version 16.10.0 Preview 1.0)

**Comment by philipyi** [comment] 2021-04-05 01:59
The version of VS I used was 16.9.3

Here is the build log file:
[INSTALL.log](https://github.com/STEllAR-GROUP/hpx/files/6255931/INSTALL.log)

Here is the CMakeCache.txt
[CMakeCache.txt](https://github.com/STEllAR-GROUP/hpx/files/6255681/CMakeCache.txt)

**Comment by philipyi** [comment] 2021-04-05 02:07
Here is the list of errors displayed on the Error List pane during the build:
[BuildErrorList.txt](https://github.com/STEllAR-GROUP/hpx/files/6255959/BuildErrorList.txt)

**Comment by hkaiser** [comment] 2021-04-05 23:29
@philipyi thank you for the additional information. I'm still not able to reproduce your issue. Would you be able to retry using the current master branch, please?

**Comment by philipyi** [comment] 2021-04-07 20:05
@hkaiser - I just built the latest from the git repository with no problems.

**Comment by hkaiser** [comment] 2021-04-07 20:19
> @hkaiser - I just built the latest from the git repository with no problems.

Thanks for investing the time to investigate that! Would it be ok if I closed this issue now? Or would you have to rely on the release and have it fixed retrospectively?

**Comment by philipyi** [comment] 2021-04-07 23:23
@hkaiser , No I don't need it to be fixed retrospectively, thank you. I think you can close the issue.

**Closed** 2021-04-08 00:26 UTC
Labels: compiler: msvc, type: defect
