### ISSUE TITLE
HPX build fails when HPX_WITH_CUDA is enabled

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2689] opened 2017-06-08 20:11 UTC
HPX build fails when HPX_WITH_CUDA is enabled. This is due to the forcing of flag `-std=c++11 ` when CMake variable HPX_WITH_CUDA is set.

**Comment by hkaiser** [comment] 2017-07-11 10:53
This is a duplicate of #2718

**Closed by hkaiser** 2017-07-11 10:53 UTC
Labels: category: core, category: executors, compiler: nvcc, platform: CUDA, tag: duplicate, type: defect
