### ISSUE TITLE
datapar_execution + zip iterator: lambda arguments aren't references

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/hpx#2403] opened 2016-11-22 17:11 UTC
Reopened issue in this repository, as I mistakenly started it in the octotiger repository. For the history of the issue see @https://github.com/STEllAR-GROUP/octotiger/issues/22.

**Comment by hkaiser** [comment] 2016-11-23 17:16
@DavidPfander-UniStuttgart: please verify that things work as expected if the lambda takes a reference (see test added by #2407)

**Comment by DavidPfander-UniStuttgart** [comment] 2016-11-23 18:51
Still not compiling with a reference, see https://gist.github.com/DavidPfander-UniStuttgart/2bde59559f003128c6dcaa1a02cc4501.

**Comment by hkaiser** [comment] 2016-11-24 15:35
The compilation problem is caused by the concept checking. Disabling the concept checking (in particular the `parallel::traits::is_indirect_callable<...>;;value`) makes things compile and run just fine. The solution is related to solving #2402. Specializing `is_indirect_callable` for the datapar execution policies and zip_iterators should prevent this from happening.

**Comment by hkaiser** [comment] 2016-11-26 00:36
This has been fixed by merging #2407

**Closed by hkaiser** 2016-11-26 00:36 UTC
Labels: category: algorithms, type: defect
