### ISSUE TITLE
Not all examples link in the latest HPX master

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5038] opened 2020-10-30 17:17 UTC
## Expected Behavior

All examples should compile 

## Actual Behavior

```
[ 65%] Linking CXX executable ../../../../bin/1d_stencil_4_checkpoint
/usr/bin/ld: ../../../../lib/libhpx.so.1.6.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<hpx::naming::id_type, hpx::naming::gid_type, hpx::traits::detail::component_tag>::set_value_action, hpx::naming::gid_type>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, hpx::naming::gid_type&&)'
/usr/bin/ld: ../../../../lib/libhpx.so.1.6.0: undefined reference to `bool hpx::detail::apply_impl<hpx::lcos::base_lco_with_value<hpx::naming::id_type, hpx::naming::gid_type, hpx::traits::detail::managed_component_tag>::set_value_action, hpx::naming::gid_type>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority, hpx::naming::gid_type&&)'
collect2: error: ld returned 1 exit status
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Compile HPX with examples 

## Specifications

... Please describe your environment

  - HPX Version: master
  - Platform (compiler, OS): not relevant

**Comment by msimberg** [comment] 2020-10-30 18:20
Duplicate of #5035.

**Closed by msimberg** 2020-10-30 18:20 UTC
