### ISSUE TITLE
Parallel algorithms inclusive_scan and exclusive_scan break under different initial values

### ISSUE THREAD

**Issue by dcbdan** [STEllAR-GROUP/hpx#1390] opened 2015-03-02 22:29 UTC
Example: Parallel inclusive_scan under the array {1,2,3,4,5,6} should yield {1,3,6,10,15,21} when init is 0 and {101,103,106,110,115,121} when init is 100. With each chunk_size equal to two, the current parallel implmentation yields {1,3,6,10,15,21} when init is 0 (correct) and {101,103,206,210,315,321} when init is 100 (incorrect).

**Comment by hkaiser** [comment] 2015-03-02 22:46
It looks like if the initial value gets applied once for each partition. @dcbdan Could you add a regression test demonstrating this problem, please?

**Comment by dcbdan** [comment] 2015-03-02 22:59
I was mistaken -- I ran inclusive scan on {1 1 2 2 3 3 4 4} with init 100 and got {201 202 304 306 409 412 516 520} instead of {101 102 104 106 109 112 116 120}. @hkaiser: Will do.

**Comment by hkaiser** [comment] 2015-03-06 15:58
This was fixed by merging #1396

**Comment by sithhell** [comment] 2015-03-10 13:49
The tests still fail occasionally.

**Comment by hkaiser** [comment] 2015-03-10 14:24
Please give us a link to the failures.

**Comment by sithhell** [comment] 2015-03-10 19:08
Hmm. Looks like I have mistaking the shortlength failure with the init failures. I will keep a closer look to buildbot and close this in the meantime again.

**Closed by sithhell** 2015-03-10 19:08 UTC
Labels: category: algorithms, type: defect
