### ISSUE TITLE
Unresolved extern variables and Segmentation fault with CUDA Clang++

### ISSUE THREAD

**Issue by JLTastet** [STEllAR-GROUP/hpx#2837] opened 2017-08-16 10:41 UTC
Given the current build issues with NVCC 8.0 & 9.0, I decided to try my luck and use Clang++ to compile both host and device code.

I configured HPX with the following parameters:
```cmake
cmake -D CMAKE_INSTALL_PREFIX=/home/jtastet/.local/stow/hpx_cuda-clang \
      -D CMAKE_CXX_COMPILER=clang++ \
      -D CMAKE_C_COMPILER=clang \
      -D HPX_WITH_CUDA=ON \
      -D HPX_WITH_CUDA_CLANG=ON \
      -D HPX_WITH_MALLOC=jemalloc \
      -D HPX_WITH_PARCELPORT_MPI=ON \
      -D HPX_WITH_CUDA_ARCH="sm_35;sm_61" \
..
```

Both HPX and all of its dependencies were compiled using Clang trunk (6.0.0, rev. `310909`).

HPX compiled fine, except for the following warnings related to `ptxas`:

```
Scanning dependencies of target benchmark_unique_copy_exe
[ 85%] Building CXX object tests/performance/parallel_algorithms/local/CMakeFiles/benchmark_unique_copy_exe.dir/benchmark_unique_copy.cpp.o
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv120__si_class_type_infoE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv117__class_type_infoE' in whole program compilation, ignoring extern qualifier
...
Scanning dependencies of target 1d_stencil_3_exe
[ 89%] Building CXX object examples/1d_stencil/CMakeFiles/1d_stencil_3_exe.dir/1d_stencil_3.cpp.o
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv117__class_type_infoE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv120__si_class_type_infoE' in whole program compilation, ignoring extern qualifier
```
For reference, the full build log is [here](https://github.com/STEllAR-GROUP/hpx/files/1227774/hpx_cuda_clang_build_log.txt).

I am well aware that the test suite currently fails to compile and run due to issues #2217 and #2690. But here the problem seems to be something else.

To test the resulting HPX build, I wrote a trivial test program:
```cuda
#include <hpx/hpx.hpp>
#include <hpx/hpx_init.hpp>

#include <cuda.h>

#include <vector>
#include <cassert>

__global__ void increment_kernel(int* x)
{
    *x += 1;
}

__host__ int increment(int x_h)
{
    int* x_d = nullptr;
    auto err1 = cudaMalloc(&x_d, sizeof(int));
    assert(err1 == cudaSuccess);
    auto err2 = cudaMemcpy(x_d, &x_h, sizeof(int), cudaMemcpyHostToDevice);
    assert(err2 == cudaSuccess);
    increment_kernel<<<1, 1>>>(x_d);
    auto err3 = cudaMemcpy(&x_h, x_d, sizeof(int), cudaMemcpyDeviceToHost);
    assert(err3 == cudaSuccess);
    return x_h;
}

HPX_PLAIN_ACTION(increment, increment_action);

__host__ int hpx_main(int argc, char* argv[])
{
    auto fut = hpx::async(increment_action(), hpx::find_here(), 0);

    assert(fut.get() == 1);

    return hpx::finalize();
}

__host__ int main(int argc, char* argv[])
{
    return hpx::init(argc, argv);
}
```

Clang emits the same ptxas-related warnings (+ a new one) when compiling it:
```
$ clang++ -o test test.cu --cuda-path=/usr/local/cuda-8.0 `pkg-config --cflags --libs hpx_application` -lhpx_iostreams -D HPX_APPLICATION
ptxas warning : Unresolved extern variable '_ZN3hpx7actions6detail32register_action_invocation_countI16increment_actionE8instanceE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv117__class_type_infoE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv120__si_class_type_infoE' in whole program compilation, ignoring extern qualifier
```

and executing it leads to a segmentation fault:
```
$ ./test
{stack-trace}: 16 frames:
0x7f455b909876  : hpx::util::stack_trace::trace(void**, unsigned long) + 0x6 in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b1d7ecb  : hpx::util::backtrace::backtrace(unsigned long) + 0x5b in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b21f8ee  : hpx::termination_handler(int) + 0x19e in /home/jtastet/.local/lib/libhpx.so.1
0x7f45595d6370  : ??? + 0x7f45595d6370 in /lib64/libpthread.so.0
0x484877        : ??? + 0x484877 in ./test
0x484255        : hpx::components::managed_component<hpx::lcos::detail::promise_lco<int, int>, hpx::components::detail::this_type>::operator new(unsigned long) + 0x35 in ./test
0x480e89        : hpx::lcos::detail::promise_base<int, int, hpx::lcos::detail::promise_data<int> >::init_shared_state() + 0x29 in ./test
0x480d85        : hpx::lcos::detail::promise_base<int, int, hpx::lcos::detail::promise_data<int> >::promise_base() + 0x55 in ./test
0x7f455b6837b0  : hpx::lcos::future<hpx::traits::extract_action<hpx::components::server::runtime_support::load_components_action, void>::local_result_type> hpx::detail::async_impl<hpx::components::s
erver::runtime_support::load_components_action>(hpx::detail::async_policy, hpx::naming::id_type const&) + 0x60 in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b6710ee  : hpx::components::stubs::runtime_support::load_components(hpx::naming::id_type const&) + 0x1e in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b22b17f  : hpx::pre_main(hpx::runtime_mode) + 0x1ef in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b161768  : hpx::runtime_impl<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::pol
icies::lockfree_lifo> >::run_helper(hpx::util::function<int (), false>, int&) + 0x68 in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b1b0c0c  : _ZN3hpx4util6detail10bound_implIMNS_12runtime_implINS_7threads8policies30local_priority_queue_schedulerISt5mutexNS5_13lockfree_fifoES8_NS5_13lockfree_lifoEEEEEFSt4pairINS4_17thread
_state_enumEN5boost13intrusive_ptrINS4_11thread_dataEEEENS0_8functionIFivELb0EEERiENS0_5tupleIJPSB_SL_SM_EEENSP_IJONS4_20thread_state_ex_enumEEEEJLm0ELm1ELm2EEEENSt9enable_ifIXsr6detail14is_simple_b
indIT0_EE5valueENS1_19invoke_bound_resultIT_SW_T1_E4typeEE4typeERSY_RSW_OSZ_NS1_6pack_cImJXspT2_EEEE + 0x6c in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b1b0b8e  : std::pair<hpx::threads::thread_state_enum, boost::intrusive_ptr<hpx::threads::thread_data> > hpx::util::detail::callable_vtable<std::pair<hpx::threads::thread_state_enum, boost::in
trusive_ptr<hpx::threads::thread_data> > (hpx::threads::thread_state_ex_enum)>::_invoke<hpx::util::detail::bound<std::pair<hpx::threads::thread_state_enum, boost::intrusive_ptr<hpx::threads::thread_
data> > (hpx::runtime_impl<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lo
ckfree_lifo> >::*(hpx::runtime_impl<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::pol
icies::lockfree_lifo> >*&&, hpx::util::function<int (), false> const&, std::reference_wrapper<int>&&))(hpx::util::function<int (), false>, int&)> >(void**, hpx::threads::thread_state_ex_enum&&) + 0x
1e in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b713132  : hpx::threads::coroutines::detail::coroutine_impl::operator()() + 0xc2 in /home/jtastet/.local/lib/libhpx.so.1
0x7f455b19d9d6  : void hpx::threads::coroutines::detail::lx::trampoline<hpx::threads::coroutines::detail::coroutine_impl>(hpx::threads::coroutines::detail::coroutine_impl*) + 0x6 in /home/jtastet/.l
ocal/lib/libhpx.so.1
{what}: Segmentation fault
{config}:
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_AWAIT=OFF
  HPX_WITH_CUDA=ON
  HPX_WITH_CXX14_RETURN_TYPE_DEDUCTION=TRUE
  HPX_WITH_DEPRECATION_WARNINGS=ON
  HPX_WITH_EXECUTION_POLICY_COMPATIBILITY=ON
  HPX_WITH_EXECUTOR_COMPATIBILITY=ON
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_HWLOC=ON
  HPX_WITH_INCLUSIVE_SCAN_COMPATIBILITY=ON
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOCAL_DATAFLOW_COMPATIBILITY=ON
  HPX_WITH_LOGGING=ON
  HPX_WITH_MORE_THAN_64_THREADS=(
  HPX_WITH_NATIVE_TLS=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=ON
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
  HPX_WITH_PARCELPORT_TCP=ON
  HPX_WITH_PARCELPORT_VERBS=OFF
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_SWAP_CONTEXT_EMULATION=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=ON
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TRANSFORM_REDUCE_COMPATIBILITY=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_UNWRAPPED_COMPATIBILITY=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=jemalloc
  HPX_PREFIX (configured)=/home/jtastet/.local/stow/hpx_cuda-clang
  HPX_PREFIX=/home/jtastet/.local
{version}: V1.1.0 (AGAS: V3.0), Git: d55dc1b220
{boost}: V1.64.0
{build-type}: release
{date}: Aug 16 2017 10:54:00
{platform}: linux
{compiler}: Clang version 6.0.0 (trunk 310909)
{stdlib}: GNU libstdc++ version 20150623
Aborted (core dumped)
```
I do not know for certain if the segmentation fault is related to the warnings issued by Clang, but it seems to be the most likely culprit.

I am willing to help regarding all the CUDA-related issues, especially the ones which I am reporting, since I can easily reproduce them and investigate them further. However my knowledge of the HPX internals is still rather limited, so I might be missing some obvious aspects. So if you have any idea about what might be causing the issue, I would also greatly appreciate it.

Regarding the present issue, I will try to find a minimal example (without HPX) which produces similar warnings as well as a segmentation fault.

**Comment by hkaiser** [comment] 2017-08-16 12:58
@Element-126 we definitely need somebody starting to take care of supporting CUDA in HPX. I very much appreciate your offer. 

As a start, we could reinstate the old `hpx::util::unwrapped` (from [here](https://github.com/STEllAR-GROUP/hpx/blob/1390354369f4d503974ee90cdce8901edb59df5e/hpx/util/unwrapped.hpp)) just for the case when CUDA is enabled (`#if defined(HPX_HAVE_CUDA)`). That should give us a stop-gap measure to not block CUDA altogether until the new unwrapped is fixed. Would you feel comfortable to attempt preparing a PR for this? 

As for the linker warnings and the segmentation fault: I don't know what's causing this. Let's roll back unwrapped and try again. Things used to work before...

**Comment by Element-126** [comment] 2017-08-16 13:51
@hkaiser If #2825 (to which you seem to be referring) only affects NVCC 8 & 9 in C++11 mode, and if we manage to get HPX to build with NVCC 9 / Clang++ in C++14 mode, then we might as well drop the C++11 support altogether for NVCC.

Since it has been broken for ages anyway, I doubt it will bother anyone, and it would avoid duplicating the whole code base just to support a non-conformant compiler.

Regarding the present issue, I will try to get HPX to build under NVCC 9 (C++14). If it works, then it means that the problem is specific to Clang or to the build procedure associated with it (relocatable device code not properly enabled ?). In the latter case, we should be able to fix it.

**Comment by hkaiser** [comment] 2017-08-16 16:26
@Element-126 I agree, we don't have a reason to support C++11 mode if C++14 mode works.

**Comment by Element-126** [comment] 2017-08-16 18:04
Unfortunately, it seems that #2825 is still present with NVCC 9 in C++14 mode, as checked by @gentryx.

If we manage to isolate the non-conforming behavior, it might be worth reporting it to Nvidia while CUDA 9 is still in RC. It probably won't change anything for this release, but at least it will be in their bug tracker.

**Comment by Element-126** [comment] 2017-08-17 15:00
Ok, this is definitely an issue in Clang, which lacks support for relocatable device code. [A bug](https://bugs.llvm.org/show_bug.cgi?id=26343) has already been filed one year and a half ago in their bug tracker, and it seems to be a WONTFIX.

I will now try to compile mixed HPX/CUDA code _without_ `-D HPX_WITH_CUDA=ON`, and see if it works better.

**Comment by Element-126** [comment] 2017-08-22 07:35
I recompiled HPX with the latest sources and tried without the `-D HPX_WITH_CUDA_*=ON`, and I get the exact same error as before.

I will see if I can fix it, but I cannot promise anything.

**Comment by Element-126** [comment] 2017-08-22 07:59
For reference, I tried to compile the above snippet using:
```
$ clang++ -o test_clang test.cu --cuda-path=/usr/local/cuda-8.0 `pkg-config --cflags --libs hpx_application` -lhpx_iostreams -I/usr/local/cuda-8.0/include -L/usr/local/cuda-8.0/lib64 -lcudart_static -ldl -lrt -pthread -D HPX_APPLICATION
ptxas warning : Unresolved extern variable '_ZN3hpx7actions6detail32register_action_invocation_countI16increment_actionE8instanceE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv120__si_class_type_infoE' in whole program compilation, ignoring extern qualifier
ptxas warning : Unresolved extern variable '_ZTVN10__cxxabiv117__class_type_infoE' in whole program compilation, ignoring extern qualifier
```
and the missing symbols respectively demangle to (using [this tool](https://github.com/eklitzke/demangle)):
```
hpx::actions::detail::register_action_invocation_count<increment_action>::instance
vtable for __cxxabiv1::__si_class_type_info
vtable for __cxxabiv1::__class_type_info
```

**Comment by Element-126** [comment] 2017-08-22 10:15
I managed to produce a minimal example which gives a similar warning, but not the associated segfault :-(
```cuda
#include <cuda.h>
#include <cassert>

struct MyStruct
{
    __host__ __device__ MyStruct() { static_member = 1; }
    static int static_member;
};

__device__ void test()
{
    MyStruct my_struct;
    int x = MyStruct::static_member;
    assert(x == 1);
}

__global__ void kernel()
{
    test();
}

__host__ int main(int argc, char* argv[])
{
    kernel<<<1, 1>>>();
    return 0;
}
```
```
$ clang++ -std=c++17 -o test test.cu --cuda-path=/usr/local/cuda-8.0 \
    -I/usr/local/cuda-8.0/include -L/usr/local/cuda-8.0/lib64 \
    -lcudart_static -ldl -lrt -pthread
ptxas warning : Unresolved extern variable '_ZN8MyStruct13static_memberE' in whole program compilation, ignoring extern qualifier
```
```
$ ./test
$ echo $?
0
```

So this seems to be a problem with static variables in device code, which are used in `register_action_invocation_count` as well as for the vtable. Now I have virtually no idea how these static variables end up being used in device code.

Regarding `register_action_invocation_count<Action>::instance`, it is only defined on the host side, but Clang allows calling `__host__` code from the device side if no corresponding `__device__` overload is found.

**Comment by hkaiser** [comment] 2017-08-22 10:49
I think we can safely guard (hide) those variables for the device code. Even if the functions get instantiated, the code will never be executed...

**Comment by Element-126** [comment] 2017-08-22 10:55
This sounds reasonable to do for `register_action_invocation_count<Action>::instance`. However what worries me most here is the issue with the vtable. I don't know if it means that we cannot issue virtual function calls from the device side.

**Comment by sithhell** [comment] 2017-08-22 11:23
That specific static is meaningless in device code. So we should `#ifdef` it out. Virtual function calls should be possible though.
The biggest issue right now is that there is a lot of code being processed by the CUDA compiler which doesn't really work in device code and emits tons of warnings.

**Comment by sithhell** [comment] 2017-08-22 11:25
The vtable warning is troublesome though, but not a lot we can do. This looks like a clang issue. Could also be code where we call some RTTI functions. No idea if we can just ignore the warning for now.

**Comment by Element-126** [comment] 2017-08-22 12:13
Yes, we could try to `#ifdef` out the static member (as well as all the code depending on it...) and see if the segfault is still there.

If I manage to make a minimal example reproducing the vtable warnings and the segfault, I will let you know here.

I still don't get why this static is being processed as device code at all, since everything is `__host__` by default, the kernel does not call any HPX-related functions, and only an `__host__` function is wrapped into an action.

**Comment by sithhell** [comment] 2017-09-06 07:56
For now, I can't reproduce that problem when using clang + cuda. I am also using libc++ as the C++ standard library. From my experience, this is generally advisable. There also has been various fixes on the [cuda_clang](https://github.com/STEllAR-GROUP/hpx/tree/cuda_clang) branch.

**Closed** 2019-08-03 08:31 UTC
Labels: platform: CUDA, tag: wontfix, type: defect
