### ISSUE TITLE
make install fails due to a non-existing .so file

### ISSUE THREAD

**Issue by rahulgayatri23** [STEllAR-GROUP/hpx#2543] opened 2017-03-17 23:43 UTC
Hi, 
 I am from lawrence berkeley and am trying to install hpx on a linux machine here.
In the final make install step, at the end the operation fails with the following error

> Install configuration: "Release"
> CMake Error at cmake_install.cmake:48 (FILE):
>   file INSTALL cannot find
>   "/my_path/build/lib/hpx/libhpx_parcel_coalescing.so.1.0.0".

I checked and the file libhpx_parcel_coalescing.so.1.0.0 does not exist, only libhpx_parcel_coalescing.so.1 is present. 

I have not got any error before that step. The make execution was fine. 

Can someone help me solve this issue.
Thanks. 

Regards,
Rahul.

**Comment by hkaiser** [comment] 2017-03-18 00:17
This has been reported before but we've never been able to reproduce this (see for instance #2515). Can you give us more information on how to reproduce this?

**Comment by rahulgayatri23** [comment] 2017-03-20 03:56
Hi, 
I followed the instructions given in the README. 
I will list out the instructions and their order, hopefully you may be able to reproduce the error

cd /path-to-dir/hpx/_build

cmake -DBOOST_ROOT=/path-to-boost/version 1.62/intel/haswell/ -DHWLOCK_ROOT=/path-to-hwlock/version 1.11.4/hsw HPX_WITH_MALLOC=tcmalloc -DTCMALLOC_INCLUDE_DIR=/path-to-tcmalloc/gperftools/_build/include -DTC_MALLOC_LIBRARY=/.../gperftools/_build/lib -DCMAKE_INSTALL_PREFIX=$PWD .. 

make -j

make install 

These are the exact set of statemements followed by me... 
hopefully you may be able to reproduce the error. 
Else any suggestion to solve this problem will also be great. 

Its a linux 64 bit machine. So let me know if you were able to reproduce the error.

**Comment by hkaiser** [comment] 2017-04-29 15:48
I'll go ahead and close this as it is a duplicate of #1529

**Closed by hkaiser** 2017-04-29 15:48 UTC
Labels: category: CMake, type: defect
