### ISSUE TITLE
Setting INTERFACE_COMPILE_OPTIONS for hpx_init in CMake taints Fortran_FLAGS

### ISSUE THREAD

**Issue by gentryx** [STEllAR-GROUP/hpx#1973] opened 2016-01-30 21:38 UTC
When one adds hpx_init via target_link_libraries() to a target which includes a Fortran source file then compilation of  the Fortran source will fail because "-std=c++14" is added to the Fortran compiler flags.

**Comment by sithhell** [comment] 2016-01-31 08:52
Am 30.01.2016 10:38 nachm. schrieb "Andreas Schäfer" <
notifications@github.com>:
>
> When one adds hpx_init via target_link_libraries() to a target which
includes a Fortran source file then compilation of the Fortran source will
fail because "-std=c++14" is added to the Fortran compiler flags.

Why do you need to link Fortran sources against libhpx_init/libhpx?

**Comment by sithhell** [comment] 2016-01-31 09:15
Could you post the target property LINKER_LANGUAGE for your library target
please? We might be able to do something there...
Am 31.01.2016 9:52 vorm. schrieb "Thomas Heller" <thom.heller@gmail.com>:

**Comment by gentryx** [comment] 2016-02-08 18:41
- I have an executable where the C++ code needs to link against both, HPX and a Fortran kernel
- the LINKER_LANGUAGE property of the executable's CMake target is undefined
- I only get this error with gfortran 4.8.5. gfortran 4.9.3 succeeds (throws a warning instead of an error).
- Since I now have a workaround, you could close this ticket. I still fell it's a bug that ought to be fixed.

**Comment by hkaiser** [comment] 2016-10-23 15:40
@gentryx How would you propose to fix this issue? Could you create a small reproducing use case for us to try, please?

**Comment by hkaiser** [comment] 2017-03-21 18:06
I'll go ahead and close this. Please feel free to reopen if the issue starts blocking you again.

**Closed by hkaiser** 2017-03-21 18:06 UTC
Labels: category: CMake, type: defect
