### ISSUE TITLE
HPX MPI Future failed

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/hpx#4813] opened 2020-07-08 19:28 UTC
## Expected Behavior

Compiled successfully. 

## Actual Behavior

```
In file included from /users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:9:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:53:51: error: 'MPI_Request' has not been declared
             future_data(init_no_addref no_addref, MPI_Request request)
                                                   ^~~~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:66:13: error: 'MPI_Request' does not name a type; did you mean 'MPIO_Request'?
             MPI_Request request_;
             ^~~~~~~~~~~
             MPIO_Request
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp: In constructor 'hpx::mpi::experimental::detail::future_data::future_data(hpx::mpi::experimental::detail::future_data::init_no_addref, int)':
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:55:17: error: class 'hpx::mpi::experimental::detail::future_data' does not have any field named 'request_'
               , request_(request)
                 ^~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp: At global scope:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:94:27: error: 'MPI_Errhandler' does not name a type; did you mean 'MPI_Errhandler_c2f'?
         HPX_EXPORT extern MPI_Errhandler hpx_mpi_errhandler;
                           ^~~~~~~~~~~~~~
                           MPI_Errhandler_c2f
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:41: error: variable or field 'hpx_MPI_Handler' declared void
         HPX_EXPORT void hpx_MPI_Handler(MPI_Comm*, int* errorcode, ...);
                                         ^~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:41: error: 'MPI_Comm' was not declared in this scope
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:41: note: suggested alternative: 'MPI_CHAR'
         HPX_EXPORT void hpx_MPI_Handler(MPI_Comm*, int* errorcode, ...);
                                         ^~~~~~~~
                                         MPI_CHAR
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:50: error: expected primary-expression before ',' token
         HPX_EXPORT void hpx_MPI_Handler(MPI_Comm*, int* errorcode, ...);
                                                  ^
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:52: error: expected primary-expression before 'int'
         HPX_EXPORT void hpx_MPI_Handler(MPI_Comm*, int* errorcode, ...);
                                                    ^~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:97:68: error: expected primary-expression before '...' token
         HPX_EXPORT void hpx_MPI_Handler(MPI_Comm*, int* errorcode, ...);
                                                                    ^~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:105:32: error: 'MPI_Request' was not declared in this scope
         HPX_EXPORT std::vector<MPI_Request>& get_active_requests();
                                ^~~~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:105:32: note: suggested alternative: 'MPIO_Request'
         HPX_EXPORT std::vector<MPI_Request>& get_active_requests();
                                ^~~~~~~~~~~
                                MPIO_Request
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:105:43: error: template argument 1 is invalid
         HPX_EXPORT std::vector<MPI_Request>& get_active_requests();
                                           ^
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:105:43: error: template argument 2 is invalid
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:135:45: error: 'MPI_Request' was not declared in this scope
     HPX_EXPORT hpx::future<void> get_future(MPI_Request request);
                                             ^~~~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:135:45: note: suggested alternative: 'MPIO_Request'
     HPX_EXPORT hpx::future<void> get_future(MPI_Request request);
                                             ^~~~~~~~~~~
                                             MPIO_Request
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp: In function 'hpx::lcos::future<int> hpx::mpi::experimental::detail::async(F, Ts&& ...)':
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:149:60: error: 'struct hpx::mpi::experimental::detail::future_data' has no member named 'request_'; did you mean 'reset'?
             int result = f(std::forward<Ts>(ts)..., &data->request_);
                                                            ^~~~~~~~
                                                            reset
In file included from /opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpi.h:2237,
                 from /users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:21:
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual void MPI::Datatype::Set_attr(int, const void*)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:342:90: warning: cast from type 'const void*' to type 'void*' casts away qualifiers [-Wcast-qual]
         MPIX_CALLWORLD( MPI_Type_set_attr( (MPI_Datatype) the_real_datatype, v2, (void *)v3 ));
                                                                                          ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:92:23: note: in definition of macro 'MPIX_CALLWORLD'
     { int err ; err = fnc ; if (err) { throw Exception(err); }}
                       ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual MPI::Group MPI::Group::Range_excl(int, const int (*)[3]) const':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:640:92: warning: cast from type 'const int (*)[3]' to type 'int (*)[3]' casts away qualifiers [-Wcast-qual]
         MPIX_CALLWORLD( MPI_Group_range_excl( (MPI_Group) the_real_group, v2, (int  (*)[3])v3, &(v4.the_real_group) ));
                                                                                            ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:92:23: note: in definition of macro 'MPIX_CALLWORLD'
     { int err ; err = fnc ; if (err) { throw Exception(err); }}
                       ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual MPI::Group MPI::Group::Range_incl(int, const int (*)[3]) const':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:646:92: warning: cast from type 'const int (*)[3]' to type 'int (*)[3]' casts away qualifiers [-Wcast-qual]
         MPIX_CALLWORLD( MPI_Group_range_incl( (MPI_Group) the_real_group, v2, (int  (*)[3])v3, &(v4.the_real_group) ));
                                                                                            ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:92:23: note: in definition of macro 'MPIX_CALLWORLD'
     { int err ; err = fnc ; if (err) { throw Exception(err); }}
                       ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual void MPI::Request::Cancel() const':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1094:54: warning: cast from type 'const MPI_Request*' {aka 'const int*'} to type 'MPI_Request*' {aka 'int*'} casts away qualifiers [-Wcast-qual]
         MPIX_CALLWORLD( MPI_Cancel( (MPI_Request *) &the_real_request ));
                                                      ^~~~~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:92:23: note: in definition of macro 'MPIX_CALLWORLD'
     { int err ; err = fnc ; if (err) { throw Exception(err); }}
                       ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual void MPI::Comm::Set_attr(int, const void*)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1419:86: warning: cast from type 'const void*' to type 'void*' casts away qualifiers [-Wcast-qual]
         MPIX_CALLREF( this, MPI_Comm_set_attr( (MPI_Comm) the_real_comm, v2, (void *)v3 ));
                                                                                      ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'MPI::Intercomm MPI::Intracomm::Spawn(const char*, const char**, int, const MPI::Info&, int) const':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1697:49: warning: cast from type 'const char*' to type 'char*' casts away qualifiers [-Wcast-qual]
     MPIX_CALLREF( this, MPI_Comm_spawn( (char *)command,
                                                 ^~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1698:26: warning: cast from type 'const char**' to type 'char**' casts away qualifiers [-Wcast-qual]
                 (char **)argv,
                          ^~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'MPI::Intercomm MPI::Intracomm::Spawn(const char*, const char**, int, const MPI::Info&, int, int*) const':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1705:49: warning: cast from type 'const char*' to type 'char*' casts away qualifiers [-Wcast-qual]
     MPIX_CALLREF( this, MPI_Comm_spawn( (char *)command,
                                                 ^~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1706:26: warning: cast from type 'const char**' to type 'char**' casts away qualifiers [-Wcast-qual]
                 (char **)argv,
                          ^~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'MPI::Intercomm MPI::Intracomm::Spawn_multiple(int, const char**, const char***, const int*, const MPI::Info*, int)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1719:29: warning: cast from type 'const char**' to type 'char**' casts away qualifiers [-Wcast-qual]
                    (char **)array_of_commands,
                             ^~~~~~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1720:30: warning: cast from type 'const char***' to type 'char***' casts away qualifiers [-Wcast-qual]
                    (char ***)array_of_argv, (int *)array_of_maxprocs,
                              ^~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1720:52: warning: cast from type 'const int*' to type 'int*' casts away qualifiers [-Wcast-qual]
                    (char ***)array_of_argv, (int *)array_of_maxprocs,
                                                    ^~~~~~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'MPI::Intercomm MPI::Intracomm::Spawn_multiple(int, const char**, const char***, const int*, const MPI::Info*, int, int*)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1734:29: warning: cast from type 'const char**' to type 'char**' casts away qualifiers [-Wcast-qual]
                    (char **)array_of_commands,
                             ^~~~~~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1735:30: warning: cast from type 'const char***' to type 'char***' casts away qualifiers [-Wcast-qual]
                    (char ***)array_of_argv, (int *)array_of_maxprocs,
                              ^~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1735:52: warning: cast from type 'const int*' to type 'int*' casts away qualifiers [-Wcast-qual]
                    (char ***)array_of_argv, (int *)array_of_maxprocs,
                                                    ^~~~~~~~~~~~~~~~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In member function 'virtual void MPI::Win::Set_attr(int, const void*)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1858:83: warning: cast from type 'const void*' to type 'void*' casts away qualifiers [-Wcast-qual]
         MPIX_CALLREF( this, MPI_Win_set_attr( (MPI_Win) the_real_win, v2, (void *)v3 ));
                                                                                   ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:85:17: note: in definition of macro 'MPIX_CALLREF'
     { int err = fnc; if (err) { (_objptr)->Call_errhandler( err ); }}
                 ^~~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h: In static member function 'static MPI::Win MPI::Win::Create(const void*, MPI::Aint, int, const MPI::Info&, const MPI::Intracomm&)':
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:1879:51: warning: cast from type 'const void*' to type 'void*' casts away qualifiers [-Wcast-qual]
         MPIX_CALLOBJ( v5, MPI_Win_create( (void *)v1, v2, v3, (MPI_Info)(v4.the_real_info), (MPI_Comm)(v5.the_real_comm), &(v6.the_real_win) ));
                                                   ^~
/opt/cray/pe/mpt/7.7.10/gni/mpich-gnu/8.2/include/mpicxx.h:87:17: note: in definition of macro 'MPIX_CALLOBJ'
     { int err = fnc; if (err) { (_obj).Call_errhandler( err ); }}
                 ^~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp: At global scope:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:74:35: error: ambiguating new declaration of 'std::vector<int>& hpx::mpi::experimental::detail::get_active_requests()'
         std::vector<MPI_Request>& get_active_requests()
                                   ^~~~~~~~~~~~~~~~~~~
In file included from /users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:9:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:105:46: note: old declaration 'int& hpx::mpi::experimental::detail::get_active_requests()'
         HPX_EXPORT std::vector<MPI_Request>& get_active_requests();
                                              ^~~~~~~~~~~~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp: In function 'void hpx::mpi::experimental::detail::add_to_request_queue(hpx::mpi::experimental::detail::future_data_ptr)':
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:104:52: error: 'struct hpx::mpi::experimental::detail::future_data' has no member named 'request_'; did you mean 'reset'?
                     "request", debug::hex<8>(data->request_), "active futures",
                                                    ^~~~~~~~
                                                    reset
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp: In function 'void hpx::mpi::experimental::detail::add_to_request_list(hpx::mpi::experimental::detail::future_data_ptr)':
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:115:35: error: request for member 'push_back' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
             get_active_requests().push_back(data->request_);
                                   ^~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:115:51: error: 'struct hpx::mpi::experimental::detail::future_data' has no member named 'request_'; did you mean 'reset'?
             get_active_requests().push_back(data->request_);
                                                   ^~~~~~~~
                                                   reset
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:121:65: error: request for member 'data' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                     "req_ptr", debug::ptr(get_active_requests().data()));
                                                                 ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:124:52: error: 'struct hpx::mpi::experimental::detail::future_data' has no member named 'request_'; did you mean 'reset'?
                     "request", debug::hex<8>(data->request_), "list size",
                                                    ^~~~~~~~
                                                    reset
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp: At global scope:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:131:53: error: 'hpx::lcos::future<void> hpx::mpi::experimental::get_future(MPI_Request)' redeclared as different kind of symbol
     hpx::future<void> get_future(MPI_Request request)
                                                     ^
In file included from /users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:9:
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/include/hpx/async_mpi/mpi_future.hpp:135:34: note: previous declaration 'hpx::lcos::future<void> hpx::mpi::experimental::get_future'
     HPX_EXPORT hpx::future<void> get_future(MPI_Request request);
                                  ^~~~~~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp: In function 'void hpx::mpi::experimental::poll()':
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:179:64: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                     debug::dec<>(detail::get_active_requests().size()),
                                                                ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:193:60: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 debug::dec<>(detail::get_active_requests().size()), "futures",
                                                            ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:205:59: error: request for member 'empty' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
         bool keep_trying = !detail::get_active_requests().empty();
                                                           ^~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:213:64: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 static_cast<int>(detail::get_active_requests().size()),
                                                                ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:214:49: error: invalid types 'int[int]' for array subscript
                 &detail::get_active_requests()[0], &index, &flag, &status);
                                                 ^
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:229:80: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                         "requests", debug::dec<>(detail::get_active_requests().size()),
                                                                                ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:241:73: error: invalid types 'int[std::size_t {aka long unsigned int}]' for array subscript
                         detail::get_active_requests()[std::size_t(index)];
                                                                         ^
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:258:69: error: invalid types 'int[std::size_t {aka long unsigned int}]' for array subscript
                     detail::get_active_requests()[std::size_t(index)] =
                                                                     ^
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:290:58: error: request for member 'begin' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 std::count(detail::get_active_requests().begin(),
                                                          ^~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:291:51: error: request for member 'end' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                     detail::get_active_requests().end(), MPI_REQUEST_NULL);
                                                   ^~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:293:55: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
             if (nulls > detail::get_active_requests().size() / 4)
                                                       ^~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:297:71: error: request for member 'begin' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 auto end1 = std::remove(detail::get_active_requests().begin(),
                                                                       ^~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:298:51: error: request for member 'end' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                     detail::get_active_requests().end(), MPI_REQUEST_NULL);
                                                   ^~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:299:47: error: request for member 'resize' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 detail::get_active_requests().resize(
                                               ^~~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:300:65: error: request for member 'begin' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                     std::distance(detail::get_active_requests().begin(), end1));
                                                                 ^~~~~
/users/wweile/dev/src/hpx_mpi_async/hpx/libs/async_mpi/src/mpi_future.cpp:308:51: error: request for member 'size' in 'hpx::mpi::experimental::detail::get_active_requests()', which is of non-class type 'int'
                 if (detail::get_active_requests().size() !=
                                                   ^~~~
make[2]: *** [libs/async_mpi/CMakeFiles/hpx_async_mpi.dir/build.make:83: libs/async_mpi/CMakeFiles/hpx_async_mpi.dir/src/mpi_future.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9519: libs/async_mpi/CMakeFiles/hpx_async_mpi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.
```
-DHPX_MPI_WITH_FUTURES=ON
-DHPX_WITH_NETWORKING=OFF
-DHPX_WITH_CXX17=ON
```   

## Specifications

... Please describe your environment

  - HPX Version: 57f2f7671b982ebd3a6f7f38a25f72ffba3aa6d2
  - Platform (compiler, OS): Piz Daint
  - Modules:
```
MPI_version=7.7.10
module purge
module unload PrgEnv-cray
module load   PrgEnv-gnu
module unload gcc
module load   gcc/8.1.0
module load   daint-gpu
module unload cray-libsci
module unload intel
module unload cray-mpich
module load   cray-mpich/$MPI_version

export  CC=/opt/cray/pe/craype/default/bin/cc
export CXX=/opt/cray/pe/craype/default/bin/CC

```

**Comment by hkaiser** [comment] 2020-07-09 14:29
Is this a duplicate of #4752?

**Comment by weilewei** [comment] 2020-07-09 14:31
> Is this a duplicate of #4752?

Seems yes, but I thought it was fixed then re-occurred again...

**Comment by hkaiser** [comment] 2020-07-09 16:49
I'll close it as a duplicate, then.

**Closed by hkaiser** 2020-07-09 16:49 UTC
Labels: category: mpi
