### ISSUE TITLE
Cannot construct component with large vector on a remote locality

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/hpx#2334] opened 2016-09-16 17:43 UTC
I created a component with a data member that has a size 512mb. The component is created on the first remote locality (therefore the code example requires 2 localities). Running the example leads to two different errors, depending on whether a debug or a release build of HPX is used (see below). Now, if the matrix size is decreased (set N to 4096), everything seems to be ok.

Bug in the example or problem with HPX?

```
#include <hpx/hpx_init.hpp>
#include <hpx/include/util.hpp>
#include <hpx/include/components.hpp>

struct matrix_multiply_multiplier: hpx::components::component_base<
  matrix_multiply_multiplier> {
  size_t N;
  std::vector<double> A;

  // why does this get called?
  matrix_multiply_multiplier() :
    N(0) {}

  matrix_multiply_multiplier(size_t N, const std::vector<double> &A_
			     ) :
    N(N), A(A_) {}


};

HPX_REGISTER_COMPONENT(hpx::components::component<matrix_multiply_multiplier>,
		       matrix_multiply_multiplier);

int hpx_main() {

  // works on my computer for N = 4096
  size_t N = 8192;
  std::vector<double> A(N * N);

  std::vector<hpx::id_type> remote_ids = hpx::find_remote_localities();
  
  hpx::components::client<matrix_multiply_multiplier> comp = 
     hpx::new_<matrix_multiply_multiplier>(remote_ids[0], N, A);

  return hpx::finalize();
}

int main(int argc, char **argv) {
  return hpx::init(argc, argv);
}
```

Output with release build of HPX:
```
pfandedd@dpfanderLSU ~ $ ./large_matrix_release -l2 -0
tcmalloc: large alloc 1073750016 bytes == 0x6172c000 @ 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  null thread id encountered: HPX(null_thread_id)
Aborted
```
Important: depending on debug or release, the error occurs on a different locality!

Output with debug build of HPX:
```
pfandedd@dpfanderLSU ~ $ ./large_matrix_debug -l2 -1
{stack-trace}: 39 frames:
0x7f6eea13edd7  : ??? + 0x7f6eea13edd7 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea13ef24  : ??? + 0x7f6eea13ef24 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea1344c6  : hpx::termination_handler(int) + 0x19b in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6ee93fb330  : ??? + 0x7f6ee93fb330 in /lib/x86_64-linux-gnu/libpthread.so.0
0x7f6eea790d03  : hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::get_state() const + 0x37 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea711f78  : hpx::threads::threadmanager_impl<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::status() const + 0x1c in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea160b34  : hpx::threads::threadmanager_is(hpx::state) + 0x5b in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea518be8  : hpx::parcelset::parcelport::add_received_parcel(hpx::parcelset::parcel, unsigned long) + 0x6e in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaabbb55  : ??? + 0x7f6eeaabbb55 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaab9116  : ??? + 0x7f6eeaab9116 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaab64b5  : ??? + 0x7f6eeaab64b5 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaab3346  : ??? + 0x7f6eeaab3346 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac1999  : ??? + 0x7f6eeaac1999 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac0327  : ??? + 0x7f6eeaac0327 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaabe790  : ??? + 0x7f6eeaabe790 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaabc832  : ??? + 0x7f6eeaabc832 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaab953f  : ??? + 0x7f6eeaab953f in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaab6b57  : ??? + 0x7f6eeaab6b57 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac37a5  : ??? + 0x7f6eeaac37a5 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac369c  : ??? + 0x7f6eeaac369c in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac3431  : ??? + 0x7f6eeaac3431 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac2f5b  : ??? + 0x7f6eeaac2f5b in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac2760  : ??? + 0x7f6eeaac2760 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eeaac1877  : ??? + 0x7f6eeaac1877 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b5e3a  : ??? + 0x7f6eea9b5e3a in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b67ff  : ??? + 0x7f6eea9b67ff in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b653f  : ??? + 0x7f6eea9b653f in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b6a13  : ??? + 0x7f6eea9b6a13 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b50a5  : hpx::util::io_service_pool::thread_run(unsigned long) + 0xaf in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b9131  : ??? + 0x7f6eea9b9131 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b909d  : ??? + 0x7f6eea9b909d in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b902a  : ??? + 0x7f6eea9b902a in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b8f75  : ??? + 0x7f6eea9b8f75 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b8f09  : ??? + 0x7f6eea9b8f09 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6eea9b8ed0  : ??? + 0x7f6eea9b8ed0 in /home/pfandedd/git/hpx/build_debug/lib/libhpxd.so.1
0x7f6ee9614e7a  : ??? + 0x7f6ee9614e7a in /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
0x7f6ee93f3184  : ??? + 0x7f6ee93f3184 in /lib/x86_64-linux-gnu/libpthread.so.0
0x7f6ee89ac37d  : clone + 0x6d in /lib/x86_64-linux-gnu/libc.so.6
{what}: Floating point exception
{config}:
  HPX_HAVE_NATIVE_TLS=ON
  HPX_HAVE_STACKTRACES=ON
  HPX_HAVE_COMPRESSION_BZIP2=OFF
  HPX_HAVE_COMPRESSION_SNAPPY=OFF
  HPX_HAVE_COMPRESSION_ZLIB=OFF
  HPX_HAVE_PARCEL_COALESCING=ON
  HPX_HAVE_PARCELPORT_TCP=ON
  HPX_HAVE_PARCELPORT_MPI=OFF
  HPX_HAVE_PARCELPORT_IPC=OFF
  HPX_HAVE_PARCELPORT_IBVERBS=OFF
  HPX_HAVE_VERIFY_LOCKS=ON
  HPX_HAVE_HWLOC=ON
  HPX_HAVE_ITTNOTIFY=OFF
  HPX_HAVE_RUN_MAIN_EVERYWHERE=OFF
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PREFIX (configured)=/home/pfandedd/git/hpx/build_debug
  HPX_PREFIX=/home/pfandedd/git/hpx/build_debug
{version}: V1.0.0-trunk (AGAS: V3.0), Git: a36ab93eab
{boost}: V1.55.0
{build-type}: debug
{date}: Sep 13 2016 09:34:29
{platform}: linux
{compiler}: GNU C++ version 4.8.5
{stdlib}: GNU libstdc++ version 20150623
Aborted
```

**Comment by sithhell** [comment] 2016-09-16 18:42
The errors are actually the same and look like a genuine hpx bug.

**Comment by sithhell** [comment] 2016-09-18 17:40
If you have the time, could you please provide a backtrace?

**Comment by hkaiser** [comment] 2016-09-19 01:41
I have added the test from above here: https://github.com/STEllAR-GROUP/hpx/tree/fixing_2334. Unfortunately, the problem is not reproducible for me.

**Comment by sithhell** [comment] 2016-09-19 07:14
Could you please check again with latest master? If my suspicion was correct, this has been fixed with merging #2302. The relevant change should be that one: https://github.com/STEllAR-GROUP/hpx/pull/2302/files#diff-a8aad89cda0f631a36250f65a21f11d2R96

**Comment by DavidPfander-UniStuttgart** [comment] 2016-09-19 17:03
Ok, there is still some issue as my code still crashes for large matrices (N=8192) and it still looks related to the matrix. The error says "broken pipe" (see attachment) which again could be a bug in my program or a bug in HPX. As I haven't created a minimal example and it might be a bug in my code, I leave this issue closed.
[error_large_matrix.txt](https://github.com/STEllAR-GROUP/hpx/files/480630/error_large_matrix.txt)

**Comment by sithhell** [comment] 2016-09-19 17:25
Am 19.09.2016 7:03 nachm. schrieb "DavidPfander-UniStuttgart" <
notifications@github.com>:
>
> Ok, there is still some issue as my code still crashes for large matrices
(N=8192) and it still looks related to the matrix. The error says "broken
pipe" (see attachment) which again could be a bug in my program or a bug in
HPX. As I haven't created a minimal example and it might be a bug in my
code, I leave this issue closed.
> error_large_matrix.txt

Broken pipes are usually errors you get with not closing a socket correctly
(for example piping the output to a pager and kill the pager while the
application still wants to write to stdout/stderr. The TCP parcel port uses
sockets as well

**Comment by DavidPfander-UniStuttgart** [comment] 2016-09-19 18:08
According to you hint in the ste||ar-chat, I tried using commit ba57370, which was the commit before the merge of parcel_optimizations.
Unfortunately, I'm still getting errors with my debug build:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  null thread id encountered: HPX(null_thread_id)
```

**Comment by sithhell** [comment] 2016-09-19 18:57
Sorry I was not being clear. You should use the mentioned commit and manually apply those changes:
https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/threads/detail/thread_pool.cpp#L96-L102

**Comment by DavidPfander-UniStuttgart** [comment] 2016-09-19 20:06
I actually didn't read your instructions carefully enough, sorry for that.

Now with the change applied and HPX recompiled, I unfortunately still get the same error:
```
info: root node is not used for computation
computing on id: {0000000200000000, 0000000000000000}
using pseudodynamic distributed algorithm
tcmalloc: large alloc 1073750016 bytes == 0xa1c8c000 @ 
tcmalloc: large alloc 2147491840 bytes == 0xe1c8e000 @ 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  null thread id encountered: HPX(null_thread_id)
```

**Comment by DavidPfander-UniStuttgart** [comment] 2016-09-24 21:44
After some some quite extensive testing, it turned out that my error is again related to creating a component with a large memory footprint.

I had to add
```
  comp.get_id();
```
and I had to increase the size of the matrix a from N=8192 to N=16384 (leads to a 2GB matrix). I suspect that this is related to the total bytes, because if I add a second matrix and both matrices are 8192x8192, the problem also appears.

If I slightly modify my example and run it only on a single locality, the problem also disappears.

The complete example is appended (the txt is a cpp, the binary has to be run with 2 localities). Additionally, I appended the console log for a debug build of the example.

[large_matrix.txt](https://github.com/STEllAR-GROUP/hpx/files/491361/large_matrix.txt)
[error.txt](https://github.com/STEllAR-GROUP/hpx/files/491362/error.txt)

**Comment by hkaiser** [comment] 2016-09-26 00:06
While the error message is misleading, the fact that things for arrays of this size fail is expected. The default maximal inbound message size allowed is currently 1GByte. This value is configurable through the configuration database entry `hpx.parcel.max_message_size=<new_max_message_size>` (for instance using the `-I` command line option).

**Comment by DavidPfander-UniStuttgart** [comment] 2016-09-27 22:31
I'm getting correct results with max_message_size increased. (Although I used --hpx:config <ini-File>, -I wouldn't work.)

**Comment by sithhell** [comment] 2016-10-07 07:40
The regression test covering this issue is showing a failure still. The failure is due to a bug in the termination detection algorithm.

**Closed** 2016-10-09 01:19 UTC
Labels: category: actions, category: components, type: defect
