### ISSUE TITLE
Phylanx fails with latest hpx

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/hpx#3484] opened 2018-10-08 21:13 UTC
## Expected Behavior
Expect Phylanx to compile with latest HPX

## Actual Behavior
Phylanx Fails compilation with the following error listed below.  I can confirm that it works up to the following commit dbbb94662ba0818cc5d6120f52e4a7b330075709 ( Merge pull request #3476 from STEllAR-GROUP/hide_credentials ). It looks to me the changes that were made to CMAKE recently is causing the issue.
The buildbot link for the failing build is here:
http://ktau.nic.uoregon.edu:8020/#/builders/8/builds/215
```
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/assert_condition.cpp.o
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/patterns.cpp: In function ‘std::__cxx11::string phylanx::execution_tree::find_help(const string&)’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/patterns.cpp:68:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 for(int i=0;i<p.size();i++) {
                             ~^~~~~~~~~
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp: In instantiation of ‘std::vector<phylanx::ast::expression> phylanx::execution_tree::compiler::compiler::extract_lambda_arguments(const std::pair<_FIter, _FIter>&, const phylanx::ast::tagged&) [with Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, phylanx::ast::expression> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:314:62:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:201:41: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (count != 0 && count != size-1 &&
                                   ~~~~~~^~~~~~~~~
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp: In instantiation of ‘std::vector<phylanx::ast::expression> phylanx::execution_tree::compiler::compiler::extract_define_arguments(const std::pair<_FIter, _FIter>&, const phylanx::ast::tagged&) [with Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, phylanx::ast::expression> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:336:62:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/compiler/compiler.cpp:160:41: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 if (count != 0 && count != size-1 &&
                                   ~~~~~~^~~~~~~~~
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/base_primitive.cpp.o
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/call_function.cpp.o
[ 12%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/console_output.cpp.o
In file included from /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/ast/parser/expression.cpp:8:0:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp: In instantiation of ‘phylanx::ast::parser::expression_base<Iterator>::expression_base(phylanx::ast::parser::error_handler<Iterator>&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’:
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp:26:62:   required from ‘phylanx::ast::parser::expression<Iterator>::expression(phylanx::ast::parser::error_handler<Iterator>&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]’
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/ast/parser/expression.cpp:13:39:   required from here
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/phylanx/ast/parser/expression_def.hpp:126:28: error: suggest parentheses around comparison in operand of ‘|’ [-Werror=parentheses]
             |   '(' > expr > ')'
                 ~~~~~~~~~~~^~~~~
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/debug_output.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/define_variable.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/enable_tracing.cpp.o
[ 14%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/format_string.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/function.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/lambda.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/node_data_helpers.cpp.o
[ 17%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/primitive_component.cpp.o
[ 19%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/primitive_component_base.cpp.o
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/execution_tree/patterns.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/execution_tree/compiler/compiler.cpp.o] Error 1
/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/src/execution_tree/primitives/base_primitive.cpp:64:21: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
         static char const* const get_primitive_argument_type_name(std::size_t index)
                     ^~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/phylanx_component.dir/ast/parser/expression.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/phylanx_component.dir/all] Error 2
make: *** [all] Error 2
program finished with exit code 2
elapsedTime=80.792626

```

## Steps to Reproduce the Problem
Build Phylanx against latest hpx

## Specifications
  - HPX Version: Master
  - Platform (compiler, OS): Ubuntu 18.04 / gcc 7.3

**Comment by biddisco** [comment] 2018-10-09 06:31
This is very annoying. If I make the flags PRIVATE then they are not inherited by the tests in the HPX project and so we get all the warnings back. If I make them PUBLIC, then all the tests are fine, but they are also exported from the project and trigger errors in phylanx etc.

Fix 1 would be to address the signed comparison problems in phlanx. 
Fix 2 is to rework our cmake and add the flags separately to each target - this is what I was trying to solve by making the changes in the offending commit.

**Comment by biddisco** [comment] 2018-10-09 08:39
I have a solution. Using a generator expression of the kind
```
target_compile_options(hpx PUBLIC $<BUILD_INTERFACE:${_temp_flags}>)
```
The correct compile flags are used by projects in the build tree, so all tests inherit them as expected. However, when exported using `make install` they are not included, so 3rd party projects using an installed HPX do not pick up the flags. However, if you build phylanx and link to the BUILD tree of HPX, then you will get the flags and would have to fix your local project.

If a solution that is god for the INSTALL tree is acceptable, then I will submit a PR with the fix.

**Comment by biddisco** [comment] 2018-10-09 09:18
See #3485

**Comment by hkaiser** [comment] 2018-10-12 17:46
Phylanx using Blaze top of master is still failing if HPX was built using C++17 mode. This is enforced onto Phylanx (see CircleCI for instance here: https://circleci.com/gh/STEllAR-GROUP/phylanx/8813) which is not desired.

**Comment by sithhell** [comment] 2018-10-12 23:09
From the error message, it looks like that certain C++17 features are failing, which means that the flags get passed down incorrectly. GCC 6.2 builds everything fine

**Comment by hkaiser** [comment] 2018-10-13 00:15
@sithhell the issue is triggered by Blaze unconditionally enabling all C++17 features when being compiled with `-std=c++17`. That includes library features that may not even have been added. On CircleCI we use clang V5 which accepts `-std=c++17` but is not 100% conforming (has no implementation of `std::uninitialized_move`, for instance). 

So the problems are a combination of:
- us letting the buildsystem select the C++ mode on CircleCI which results in clang V5 being used with `-std=c++17` (despite the fact that the library is not there yet); we should explicitly enforce C++14 at best
- us unconditionally forcing the C++ compilation mode onto dependent targets (which is questionable)
- and Blaze (top of master) unconditionally enabling all of C++17 when compiled with `-std=c++17`; Blaze should use feature macros or similar instead

**Comment by sithhell** [comment] 2018-10-13 12:38
> @sithhell the issue is triggered by Blaze unconditionally enabling all C++17 features when being compiled with `-std=c++17`. That includes library features that may not even have been added. On CircleCI we use clang V5 which accepts `-std=c++17` but is not 100% conforming (has no implementation of `std::uninitialized_move`, for instance).

Right. It is that commit here: https://bitbucket.org/blaze-lib/blaze/commits/e9fc567e6bcd5ba11fd0611dc2f0863d60b75d2

> 
> So the problems are a combination of:
> 
>     * us letting the buildsystem select the C++ mode on CircleCI which results in clang V5 being used with `-std=c++17` (despite the fact that the library is not there yet); we should explicitly enforce C++14 at best

Sure, we can do that. That's orthogonal to the problem at hand though. Furthermore, I am not very fond of the idea that one project forces the compile flags of the HPX testing system. There'll always be special requirements by some projects, we can not respect them all in our current infrastructure. If Phylanx wants to enforce the C++ mode, that's fine and doable, however not very feasible with the current setup where Phylanx consumes the Docker image we produce.

> 
>     * us unconditionally forcing the C++ compilation mode onto dependent targets (which is questionable)

We always did this and I am not sure there is a way around it here. Can we really guarantee no ABI/API breakage between two standard versions? I have no idea.

Mixing and matching libraries with different flags is a hard problem. In my book, if someone wants to build against a built/installed HPX version, there is no away around that we inherit some build flags down to the consumer (-DHPX_DEBUG, standard level, to name the most important part). This situation changes when you, as the project fully controls the dependencies of the project. In this scenario, there is no doubt, that every library needs to respect the globally set compile flags. That requires far more work. Not only on the HPX side itself.

I think what changed is the order of command line parameters, that is, the C++14 flag is set before the C++17 flag in HPX. This is happening due to a different way of setting the flags (target vs. CMAKE_CXX_FLAGS)

> 
>     * and Blaze (top of master) unconditionally enabling all of C++17 when compiled with `-std=c++17`; Blaze should use feature macros or similar instead

**Comment by hkaiser** [comment] 2018-10-13 13:02
@sithhell so what do you suggest?

**Comment by sithhell** [comment] 2018-10-15 04:57
As a short term solution I am updating the toolchain in our docker images now to have a fully compliant C++17 one. Of course, this only hides the real problem.

For a long term solution, the only real fix to avoid those issues is to fully control the dependencies:

1.  Freeze all versions of the libraries you depend on
2.  Build all libraries you depend on yourself for testing

When having multiple dependencies from different sources coming in, it is almost impossible for all those dependencies to meet the requirements of the downstream project. IMHO, this only partially a HPX issue (forcing the C++ version downwards). With that being said, I am not sure what other issues there'll arise once we freeze the C++ version in HPX to the minimum (C++11) and not export it via our targets. Lot's of other user code will fail to compile that way, i guess (the users that don't explicitly set the C++ version in their CMakeList.txt, for example)

**Comment by sithhell** [comment] 2018-10-15 09:32
See #3491 
Once this is through, there should be a more compliant C++17 environment available to use.

**Comment by chinz07** [comment] 2018-10-17 18:50
I just stumbled across the following blog post: https://foonathan.net/blog/2018/10/17/cmake-warnings.html. If I am not mistaken, this pattern could fix the accidental propagation for both the installed version and the build tree. No flags are propagated and warnings from imported header files are suppressed.

**Comment by sithhell** [comment] 2018-11-06 19:23
is this resolved now?

**Comment by hkaiser** [comment] 2018-11-06 19:37
I think we can close this now, thanks!

**Closed by hkaiser** 2018-11-06 19:37 UTC
Labels: category: CMake, type: defect
