### ISSUE TITLE
First example not working

### ISSUE THREAD

**Issue by andreichalapco** [STEllAR-GROUP/hpx#6295] opened 2023-07-03 09:19 UTC
## Expected Behavior

I just ran the first example on the website:
[example](https://hpx-docs.stellar-group.org/latest/html/quickstart.html#writing-task-based-applications)

and encountered the following debug error (besides others):
```bash
/usr/include/hpx/parallel/algorithms/detail/sample_sort.hpp:282:52: error: no matching function for call to ‘make_iterator_range(hpx::util::counting_iterator<unsigned int, void, void, void>, hpx::util::counting_iterator<unsigned int, void, void, void>)’
  282 |         auto shape = hpx::util::make_iterator_range(
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  283 |             hpx::util::make_counting_iterator(std::uint32_t(0)),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  284 |             hpx::util::make_counting_iterator(nthreads));
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Could you please check if this is due to my compiler or is it a known issue. 

  - Platform (compiler, OS): Fedora, gcc 13.
  - hpx installed via dnf install

**Comment by andreichalapco** [comment] 2023-07-03 13:03
I also noticed that in the `counting_iterator.hpp` <cstdint> is missing. Which is leading to the error intmax_t is not recognize in the std:: namespace. (in the updated repository on master the <csdint> is included)

I basically think the fedora hpx version/binaries are outdated.... and will build the hpx binaries myself.

Is there any solution or can we close this issue?

**Comment by hkaiser** [comment] 2023-07-03 13:37
@andreichalapco Thanks for checking! I think there isn't anything you can do short of #including `cstdint` yourself first. Since the issue is resolved on the master branch I think we can close this.

**Closed by hkaiser** 2023-07-03 13:37 UTC
