### ISSUE TITLE
HPX on Mac OS X with HWLoc 2.0.0 fails to run

### ISSUE THREAD

**Issue by svanzwam** [STEllAR-GROUP/hpx#3221] opened 2018-03-08 22:51 UTC
## Expected Behavior

```
$ ./build/bin/hello_world_exe
hello world from OS-thread 5 on locality 0
hello world from OS-thread 6 on locality 0
hello world from OS-thread 7 on locality 0
hello world from OS-thread 0 on locality 0
hello world from OS-thread 1 on locality 0
hello world from OS-thread 3 on locality 0
hello world from OS-thread 4 on locality 0
hello world from OS-thread 2 on locality 0
```

## Actual Behavior

```
$ ./build/bin/hello_world_exe
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: partitioner::setup_pools: Default pool default has no threads assigned. Please rerun with --hpx:threads=X and check the pool thread assignment
Abort trap: 6
```

## Steps to Reproduce the Problem

  1. OS X 10.13.3 with hwloc 2.0.0 (installed by home-brew)
  1. Build HPX either in Release or Debug version
  1. Run hello_world_exe

```bash
brew install hwloc
mkdir build
cd build

cmake /Users/svanzwam/coding/hpx1.1/repo \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/Users/svanzwam/coding/hpx1.1/install

ninja hello_world_exe
```
## Specifications

  - HPX Version: 1.1
  - Platform (compiler, OS): OS X 10.13.3, compiler:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Missing packages mostly installed through home-brew.

**Comment by msimberg** [comment] 2018-03-09 07:51
If we don't have a way of testing on OS X (I don't) in the short term I suggest we make hwloc < 2.0.0 a requirement for the next release and try to fix it for the next one. Objections? Does someone else have an OS X machine and the time to look into this?

**Comment by AntonBikineev** [comment] 2018-03-09 07:53
@msimberg I'll take a look at this

**Comment by msimberg** [comment] 2018-03-09 07:54
@AntonBikineev Great, thanks!

**Comment by zao** [comment] 2018-03-09 13:40
I can repro this on a VM, please note the different hierarchies for `hwloc2` and `hwloc1` below.
```
Larss-iMac:build-debug-hwloc1 lars$ /Users/lars/stellar/opt/hwloc-1.11.9/bin/hwloc-info
depth 0:        1 Machine (type #1)
 depth 1:       1 NUMANode (type #2)
  depth 2:      1 Package (type #3)
   depth 3:     6 L3Cache (type #4)
    depth 4:    6 L2Cache (type #4)
     depth 5:   6 L1dCache (type #4)
      depth 6:  6 L1iCache (type #4)
       depth 7: 6 Core (type #5)
        depth 8:        6 PU (type #6)
Larss-iMac:build-debug-hwloc1 lars$ /Users/lars/stellar/opt/hwloc-1.11.9/bin/hwloc-ls
Machine (8192MB total) + NUMANode L#0 (P#0 8192MB) + Package L#0
  L3 L#0 (12MB) + L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  L3 L#1 (12MB) + L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  L3 L#2 (12MB) + L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  L3 L#3 (12MB) + L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  L3 L#4 (12MB) + L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
  L3 L#5 (12MB) + L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
Larss-iMac:build-debug-hwloc1 lars$ /Users/lars/stellar/opt/hwloc-2.0.0/bin/hwloc-info
depth 0:           1 Machine (type #0)
 depth 1:          1 Package (type #1)
  depth 2:         6 L3Cache (type #6)
   depth 3:        6 L2Cache (type #5)
    depth 4:       6 L1dCache (type #4)
     depth 5:      6 L1iCache (type #9)
      depth 6:     6 Core (type #2)
       depth 7:    6 PU (type #3)
Special depth -3:  1 NUMANode (type #13)
Larss-iMac:build-debug-hwloc1 lars$ /Users/lars/stellar/opt/hwloc-2.0.0/bin/hwloc-ls
Machine (8192MB total) + Package L#0
  NUMANode L#0 (P#0 8192MB)
  L3 L#0 (12MB) + L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  L3 L#1 (12MB) + L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  L3 L#2 (12MB) + L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  L3 L#3 (12MB) + L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  L3 L#4 (12MB) + L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
  L3 L#5 (12MB) + L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
Larss-iMac:build-debug-hwloc1 lars$
```

**Comment by zao** [comment] 2018-03-09 13:43
Looking at setup_pools, `numa_domains_` is empty at that point, so our hierarchy is probably way off target.
This is similar to the failures I had on DragonFlyBSD where hwloc didn't have enough OS support and thus didn't fit into our strict hierarchy.

**Comment by biddisco** [comment] 2018-03-09 20:05
This is a duplicate of #3181 which was closed in error.

**Comment by AntonBikineev** [comment] 2018-03-09 21:31
@zao Seems like the problem is in the changed hierarchy - numa-nodes now have a special depth, cores are not their children and `hwloc_get_next_child(node_obj, HWLOC_OBJ_CORE, nullptr);` returns 0...

**Closed** 2018-03-18 16:29 UTC
Labels: type: compatibility issue, type: defect
