### ISSUE TITLE
Using 'gmakeN' after 'cmake' produces error in src/CMakeFiles/hpx.dir/runtime/agas/addressing_service.cpp.o

### ISSUE THREAD

**Issue by Rodario** [STEllAR-GROUP/hpx#2814] opened 2017-08-11 13:04 UTC
Hello, currently I cant get beyond gmake -j3 in the steps to setting up hpx. 

My setup:
* OS: Fedora 26
* Compiler: gcc 7.1.1
* Boost library: 1.61.0
* Using TCMalloc

I followed the steps of your fedora [receipe](https://github.com/STEllAR-GROUP/hpx/blob/master/docs/manual/build_system/recipe_fedora.qbk) to get all the required librarys.

After that I used the steps:
* "cmake .." in build folder without extra definitions
* gmake -j3

Than the building reached:
`[  0%] Building CXX object src/CMakeFiles/hpx.dir/runtime/agas/big_boot_barrier.cpp.o`

and I got the following error message:
```
In file included from /usr/local/boost_1_61_0/boost/icl/type_traits/identity_element.hpp:11:0,
                 from /usr/local/boost_1_61_0/boost/icl/type_traits/unit_element.hpp:12,
                 from /usr/local/boost_1_61_0/boost/icl/concept/interval.hpp:17,
                 from /usr/local/boost_1_61_0/boost/icl/closed_interval.hpp:12,
                 from /home/rodri/Desktop/BA/hpx_main/hpx/src/runtime/agas/addressing_service.cpp:48:
/usr/local/boost_1_61_0/boost/icl/type_traits/type_to_string.hpp:56:12: error: partial specialization of ‘struct boost::icl::type_to_string<Unary<Type> >’ after instantiation of ‘struct boost::icl::type_to_string<std::__cxx11::basic_string<char> >’ [-fpermissive]
     struct type_to_string<Unary<Type> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/boost_1_61_0/boost/icl/type_traits/type_to_string.hpp:72:12: error: partial specialization of ‘struct boost::icl::type_to_string<Binary<Type1, Type2> >’ after instantiation of ‘struct boost::icl::type_to_string<std::__cxx11::basic_string<char> >’ [-fpermissive]
     struct type_to_string<Binary<Type1, Type2> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  0%] Building CXX object src/CMakeFiles/hpx.dir/runtime/agas/component_namespace.cpp.o
[  0%] Building CXX object src/CMakeFiles/hpx.dir/runtime/agas/detail/bootstrap_component_namespace.cpp.o
gmake[2]: *** [src/CMakeFiles/hpx.dir/build.make:159: src/CMakeFiles/hpx.dir/runtime/agas/addressing_service.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1819: src/CMakeFiles/hpx.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2`
```

I have used all available tutorials but cant seem to find the problem causing error in
`agas/addressing_service.cpp.o`

**Comment by hkaiser** [comment] 2017-08-11 16:10
@Rodario: this is a known problem in Boost caused by the fact that it was released before the compiler you're using (gcc 7). Please configure HPX with `cmake -DHPX_WITH_CXX14=ON ...` to work around the issue.

**Comment by hkaiser** [comment] 2017-08-13 22:30
@Rodario do you still have problems? Can we close this now?

**Comment by Rodario** [comment] 2017-08-15 01:53
Jep, the compiler version was the problem, thanks for the quick help!

**Closed** 2017-08-15 13:07 UTC
Labels: category: CMake, compiler: gcc, type: compatibility issue
